### ISSUE TITLE
Add some docs for app.store.update if data changed in mean time

### ISSUE THREAD

**Issue by jviereck** [hoodiehq/hoodie#1]
Looking over the code, I'm not 100% sure what's happening if `app.store.update( type, id, {nr: 1} )` is executed but the same type and id was changed in the mean time on the server.

Is the object on the backend always overwritten with the latest object send by using the `app.store.update` api? Does the backend do some merging on the way? Is there a way to detect there is a conflict (e.g. does `app.store.update` fail?) and what's the best way to resolve it again?

(I think you gave me some of these answers this afternoon, but I'm not 100% sure anymore and some documentation would be helpful in general I guess.)

**Comment by gr2m** [comment]
Thanks for raising the question – and sorry for the late response!

this is how it's working at the moment: your local changes get always pushed, possible conflicts remain in the couch and may be resolved, or just left. Changes coming from remote do always overwrite your local data at the moment, there is no check if your data changed locally meanwhile, we probably should add such a thing.

What would be your desired behavior / API?

**Comment by jviereck** [comment]
> What would be your desired behavior / API?

Maybe have a way to specify a callback `onConflict`, that is called once a conflict is detected. The developer can then implement some functionality to resolve the conflict. If the callback is not specified, the default CouchDB way of handling/merging is used.

Sorry, I still haven't looked too much into how conflict resolving works in CouchDB, so I can only give that high-level API-idea response :/

**Comment by gr2m** [comment]
We have the concept of modular background workers acting on changes in the databases.

What we could do is to implement a "conflict resolution worker". In the admin backend of your app, you could define a JavaScript function that gets called each time there is a conflict and that contains the custom logic to resolve the conflict.

Makes sense?

**Comment by jviereck** [comment]
+1

**Comment by gr2m** [comment]
I've created a new repo for a worker that will resolve conflicts in the backend:
https://github.com/hoodiehq/worker-conflict-resolver
