### ISSUE TITLE
hoodie.account.changePassword does not reject when passed current password is wrong

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#103]
follow up for https://github.com/hoodiehq/hoodie-server/issues/105 by @ro-ka

> When I try to change a password and enter a wrong `currentPassword`, the `handleDone` is called, not the `handleFail` function.
> 
> ``` js
> hoodie.account.changePassword(currentPassword, newPassword)
>   .done(handleDone)
>   .fail(handleFail);
> ```
> 
> On `hoodie.account.signin` and `hoodie.account.signup` it's working as expected.

**Comment by ro-ka** [comment]
Next week is fine. :)

Or should I open an Pull Request if I manage to fix it?

**Comment by gr2m** [comment]
of course, that'd be great!

So problem is: we don't really need the current password to change it, as the user is already authenticated. But we will fix that down the road. Until then, I'd fake it. To check if the current password is correct, send A GET request to the `_users` doc, with HTTP BASIC AUTH headers. If that fails, stop and reject the promise.

Let me know if you have any questions

**Comment by ro-ka** [comment]
Trying that, but the promise always triggers the done. See my commit: https://github.com/ro-ka/hoodie.js/commit/e0030711f259ad4e02c5c30c94b8a55570ed9806

What is missing?

**Comment by gr2m** [comment]
hmmm, have you tried to sign out before sending the request with basic auth?

I'm happy to look into it in a bit. Also, lets chat on IRC for quick questions

**Comment by gr2m** [comment]
for reference: https://github.com/ro-ka/hoodie.js/commit/e0030711f259ad4e02c5c30c94b8a55570ed9806#commitcomment-3635145

CouchDB seems to fallback to session auth when basic auth headers are incorrect. No idea how to fix that yet.

**Comment by zoepage** [comment]
it seems like the couchDB issue was solved. 
https://github.com/hoodiehq/hoodie-server/pull/255

what is missing to fix this bug?

**Comment by gr2m** [comment]
I'm not sure, maybe it's good? Could you try it out and close if you can't reproduce it?

**Comment by zoepage** [comment]
will do!

**Comment by zoepage** [comment]
the bug isn't fixed. you can still change the password.

**Comment by Rezi** [comment]
The bug is still there. If there is no will to fix it, perhaps the old password argument should be removed from the function.

**Comment by janl** [comment]
@gr2m could you have a look?

**Comment by gr2m** [comment]
@lupomontero changes in 
https://github.com/lupomontero/hoodie.js/commit/596e8156428077b53975ea4a47cbc4d46a11193c look good to me, that's how I'd have solved it, too. Didn't test if it's working, but if it does, please send a pull request Lupo :)

**Comment by lupomontero** [comment]
@gr2m It does seem to do the job ;-)

PR sent!

**Comment by Rezi** [comment]
Thanks for the swift fix. You are doing great job guys!
