### ISSUE TITLE
Implement stupid simple statemachine-worker

### ISSUE THREAD

**Issue by mstefaniuk** [hoodiehq/hoodie#105]
Most of long running processes (eg. sign-up) may be replaced with simple workflow / statemachine definitions.

Process definition can be compiled into design document (validations, doc_updates). User tasks would be attachments (HTML parts) and actions would be simple database operations (store, delete, replicate).

Dreamcode example of workflow you can check on https://gist.github.com/mstefaniuk/5671321

**Comment by gr2m** [comment]
sorry, I don't get it at all. How is this simpler than the current setup?

**Comment by mstefaniuk** [comment]
I see it as following:
1. Extending default processes with user tasks (eg. singup proofreading) or action (eg. sending additional email to admin) would be easier.
2. It would be possible to build process editor with graphviz visualization. Process DSL would be compiled and deployed on the fly.
3. There would be clean separation between workers with narrow responsibilities (email sending, sharing, payment authorization) and orchestrated tasks (eg. shopping process).

In fact it would be adding the hoodie features also to server-side.

**Comment by svnlto** [comment]
This still doesn't make sense to me.

**Comment by gr2m** [comment]
closing this one. We just don't get it. If you feel passionate about it, feel free to send a pull request. But maybe wait another few weeks until we ship the new plugin architecture
