### ISSUE TITLE
Document Hoodie's naming rules and conventions

### ISSUE THREAD

**Issue by ejeklint** [hoodiehq/hoodie#106]
Like the use of $someName and "type/this/that" for db names and doc id's. That's all!

**Comment by gr2m** [comment]
May I ask why you're interested in that? These are internal implementation details that we try not to expose via the API. Just wondering

**Comment by janl** [comment]
he wants to steal some ideas for his project :)

**Comment by ejeklint** [comment]
Just thought it could help set a nice standard when dealing with CouchDB best practices. And as Jan says too :P

**Comment by gr2m** [comment]
now that we have the plugins in place, our conventions are as follows:
- we use camelCase for properties
- every object stored has a `type` and an `id` attribute, that gets combined fro couchDB to `_id` in the form of `{type}/{id}`. 
- we only allow characters in type & id that are also allowed for couchDB database names
- tasks are just objects, with a `type` prefixed by `$`
- all events are lowercase letters only
- every user has a database, the name is `user/{userHash}`
- if plugins create own databases, we encourage them to follow the convention

Feel free to ask farther questions

**Comment by janl** [comment]
@gr2m wanna leave this open until we documented this somewhere that isn’t a closed issue? :)

**Comment by ejeklint** [comment]
Thanks for sharing this. And yes, I have completely nicked it all. :)

**Comment by gr2m** [comment]
@janl I put it into [quickstart_for_developers.md](https://github.com/hoodiehq/hoodie.js/blob/master/quickstart_for_developers.md) – good enough for now?

**Comment by janl** [comment]
:+1:
