### ISSUE TITLE
to hoodie or not to hoodie

### ISSUE THREAD

**Issue by sallespromanager** [hoodiehq/hoodie#108]
hi guys,

it's been a good surprise to stumble upon you. it seems a very simple and useful combination of functionality you provide.

 one doubt is if we can have somehow offline persistence ?

**Comment by gr2m** [comment]
hoodie has offline persistence today. All data is stored locally in your browser.

**Comment by sallespromanager** [comment]
cool, is it indexedDB based ? 
Can it be used on mobile with Cordova ?

**Comment by janl** [comment]
On Jul 26, 2013, at 20:57 , salles notifications@github.com wrote:

> cool, is it indexedDB based ? 

localStorage today. Others later :)

> Can it be used on mobile with Cordova ?

Yes.

**Comment by sallespromanager** [comment]
well, 24 hours after getting to know you guys I have a very enthusiastic moment to try hoodie out.

please help me figure out what i might be missing here.

A couple of attempts

https://github.com/hoodiehq/hoodie-server/issues/107

and in another environment I get...

```
hoodie new app

.d$b.  .d$b.  .d$$$$$$b.    .d$$$$$$b.  .d$$$$$$b.  .d$b..d$$$$$$$$b.
$$$$$..$$$$$.$$$$$$$$$$$b .$$$$$$$$$$$b $$$$$$$$$$b $$$$$$$$$$$$$$$P'
$$$$$$$$$$$$d$$$$$$$$$$$$bd$$$$$$$$$$$$b$$$$$$$$$$$b$$$$$$$$$$$$$$$b.
$$$$$$$$$$$$Q$$$$$$$$$$$$PQ$$$$$$$$$$$$P$$$$$$$$$$$P$$$$$$$$$$$$$$$P'
$$$$$´`$$$$$'$$$$$$$$$$$$''$$$$$$$$$$$$'$$$$$$$$$$P $$$$$$$$$$$$$$$b.
'Q$P'  'Q$P'  'Q$$$$$$P'    'Q$$$$$$P'  'Q$$$$$$$P  'Q$P''Q$$$$$$$$P'

  hoodie  created project at /home/rafael/hoodie/app/
Cloning into 'app'...
remote: Counting objects: 28, done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 28 (delta 2), reused 22 (delta 2)
Unpacking objects: 100% (28/28), done.
  hoodie  Replaced package.json
  hoodie  removing .git folder
npm ERR! git fetch -a origin (git://github.com/hoodiehq/worker-users.git) error: cannot open FETCH_HEAD: Permission denied
npm ERR! git fetch -a origin (git://github.com/hoodiehq/hoodie-server.git) error: cannot open FETCH_HEAD: Permission denied
npm ERR! Error: Command failed: error: cannot open FETCH_HEAD: Permission denied
npm ERR!
npm ERR!
npm ERR!     at ChildProcess.exithandler (child_process.js:637:15)
npm ERR!     at ChildProcess.EventEmitter.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:735:16)
npm ERR!     at Socket.<anonymous> (child_process.js:948:11)
npm ERR!     at Socket.EventEmitter.emit (events.js:95:17)
npm ERR!     at Pipe.close (net.js:466:12)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.2.0-24-virtual
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/rafael/hoodie/app
npm ERR! node -v v0.10.13
npm ERR! npm -v 1.3.2
npm ERR! code 1
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/rafael/hoodie/app/npm-debug.log
npm ERR! not ok code 0
  hoodie  Installed all dependencies
You can now start using your hoodie app

     cd app
     hoodie start
```

**Comment by svnlto** [comment]
```
npm ERR! git fetch -a origin (git://github.com/hoodiehq/worker-users.git) error: cannot open FETCH_HEAD: Permission denied
npm ERR! git fetch -a origin (git://github.com/hoodiehq/hoodie-server.git) error: cannot open FETCH_HEAD: Permission denied
npm ERR! Error: Command failed: error: cannot open FETCH_HEAD: Permission denied
```

something's gone wrong while cloning the repos.

**Comment by janl** [comment]
@svnlto can we detect the status code of the commands we launch and provide a useful error messages?

**Comment by svnlto** [comment]
@janl right now we're just passing through whatever npm reports. What sort of detection would you run? Also, define useful.

**Comment by sallespromanager** [comment]
well, no matter what stands upon us, it's a really good feeling to be working on this in a cold sunny south brazilian afternoon and in a couple of minutes "the hoodies" themselves to get back to you ! great to start with !

let's hood on. i'll try the couchdb.ini permissions for a start. the npn stuff i might not be able to help.

**Comment by svnlto** [comment]
@janl I've done some digging. We might be better of using npm programatically. 
https://github.com/isaacs/npm/#using-npm-programmatically

Will create an issue for that.

**Comment by janl** [comment]
@svnlto ah, cool, good call.

I was thinking about the scenario where the `git clone my-first-hoodie` and `npm install` on `hoodie new` would fail. My think is that a unix program will have an exit code that is `0` (zero) on success non-`0` on error. I thought we could check the exit code of `git` and `npm` in these cases and tell the user “we had trouble with the set up,make sure npm and github are up and reachable and try again”.

**Comment by gr2m** [comment]
can this be closed?

**Comment by svnlto** [comment]
closing for now. will open separate issue on `hoodie-cli`
