### ISSUE TITLE
More examples/multi-page apps

### ISSUE THREAD

**Issue by ile** [hoodiehq/hoodie#109]
Hi,

Could we have more Hoodie examples, please? My-first-hoodie is quite minimal. More extensive examples would help to tackle more problemsm I'm sure.

In particular I'm interested in multi-page apps/routing, if that's feasible with Hoodie. 

Thanks.

**Comment by ile** [comment]
Hoodie admin console seems to have some multi-page(ish) functionality. The URLs have a `#` in them though as in `http://192.168.1.35:2005/#modules/appconfig` 

Can I do without `#`?

**Comment by ile** [comment]
Also, were there some docs for running Hoodie apps on mobile phones? What is possible, what are the limitations etc...?

**Comment by janl** [comment]
Heya, we definitely more examples, thanks for opening this ticket :)

As for multi-page apps and their feasibility: Hoodie doesn’t care. You are responsible for any frontend code, routing, pages, anything, Hoodie just gives you an abstraction over backend tasks like account creation and data storage/sync. What you do with your URLs and views and everything is entirely up to you and you can pick any of the many solutions (including Backbone, Angular, jQuery UI, Ember etc.).

I hope this answers the question about multi-page apps :)

**Comment by espy** [comment]
Hi @ile, 
as Jan already said, Hoodie has nothing to do with how you do routing. Pocket uses Backbone routes, I've used [davis.js](http://davisjs.com/) too for a Hoodie app, it really doesn't matter. You're free to build your app however you want :)

**Comment by gr2m** [comment]
For example, you can use https://github.com/bbn/backbone-hoodie to use hoodie as the "backend" for backbone. It's quite simple to make similar adapters for all the other MV\* frameworks.
