### ISSUE TITLE
What does `hoodie.store` do when a document gets changed locally and remotely?

### ISSUE THREAD

**Issue by janl** [hoodiehq/hoodie#110]
This is one for @gr2m and I thought it is worth asking it here and keep a permanent record.

What happens in this scenario:
1. `hoodie.store` creates document A.
2. Document A gets pushed to the server.
3. Document A gets updated on the client in `hoodie.store`.
4. Document A also gets updated on the server by a plugin.
5. The server notifies the client about the change in Document A (are we using _changes here?).
6. ??? (What happens in `hoodie.store` as it detects that the server has a different version).

(I think I knew the answer once, but I completely blank on it, so I’d appreciate a refresher :)

**Comment by gr2m** [comment]
right now, remote always wins. There is no detection if the object has local changes. That's something for later.

**Comment by janl** [comment]
ok, thanks!
