### ISSUE TITLE
If a user logs in from two devices...

### ISSUE THREAD

**Issue by brainkim** [hoodiehq/hoodie#112]
...goes offline, modifies her data from both, and then comes back online, how does syncing work? Does hoodie have some notion of conflict resolution? Are there mechanisms which prevent this from ever happening?

This is a beginner question. Imma start playing around with hoodie as soon as I can. Looks neat.

**Comment by gr2m** [comment]
both devices will push their changes as soon as their are online again. If an object has been changed with both devices, a conflict will be created in the backend (CouchDB), there will be one winner that both will see. The "looser" will disappear, but the data is not lost and can be recovered.

We want to allow for custom conflict resolution logic in the future, but it's not a priority at the moment. 
I'll close this issue, but please feel free to ask farther questions

**Comment by brainkim** [comment]
I apologize if issues isn't the place to ask questions. Thanks for the response!

**Comment by gr2m** [comment]
not at all, perfect place to ask questions, I just close issues unless the relate to problems / bugs in the current code, just to keep the oversight.
