### ISSUE TITLE
workarounds

### ISSUE THREAD

**Issue by sallespromanager** [hoodiehq/hoodie#115]
hi,

thsi is to depict my current working status with hoodie and get some advice on how to get along.

i have only been able to create/deploy a new hoodie app as such 

```
sudo hoodie new app
 sudo chown -R myuser app
cd app
HOODIE_BIND_ADDRESS=0.0.0.0 COUCH_URL=http://127.0.0.1:5984 hoodie start
```

it starts hoodie...

```
Waiting for CouchDB [-*----] SUCCESS
Please set an admin password:

WWW:   http://0.0.0.0:6004
Admin: http://0.0.0.0:6005

[changes] using changes feed fallback
Starting: 'users'
[users] [Setup] reading global config from modules/module/appconfig …
All workers started.
[users] [Setup] reading user config from modules/module/users …
[users] [Setup] /modules/users not yet setup
[users] creating skeleton/user database …
[users] [Setup] creatinging object in modules database …
```

then, it can signup a new user but does not create or store the user/xxxxx database, as it does when the whole process is done locally.

Another strange thing is if i am not logged into Futon, it shows `unauthorized` GET request 
`http://myserver:6004/_api/user%2F3913242/_changes?include_docs=true&since=6&heartbeat=10000&feed=longpoll 401 (Unauthorized)`

i am also not sure when I try to create another app to access hoodie DB, if I shall use

`var hoodie  = new Hoodie(http://myserver:6004)`

or

`var hoodie  = new Hoodie(http://myserver:5984/_api)`

**Comment by gr2m** [comment]
if `hoodie start` says: `WWW:   http://0.0.0.0:6004`, then you want to connect with

```
var hoodie = new Hoodie(http://myserver:6004/_api) 
```

You said it's working locally, right? What's the system you deployed it to?

**Comment by sallespromanager** [comment]
hallo gregor,

everything works fine in my Mac locally. the situations i have described are on Ubuntu 12.04 LTS.

**Comment by gr2m** [comment]
sorry I didn't get back to you. Does the problem still persist? Please make sure to update to the latest versions of hoodie-server.

For linux questions, best would be to ask in our [IRC chat](irc://irc.freenode.net/#hoodie) room. Or open an issue over at https://github.com/hoodiehq/hoodie-server/issues as there are some Linux people listening :)
