### ISSUE TITLE
move request pooling into hoodie.js core

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#118]
I made `withSingleRequest` & `withPreviousRequestsAborted` for request pooling in the  `hoodie.account` pooling.

I think `withSingleRequest` should be the default behavior of GETs / DELETEs and `withPreviousRequestsAborted` the default behavior for PUTs / POSTs in  `hoodie.request`.

That means if I call `hoodie.request('GET', '/_session')` several times before the first request finishes, the subsequent calls don't send another request, but simply get the promise of the first.

**Comment by svnlto** [comment]
+1

**Comment by gr2m** [comment]
closing in favor of https://github.com/hoodiehq/hoodie-client/issues/81
