### ISSUE TITLE
add '/_api' automatically when initializing Hoodie

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#119]
to make a hoodie instance connected to a remote located on a different domain, we currently need to do

``` js
hoodie = new Hoodie('https//example.com/_api')
```

We should hide the /_api part, that should work already:

``` js
hoodie = new Hoodie('https//example.com')
```

**Comment by svnlto** [comment]
I'd leave it as is for now.

**Comment by gr2m** [comment]
now that v0.3 is out, can we kick it? I find `/_api` is an internal implementation detail that we should as we do with all the other things.

I'd add a deprecation warning for current apps initializing with `/_api` for some time

**Comment by svnlto** [comment]
go for it.
