### ISSUE TITLE
building public apps

### ISSUE THREAD

**Issue by aaronmoodie** [hoodiehq/hoodie#121]
Adding this here on Jan's suggestion.

In Hoodies's current state, what would be the best way to add an item (post) that is publicly viewable and voteable? eg: a reddit/HN style app. 

I see that the public and sharing features are in development, but without those, what would be the best way to achieve this?

**Comment by geelen** [comment]
I've been hacking on this project of Aaron's too, and trying to find a way to fit our data model in. I'm freaking _loving_ working with Hoodie so far, I'm super keen to figure out how to make it work.

Our use case is basically a single global **List** of **Posts**, which gets ranked by users' votes. Each user can submit posts, exactly like Reddit or HN. What we're trying to understand is where to put the data, how users can have partial access (vote up/vote down) to the posts, and add Posts but not remove them.

I'd been thinking that each user could have a list of their submissions, and a list of things they've voted for, and someone we could use a view in Couch to generate the List (mapping over all the users' stores), but I don't know enough Couch to know if that's possible or efficient. It does have the advantage of ensuring that each user only updates their own database, and looking through the source I see you just proxy some requests (anything starting with _api, it appears) to Couch, so we could have each client hit that JSON endpoint.

Our other idea is more traditional, with a List document, a Posts database, and record votes against each. But I see that the Global store and fine-grained roles and access control is still a work-in-progress for Hoodie, and I believe we'd need both for our use case.

Anyway, wanted to get your thoughts. Should we try to dive in and put some more logic into Couch itself, or should we hold tight until sharing/roles/global stores are released?

**Comment by gr2m** [comment]
Hey Glen / Aaron, I'll think about it and respond later today or early tomorrow

**Comment by gr2m** [comment]
We're currently finishing up the new plugin architecture, I'd definitely wait for that. Once it's in place, you can build the functionality with a hoodie plugin. Here's an example plugin, the code might not be 100% accurate, but it's good to get an idea: https://github.com/hoodiehq/hoodie-plugin-dreamthing

The base setup of Hoodie is: each user has an own database. The user can create / update / remove posts and create / update / remove votes. So far, that's simple with Hoodie core. You could create an extension for the frontend API ([see the dreamthing example](https://github.com/hoodiehq/hoodie-plugin-dreamthing/blob/master/hoodie.dreamthing.js)), that could provide a nice API like `hoodie.post.add(properties) / .update(properties) / remove()`,  `hoodie.post.voteUp( postId ) / .voteDown( postId ) / .removeVote( postId )` and `hoodie.post.findAll()` to list all public posts.

Then you'd need a worker ([see the dreamthing example](https://github.com/hoodiehq/hoodie-plugin-dreamthing/blob/master/worker.js)). The worker would the following:
1. create a central `posts` database, with public read
2. listen to new user accounts being created and setup filtered replications from userDb ➔ posts

The worker code would something look like this:

``` js
// this is a Node.js module. The function gets 
// executed on Hoodie Server startup.
module.exports = function(hoodie, doneCallback) {

  function createPostsDatabase(callback) { /* ... */ };
  function startReplication(db) { /* ... */ };
  function stopReplication(db) { /* ... */ };

  hoodie.account.on('add', startReplication)
  hoodie.account.on('remove', stopReplication)
  hoodie.account.on('remove', )

  createPostsDatabase( doneCallback );
};
```

Last but not least you could also create a custom view for pocket for statistics and administrative tasks.

Makes sense?

**Comment by allain** [comment]
I was wondering this too. This is quite nice.

So, there'd be no need to setup any kind of writing permissions on the posts db for the user.

Voting on other users' posts could be done by just creating a vote document and replicating vote types with user dbs. The posts plugin would then be responsible for aggregating the results using views or some other mechanism. Cool.

Thanks for responding @gr2m

**Comment by gr2m** [comment]
@aaronmoodie @allain @geelen 

are you guys good? The new plugin infrastructure is in place now. Feel free to create follow up tickets
