### ISSUE TITLE
My observations on Cheesecake

### ISSUE THREAD

**Issue by espy** [hoodiehq/hoodie#123]
- [ ] First run pauses at `[users]  [Setup] creatinging object in modules database …` until I sign in to Pocket or Futon
- [ ] It says "creatinging" :D
- [ ] The signup button is missing on first run, or whenever I open the app without a session. SignUp per console works, signup button appears as soon as I'm logged in.

Everything else I've tried works fine, storing and retrieving, password reset, sync between two browsers.

**Comment by gr2m** [comment]
looks all good to me now :)
