### ISSUE TITLE
hoodie.task API

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#125]
as part of the new plugin architecture, we want to provide a nice API for handling tasks in the frontend as well. At the moment, to create a new task, e.g. to send an email, one has to do:

``` js
hoodie.store.add('$email', emailProperties)
```

This exposes the implementation of how tasks are handled in Hoodie internally, and it shouldn't. Also, tasks don't need the entire store API. For example, the user should not be able to change a task's properties after it was created. Instead, the task has to be cancelled and  a new task with the updated properties has to be started. And it also doesn't make sense that creating a task resolves after the object representing it gets stored locally, instead it should resolve once the task has been finished, or be rejected if there was an error doing so.

To reflect that, and to make clear that tasks are different from data, I'd suggest we give it it's own API:

``` js
// starts the task. Once the worker picked it up, it either gets removed (success) or it gets marked as failed
// Rather than resolving right away when the task object was saved locally, it waits until it gets removed from remote
hoodie.task.start('email', emailProperties)

// stop a running task, adds a `canceledAt` timestamp, then removes it
hoodie.task.cancel('email', 'id123')

// if a task had an error, removes the error so task gets restarted
// if task is pending, cancels it and restarts once the worker canceled it
hoodie.task.restart('email', 'id123')

// and probably
hoodie.task.cancelAll()
hoodie.task.restartAll()

// while we're at it
hoodie.task.start('email', emailProperties, { timeout: 20000 })
```

For a plugin creator, (dream) code would look like

``` js
Hoodie.extend(function(hoodie) {
  hoodie.directMessages = {
    send: hoodie.task('direct-message').start,
    on: hoodie.task('direct-message').on
  };
});
```

Find the latest version at https://github.com/hoodiehq/hoodie.js/tree/v0.4-peanuts-task-api#tasks

Thoughts? @svnlto @caolan @espy @janl

**Comment by janl** [comment]
`canceledAt` should be `cancelledAt`.

**Comment by gr2m** [comment]
Is this just taste or is there a consensus to use British English instead of American English?

**Comment by janl** [comment]
ah, I didn’t know it was an BE/AE thing. AE usually looks grammatically wrong to me.

**Comment by janl** [comment]
> `hoodie.task.cancel('email', 'id123')`

where do I get `'id123` from?

**Comment by gr2m** [comment]
``` js
hoodie.task.start('email', properties)
.then( function(emailTask) {
  emailTask.id // is set now, this is where 'id123' comes from
});
```

I'm also thinking to allow a shortcut:

``` js
var taskPromise = hoodie.task.start('email', properties)
/* do some funk */
hoodie.task.cancel(taskPromise)
```

**Comment by janl** [comment]
thanks!

Next:

If I understand correctly, tasks only get `then()` / `fail()` callbacks, right? What happens if I create a lot of tasks when offline? Doesn’t this a lot of objects in memory that are held onto until we are online again?

**Comment by gr2m** [comment]
> If I understand correctly, tasks only get then() / fail() callbacks, right? What happens if I create a lot of tasks when offline? Doesn’t this a lot of objects in memory that are held onto until we are online again?

yes. If you reload the page you loos the callbacks. If that's a problem, you can still listen to `success` and `error` events

**Comment by gr2m** [comment]
There is also a `progress` callback, that we do not use yet, but that might make sense for certain tasks. A worker could pick up a task and just add the `$processedAt` timestamp while it is still running it, maybe waiting for an external service. Then once it's done, it removes it. In the frontend, the first update would trigger the `progress` callback, the second the `done` callback.

But that's for later.

**Comment by janl** [comment]
cool, can you add examples for “listening to `success` and `error` events”?

**Comment by gr2m** [comment]
I got examples in the readme:
https://github.com/hoodiehq/hoodie.js/tree/v0.4-peanuts-task-api#tasks

``` js
// task could not be completed
hoodie.task.on( 'error', function( errorMessage, task) { } )

// task completed successfully
hoodie.task.on( 'success', function( completedTask) { } )
```

good?

**Comment by janl** [comment]
excellent, didn’t see these :)

**Comment by janl** [comment]
thumbs up then.
