### ISSUE TITLE
hoodie.my.* -> hoodie.*

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#13]
Here's a list of current modules we have

Core:

``` js
// core
hoodie.my.store
hoodie.my.config
hoodie.my.account
hoodie.my.remote

//extensions
hoodie.user
hoodie.share
hoodie.global
hoodie.email
```

Why not kick the `.my` and go with the following?

``` js
// core
hoodie.store
hoodie.config
hoodie.account
hoodie.remote

//extensions
hoodie.user
hoodie.share
hoodie.global
hoodie.email
```

If I remember it correctly, we introduced the `.my` prefix to make it clear that all the modules are me-centred. But no I think: they all are me centered, so why not simply kick it? Backend is where we have to handle multiple users, but in the frontend, there is always only one user who's logged in, isn't it?

**Comment by espy** [comment]
Kinda makes sense. Don't see any immediate downside either. It's easier to remember, too: "wait, did .share need .my or not? Is .config in .my or isn't it?"

**Comment by janl** [comment]
+1.

**Comment by janmonschke** [comment]
makes totally sense!
