### ISSUE TITLE
rethink hoodie.store.update(type, id, attrs): how to handle NOT_FOUND?

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#134]
when I do

``` js
hoodie.store.update('doc', '123', { title: 'new title' })
```

it does 2 things:
1. when doc/123 exists, it sets the new title property.
2. if doc/123 does not exist, it creates doc/123 in store with title set to 'new title'

I have no clue why I implemented it this way, and now I find it rather confusing and error prone. 

I run into this while implementing `hoodie.task.restart(type, id)`. I want to use the `store.update` method internally, but I certainly du not want a new task to be created if the task could not be found.

So I suggest to change the behavior of hoodie.store.update, so that it fails when the object cannot be found. If there is a use case when we actually want that, and the use case is reasonable, we can still add a `updateOrAdd` method. But I really can't think of any at the moment.

Any objections? @janl @caolan @svnlto @espy

**Comment by janl** [comment]
This is a classic issue and both versions are a valid use case, so picking defaults is what we should be looking at.

Generally the update-fail-on-not-found strategy is the default, with either a config option or a separate method to do the update-or-create case.

A few options:

```
hoodie.store.update(type, id, add=true);
hoodie.store.update(type, id, {add:true});
hoodie.store.insert(type, id); // kinda stolen from SQL
hoodie.store.updateOrAdd(type, id); // as proposed above
```

I don’t have a preference as long as we have one solution :)
