### ISSUE TITLE
remove hoodie.store.save from public API

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#136]
it's more of a reminder of. I've run into this thought so many times now, it's time to bring it to the next level :)

`hoodie.store.save` is rather a method that is meant to be used internally. And if we expose it, we should rename it to `replace`, because that's what it does. Lots of things can go wrong when using `hoodie.store.save` directly, so I'd rather hide it from the API entirely.

**Comment by janl** [comment]
+1 to removing dangerous things.

**Comment by svnlto** [comment]
yeah, lets hide it away.
