### ISSUE TITLE
uuid should be renamed

### ISSUE THREAD

**Issue by allain** [hoodiehq/hoodie#140]
uuid means something specific to most developers (https://npmjs.org/package/uuid) it makes certain guarantees that this uuid method does not.

Even changing it to uid would solve the problem.

**Comment by gr2m** [comment]
agreed. uuid is also to technical. How about `hoodie.genereateId()`?
@svnlto

**Comment by allain** [comment]
Works for me.

+1

**Comment by svnlto** [comment]
> How about hoodie.genereateId()?

Works.
