### ISSUE TITLE
Pagination for findAll

### ISSUE THREAD

**Issue by bastianallgeier** [hoodiehq/hoodie#141]
Hey guys, 

how do you handle pagination with the findAll method?

**Comment by janl** [comment]
I will have to leave the answer for this to @gr2m, but out of curiosity, how many records do you have?

**Comment by bastianallgeier** [comment]
It depends on the user. Between 3.000 and 30.000 – pretty vague, I know :) But probably too much to get them all at once.

**Comment by svnlto** [comment]
I've solved this before with Backbone (using various pagination mixins). If you're using backbone, here's what you can use to act on hoodie data https://github.com/bbn/backbone-hoodie

**Comment by allain** [comment]
If I'm reading this properly, because findAll is performed client side (unless localStorage is unavailable), then the problem of pagination is up to the client to implement using whatever scheme they see fit?

**Comment by gr2m** [comment]
@allain that is correct.

There is no build-in feature for pagination in hoodie.core. I'd leave that to the apps
