### ISSUE TITLE
findAll returning empty array just after signIn

### ISSUE THREAD

**Issue by caolan** [hoodiehq/hoodie#142]
If we refresh the page after sign-in we get the results, if we wait for setTimeout 1000ms then we get the results too, but when we check directly after a 'signin' event the findAll call returns an empty array. I assume there is some timing issue when syncing with the server?

**Comment by caolan** [comment]
cc @lupomontero

**Comment by lupomontero** [comment]
Add this to `www/assets/main.js` in [my-first-hoodie](https://github.com/hoodiehq/my-first-hoodie):

``` js
hoodie.account.on('signin', function () {
  console.log('signed in!');
  hoodie.store.findAll('todo').done(function () { console.log(arguments); });
})
```

`findAll` returns an empty even if user has objects stored in database.

**Comment by janl** [comment]
@caolan, @lupomontero check the mapchat app and how it is done there

**Comment by gr2m** [comment]
This usecase is covered by https://github.com/hoodiehq/hoodie.js/blob/master/src/hoodie/local_store.js#L159. After signin, hoodie is in bootstrapping mode until the first pull of data finishes, and enqueues requests to the store until then.

Must be a bug, I'll look into it

**Comment by gr2m** [comment]
Is this on my-first-hoodie `#master` or `#plugins`?

**Comment by gr2m** [comment]
Ok, I just checked both and both are affected. I'll look into it

**Comment by gr2m** [comment]
If you created the app using `hoodie new myapp hoodiehq/my-first-hoodie#plugins`:
remove node_modules/hoodie-server and run `npm install` to get the fixed. 

If you created the app using `hoodie new myapp`:
replace /www/assets/vendor/hoodie.js with https://github.com/hoodiehq/hoodie.js/blob/master/dist/hoodie.js

**Comment by lupomontero** [comment]
@gr2m Many thanks! Works as expected now :-)
