### ISSUE TITLE
change order of namespaced store events

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#146]
At the moment we do:

``` js
hoodie.store.on('add:note',    function (newObject) {});
hoodie.store.on('add:note:uuid123',    function (newObject) {});
```

But I think we should instead do 

``` js
hoodie.store.on('note:add',    function (newObject) {});
hoodie.store.on('note:uuid123:add',    function (newObject) {});
```

Because that makes more sense with the scoped store:

``` js
hoodie.store('note').on('add')
hoodie.store('note', 'uuid123').on('add')
```

And I think that @caolan also used this order in the hoodie-server code, right? 
This change might break some code out there ... but I think it's the right thing to do.

@svnlto  @janl

**Comment by gr2m** [comment]
This is a blocker for me unfortunately. I'll add the old way to trigger events in there as well, so it will still work, but not be documented anymore. This way we don't break any code. It might have quite some impact on performance though, I'm not sure.

Any thoughts?

**Comment by janl** [comment]
@gr2m can't you just work in a branch until everyone had a chance to comment? :)

**Comment by gr2m** [comment]
yeah, I'm working on `store_events_new_order` branch, no worries

**Comment by svnlto** [comment]
I myself welcome the new `{{task}}:{{item}}:{{action}}` event namespace

**Comment by janl** [comment]
thumbs up

**Comment by caolan** [comment]
I like it, can you open me an issue on hoodie-plugins-api to check the
order there too?

**Comment by janl** [comment]
Done! https://github.com/hoodiehq/hoodie-plugins-api/issues/22
