### ISSUE TITLE
testing: make coverage thingy optional

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#149]
I'd like to run `node node_modules/karma/bin/karma start --no-single-run` without the coverage thingy minifying all the script files.

**Comment by gr2m** [comment]
@svnlto could you please look into this? It's really obstructive

**Comment by svnlto** [comment]
@gr2m this is being fix as part of the saucelabs PR.

**Comment by gr2m** [comment]
fixed via #172
