### ISSUE TITLE
Shares: Per-user public Data

### ISSUE THREAD

**Issue by espy** [hoodiehq/hoodie#155]
It should be possible to make some of a user's data public. This means absolutely anyone can see it. This does not mean you can get every single user's `cats` document with a single Hoodie command, though, that belongs in global public shares (#154). Think of this as the API you'd use to build each single public-facing user profile page.

**Comment by gr2m** [comment]
see https://github.com/hoodiehq/hoodie-plugin-public-data. Let's discuss farther in there
