### ISSUE TITLE
Shares: Group Shares (and User to User shares)

### ISSUE THREAD

**Issue by espy** [hoodiehq/hoodie#156]
It should be possible for users to share (read/write/etc.) data within a group of users. Since this group can conceivably just have two users, the same mechanism might be used to accommodate user to user sharing (such as direct messaging) as well.

**Comment by svnlto** [comment]
I'd like to add the following comment to the discussion.

`Jan____> e.g.: hoodie-plugin-share-private, hoodie-plugin-share-group, hoodie-plugin-share-public etc.`

**Comment by janl** [comment]
Thanks @svnlto. For context: I think there are more than one connotation for what we call “shares” at the moment, I see at least three and I think it is worth separating them, at least in the beginning.

I see:
1. private shares, aka hoodie-plugin-shares-private, that basically do private messaging between two users. A “message” could be a shared document or whatever.
2. public shares, aka hoodie-plugin-shares-plublic, that allows individual users to put data in a place for the world to read. / A version of that would be to have a share that aggregates public user data for things like “top 100 photos by all users”.
3. group shares, aka hoodie-plugin-shares-group, that implements what we usually explain with “Google Docs type of sharing model”.

Eventually, 1. and 2. should be possible to be implemented using 3., but I think we have a better chance of shipping any one of them at all if we start separately. We can always move shared code into (node-)modules and consolidate plugins later.

**Comment by gr2m** [comment]
1. sounds like a peer-to-peer system, right? It's not that we would collaborate on a message I've sent to another user, it's more of a read-only copy?
2. That's what we once implemented with [user stores](publicShares), right? We had the idea to have one private and one public store per user, and all data from the public stores would be replicated to a central global store, that would allow for things like "top 100 photos by all users"
3. is what we describe under [userShares](http://hood.ie/#userShares) on the homepage, right?

If I got that right, I'd totally agree to keep them separated.

**Comment by janl** [comment]
@gr2m sounds correct.

**Comment by allain** [comment]
I have a situation where I need a cascading share of sorts.

I need a pool of data onto which users with a certain role can read and write to, but that only certain documents and only certain properties of those documents should be made public. Normal users do not have write access to the public share.

In that scenario I'd implemented a chain of databases with transforms that were applied by listening to the changes feed.

todos-all  => todos-public

in hoodie you might have hoodie.share('todos') and then depending on your account roles, it would determine which of the underlying databases you were replicating with and how.

It is also conceivable that you might want to chain these databases together to support testing of data before it goes live to the public

todos-all => todos-testing => todos-public

and then have an explicit stage specified for the share as: hoodie.share('todos', 'testing')

In case you're wondering, I do indeed have a set of apps that require this kind of complexity.

**Comment by gr2m** [comment]
allain: would you mind to open a separate issue for your use case? I think your input would be very valuable, I'd like to have a dedicated issue for farther discussion

**Comment by gr2m** [comment]
Hey everyone, 

I created 3 plugin repos for different share use cases:
1. [Hoodie Shares Plugin](https://github.com/hoodiehq/hoodie-plugin-shares)
   share data with specific other users, with detailed settings on read/write access.
2. [Hoodie Public Data Plugin](https://github.com/hoodiehq/hoodie-plugin-public-data)
   Enable public user data, think of the public twitter wall. Would also include a global store, where all public user stores replicate to, so it would allow for things like "top 100 photos by all users"
3. [Hoodie User Groups Plugin](https://github.com/hoodiehq/hoodie-plugin-user-groups)
   A user can create a group and add other users to it. Data is shared within the group. A group would usually be a company

I invite everyone to use the respective issues with questions or dreamcode, on how you'd like to use it.
I'm closing this one, but feel free to reopen if you see a need
