### ISSUE TITLE
karma saucelabs

### ISSUE THREAD

**Issue by svnlto** [hoodiehq/hoodie#163]
run karma build against multiple browsers on saucelabs.

https://saucelabs.com/opensauce

**Comment by svnlto** [comment]
works: https://travis-ci.org/hoodiehq/hoodie.js/jobs/13972733#L1559

**Comment by gr2m** [comment]
what's the status here?

**Comment by svnlto** [comment]
@gr2m status is: It's working but FF build currently fail because of an issue with tests.
