### ISSUE TITLE
Hoodie plugin website/page

### ISSUE THREAD

**Issue by alanshaw** [hoodiehq/hoodie#169]
Hey guys,

I'm working on a hoodie plugin website/page where you can view hoodie plugins, search them, etc. It's currently looking something like this:

![screen shot 2013-11-11 at 09 02 32](https://f.cloud.github.com/assets/152863/1511549/d193a956-4ab1-11e3-846a-c432cc726f10.png)

I knocked up a "plugins" plugin that is a NPM registry changes feed watcher which adds/updates to a local server database (which has public read access). Client side, it opens the "plugins" database and uses [reactive](https://npmjs.org/package/hoodie-plugin-reactive) to re-render the list automatically when new plugins are changed/updated.

Is this something you guys need/want? If so, what other features should it have?

**Comment by janl** [comment]
SO COOL WANT :D

**Comment by svnlto** [comment]
GIMME!

**Comment by svnlto** [comment]
perhaps we could host this at `plugins.hood.ie` ?

**Comment by lupomontero** [comment]
+1

**Comment by gr2m** [comment]
sexy. +1 on plugins.hood.ie

**Comment by alanshaw** [comment]
Great, I'll put it up on nodejitsu and give you a shout when ready.

**Comment by caolan** [comment]
Nice one @alanshaw, this looks awesome :+1:

**Comment by alanshaw** [comment]
http://hoodie-plugins-www.jit.su/

Ok, so that was a pretty bad first experience. Nodejitsu refused to create me a database through CLI or website (https://twitter.com/_alanshaw/status/399978483364806656). I eventually decided to short circuit and create an account on iriscouch, and when I did, my profile page was stuck on "building account" for a day or so. Instead of using mozilla persona to sign in I signed up using the sign up form on the site with the same email address, this logged me in and took me to my profile page where everything had magically just set up.

If you do this, the COUCH_URL should be https://username.iriscouch.com (no port, and https).

I created another admin user for hoodie to use, since I have to create an environment var in nodejitsu where the password is just plain text. DON'T do that. As soon as I removed the second admin account the site started successfully and I stopped getting 401 errors when trying to access the database my plugin had created.

Anyway, it is finally up there although I get this error when starting up: https://github.com/hoodiehq/hoodie-server/issues/155 ...although things still seem to work.

Roll on "Hoodie hosting for even simpler deployment"

**Comment by alanshaw** [comment]
Forgot to mention - this is the first iteration, please let me know if there are problems that need fixing or features that you want to see added!

Codes are here:
https://github.com/alanshaw/hoodie-plugins-www
https://github.com/alanshaw/hoodie-plugin-plugins

**Comment by svnlto** [comment]
@alanshaw this is so awesome!

> please let me know if there are problems that need fixing

Not really to do with your work per say but I'd like to look at how to 'build' a hoodie project which means compiling assets etc. before deploying. I think your work is a good use-case for that as it perfectly demonstrates my point of 'making too many requests'.

**Comment by alanshaw** [comment]
@svnlto thanks!

I've added `plugins.hood.ie` to domains in the `package.json` so you can [do the dns thing](https://www.nodejitsu.com/documentation/features/dns/#individual-plans) if you want.

**Comment by gr2m** [comment]
@janl can you ADS the DNS Setting  for plugins.hood.ie

—
Gregor Martynus

**Comment by alanshaw** [comment]
Bump!?

**Comment by janl** [comment]
Sorry for the delay. Travels and all.

Here we go: http://plugins.hood.ie :)

WOOOHOOO THANKS @alanshaw!
