### ISSUE TITLE
CouchDB error when signing up

### ISSUE THREAD

**Issue by martin-hewitt** [hoodiehq/hoodie#170]
OS: Mac OS Mavericks
CouchDB: 1.5.0 downloaded from CouchDB site
Hoodie version: 0.3.2 (node v0.10.21, npm 1.3.14, platform: darwin)

When I try and signup on the boilerplate Hoodie app, I get the following as an error:

```
EXIT: {{badmatch,{error,{bad_return_value,{os_process_error,{exit_status,1}}}}}, [{couch_query_servers,new_process,3, [{file,"/Users/jan/Work/build-couchdb-mac/build-couchdb/git-build/https%3A%2F%2Fgit-wip-us.apache.org%2Frepos%2Fasf%2Fcouchdb.git%3A1.5.x/src/couchdb/couch_query_servers.erl"}, {line,477}]}, {couch_query_servers,lang_proc,3, [{file,"/Users/jan/Work/build-couchdb-mac/build-couchdb/git-build/https%3A%2F%2Fgit-wip-us.apache.org%2Frepos%2Fasf%2Fcouchdb.git%3A1.5.x/src/couchdb/couch_query_servers.erl"}, {line,462}]}, {couch_query_servers,handle_call,3, [{file,"/Users/jan/Work/build-couchdb-mac/build-couchdb/git-build/https%3A%2F%2Fgit-wip-us.apache.org%2Frepos%2Fasf%2Fcouchdb.git%3A1.5.x/src/couchdb/couch_query_servers.erl"}, {line,322}]}, {gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,585}]}, {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]}
```

And the line in the Hoodie console is:

```
[www] PUT 500 /_api/_users/org.couchdb.user%3Auser%2Fmartin 8ms - 1.06kb
```

**Comment by gr2m** [comment]
@caolan @janl does that make any sense to you? The

```
PUT 500 /_api/_users/org.couchdb.user%3Auser%2Fmartin
```

looks good to me

**Comment by gr2m** [comment]
@martin-hewitt does the error still exist? Could you try to recreate a new up and see if it's still the case?

**Comment by janl** [comment]
That looks like the CouchDB install is faulty.

**Comment by martin-hewitt** [comment]
This was the Mac binary downloaded from the Apache CouchDB website. I'll try and replicate the issue tomorrow.

**Comment by janl** [comment]
@martin-hewitt if you can paste your `data/couch.ini` and `data/couch.log`, that’d be nice :)

**Comment by martin-hewitt** [comment]
Just tried this on my work machine and couldn't replicate this issue, I'll try later today on the machine I originally experienced the issue on.

**Comment by gr2m** [comment]
@martin-hewitt you good now? Feel free to reopen the issue if not

**Comment by briancleland** [comment]
Hi, I'm getting a similar error on a new install of Hoodie when I try to sign up. 

Mac OSX 10.9.5
Hoodie Version: 0.6.1 (node v0.10.32, npm 1.4.28, platform: darwin)

Link to data/couch.log - http://pastebin.com/raw.php?i=1A1hL1bh

Error message: 
{"error":"{bad_return_value,{os_process_error,{exit_status,133}}}","reason":"{gen_server,call,\n            [couch_query_servers,\n             {get_proc,{doc,<<\"_design/_auth\">>,\n                            {1,\n                             [<<117,239,204,225,240,131,49,109,98,45,56,159,\n                                63,152,19,247>>]},\n                            {[{<<\"language\">>,<<\"javascript\">>},\n                              {<<\"validate_doc_update\">>,\n                               <<\"\n    function(newDoc, oldDoc, userCtx, secObj) {\n        if (newDoc._deleted === true) {\n            // allow deletes by admins and matching users\n            // without checking the other fields\n            if ((userCtx.roles.indexOf('_admin') !== -1) ||\n                (userCtx.name == oldDoc.name)) {\n                return;\n            } else {\n                throw({forbidden: 'Only admins may delete other user docs.'});\n            }\n        }\n\n        if ((oldDoc && oldDoc.type !== 'user') || newDoc.type !== 'user') {\n            throw({forbidden : 'doc.type must be user'});\n        } // we only allow user docs for now\n\n        if (!newDoc.name) {\n            throw({forbidden: 'doc.name is required'});\n        }\n\n        if (!newDoc.roles) {\n            throw({forbidden: 'doc.roles must exist'});\n        }\n\n        if (!isArray(newDoc.roles)) {\n            throw({forbidden: 'doc.roles must be an array'});\n        }\n\n        for (var idx = 0; idx < newDoc.roles.length; idx++) {\n            if (typeof newDoc.roles[idx] !== 'string') {\n                throw({forbidden: 'doc.roles can only contain strings'});\n            }\n        }\n\n        if (newDoc._id !== ('org.couchdb.user:' + newDoc.name)) {\n            throw({\n                forbidden: 'Doc ID must be of the form org.couchdb.user:name'\n            });\n        }\n\n        if (oldDoc) { // validate all updates\n            if (oldDoc.name !== newDoc.name) {\n                throw({forbidden: 'Usernames can not be changed.'});\n            }\n        }\n\n        if (newDoc.password_sha && !newDoc.salt) {\n            throw({\n                forbidden: 'Users with password_sha must have a salt.' +\n                    'See /_utils/script/couch.js for example code.'\n            });\n        }\n\n        if (newDoc.password_scheme === \\"pbkdf2\\") {\n            if (typeof(newDoc.iterations) !== \\"number\\") {\n               throw({forbidden: \\"iterations must be a number.\\"});\n            }\n            if (typeof(newDoc.derived_key) !== \\"string\\") {\n               throw({forbidden: \\"derived_key must be a string.\\"});\n            }\n        }\n\n        var is_server_or_database_admin = function(userCtx, secObj) {\n            // see if the user is a server admin\n            if(userCtx.roles.indexOf('_admin') !== -1) {\n                return true; // a server admin\n            }\n\n            // see if the user a database admin specified by name\n            if(secObj && secObj.admins && secObj.admins.names) {\n                if(secObj.admins.names.indexOf(userCtx.name) !== -1) {\n                    return true; // database admin\n                }\n            }\n\n            // see if the user a database admin specified by role\n            if(secObj && secObj.admins && secObj.admins.roles) {\n                var db_roles = secObj.admins.roles;\n                for(var idx = 0; idx < userCtx.roles.length; idx++) {\n                    var user_role = userCtx.roles[idx];\n                    if(db_roles.indexOf(user_role) !== -1) {\n                        return true; // role matches!\n                    }\n                }\n            }\n\n            return false; // default to no admin\n        }\n\n        if (!is_server_or_database_admin(userCtx, secObj)) {\n            if (oldDoc) { // validate non-admin updates\n                if (userCtx.name !== newDoc.name) {\n                    throw({\n                        forbidden: 'You may only update your own user document.'\n                    });\n                }\n                // validate role updates\n                var oldRoles = oldDoc.roles.sort();\n                var newRoles = newDoc.roles.sort();\n\n                if (oldRoles.length !== newRoles.length) {\n                    throw({forbidden: 'Only _admin may edit roles'});\n                }\n\n                for (var i = 0; i < oldRoles.length; i++) {\n                    if (oldRoles[i] !== newRoles[i]) {\n                        throw({forbidden: 'Only _admin may edit roles'});\n                    }\n                }\n            } else if (newDoc.roles.length > 0) {\n                throw({forbidden: 'Only _admin may set roles'});\n            }\n        }\n\n        // no system roles in users db\n        for (var i = 0; i < newDoc.roles.length; i++) {\n            if (newDoc.roles[i][0] === '_') {\n                throw({\n                    forbidden:\n                    'No system roles (starting with underscore) in users db.'\n                });\n            }\n        }\n\n        // no system names as names\n        if (newDoc.name[0] === '_') {\n            throw({forbidden: 'Username may not start with underscore.'});\n        }\n\n        var badUserNameChars = [':'];\n\n        for (var i = 0; i < badUserNameChars.length; i++) {\n            if (newDoc.name.indexOf(badUserNameChars[i]) >= 0) {\n                throw({forbidden: 'Character `' + badUserNameChars[i] +\\n                        '` is not allowed in usernames.'});\n            }\n        }\n    }\n\">>}]},\n                            [],false,[]},\n                       {<<\"_design/_auth\">>,\n                        <<\"1-75efcce1f083316d622d389f3f9813f7\">>}},\n             infinity]}"}

**Comment by janl** [comment]
How did you install CouchDB? Which version did you install?

**Comment by briancleland** [comment]
Hi Jan,

Thanks for the quick response.

I followed the instructions here: http://hood.ie/#installation, which installed v1.6.1. I then tried installing older versions of CouchDB (eg, 1.5.0) but got the same error.

**Comment by janl** [comment]
can you remove the brew couchdbs and instead download the mac binary from http://couchdb.apache.org? download & unzip will do

**Comment by briancleland** [comment]
Hi,

That seemed to work. Error message no longer appearing - thanks!
