### ISSUE TITLE
hoodie.plugins property

### ISSUE THREAD

**Issue by svnlto** [hoodiehq/hoodie#171]
I'd like to start a discussion around hoodie extensions. Currently everything that is being added by running `hoodie.extend(pluginName)` is being added directly to the `hoodie` object. I feel there is a need to distinguish between hoodie core plugins and 3rd party plugins, even if it's just to keep the hoodie object clean and free from collisions.

So the proposed solution would be adding 3rd party plugins like so:

``` js

hoodie.extend(pluginName)

hoodie.plugins.pluginName // returns actual plugin
```

Thoughts?

@gr2m @janl

**Comment by allain** [comment]
Personally, I'd leave it to the plugin author. If they like the clarity of adding methods directly to hoodie, they should be able to do so. Yes, it means that there will be collisions, but that's the plugin author's responsiblity. This approach has worked or jQuery.

**Comment by gr2m** [comment]
initially, we had the syntax `hoodie.extend('myplugin', myPluginCode)`, that would give me `hoodie.myplugin.xyz`. We changed it to `hoodie.extend(myPluginCode)` for simplify it. You have to pass the `hoodie` instance anyway to any plugin, so you can't keep plugin developers from messing things up.

There is in theory the problem of conflicts, but I agree with @allain, it worked for jQuery, and I think we should keep things simple and treat plugin developers as adults

**Comment by svnlto** [comment]
fair enough.
