### ISSUE TITLE
Additional user attributes

### ISSUE THREAD

**Issue by nnarhinen** [hoodiehq/hoodie#175]
I'd like to have something like 

`hoodie.account.signIn('user', 'pass', {ding: 'dong'})`

and/or

`hoodie.account.set({ding: 'dong'})`

the plans at https://gist.github.com/gr2m/5463426 look great

**Comment by gr2m** [comment]
I would not allow to set custom properties with the `signIn` method. To keep things simple, I'd suggest to add `set` / `get` / `unset` method similar to [hoodie.config](https://github.com/hoodiehq/hoodie.js/blob/master/src/hoodie/config.js#L21)

btw, what's your exact use case here? If you want to save user settings, simply use the `hoodie.config` API. Custom user attributes would be for things like birthday or address, to have app-specific user data available right in the admin interface.

Another aspects that are related:
- read-only settings, for things like `plan`, that would mark if the user subscribed to a payed plan for example
- secured settings, that are only readable/changeable with the user's password, for things like 3rd party API keys

I know this goes beyond your scope here, but we should consider all these things to assure a coherent API. What you think?

**Comment by gr2m** [comment]
see also #220

**Comment by gr2m** [comment]
closing in favor of #328
