### ISSUE TITLE
Shares: User shares

### ISSUE THREAD

**Issue by nnarhinen** [hoodiehq/hoodie#176]
Thinking of starting implementing shares

On hood.ie there is this code snippet:

``` javascript
// add a new share
hoodie.share.add().done(function (share) {});

// grant / revoke access
share.grantReadAccess();
share.grantWriteAccess();
share.revokeReadAccess();
share.revokeWriteAccess();
share.grantReadAccess('joe@example.com');
share.revokeWriteAccess(['joe@example.com', 'lisa@example.com']);

// add all todo objects to the share
hoodie.store.findAll('todo').shareAt(share.id);

// remove a specific todo from the share
hoodie.store.find('todo', '123').unshareAt(share.id);

// add a new share and add some of my objects to it in one step
hoodie.store.findAll('todo').share()
  .done(function (todos, share) { alert('shared at ' + share.id); } );

// remove objects from all shares
hoodie.store.findAll('todo').unshare();

// remove share
hoodie.share.remove(share.id);

// open a share and load all its objects
hoodie.share('shareIdHere').findAll()
  .done(function (objects) {});

// subscribe / unsubscribe
hoodie.share('shareId').subscribe();
hoodie.share('shareId').unsubscribe();
```

@gr2m is that code still ok?

Backend-wise I thought a share would be a database with all granted users as readers and replication setup between the share and all the user-databases? Would this be a good data model?
#156 is kinda related. I just don't know what kind of group mechanism there is planned for hoodie.

Opinions, notes, suggestions?

**Comment by gr2m** [comment]
That code is currently not working, it used to be in hoodie core but we removed it as part of the new plugin infrastructure. It has to be reimplemented entirely.

Here's the deprecated code for the frontend:
https://github.com/gr2m/deprecated-hoodie-extensions-code

I just arrived from a long flight and need to relax a bit. But I'll put together the concept of how it was implemented in the past tomorrow, to have a starting point

**Comment by svnlto** [comment]
@gr2m if you want to consider [this](https://github.com/hoodiehq/hoodie.js/issues/156#issuecomment-28884804) before writing out an entirely new concept ;)

**Comment by gr2m** [comment]
no worries, I think I even did it before, just have to find it again. I've spent hundreds of hours on this, not going to start from scratch ;)

**Comment by svnlto** [comment]
:thumbsup:

**Comment by nnarhinen** [comment]
So,
what I need is following:

1) A CEO signs up on my application
2) He invites an employee to the application
3) The employee reports stuff on the application with his own credentials
4) The reports appear for the CEO under his own credentials

This is what I thought the shares-code in hood.ie was supposed to do. Create 'shares' between users and every document shared into a 'share' will get available for everyone in the 'share'.

**Comment by gr2m** [comment]
Yes, that could be done with the `hoodie.share` API.

But in your specific case, I think what might even make more sense is something I'd call user groups. A user group could for example be a company.
1. A CEO signs up to your application
2. He creates a group "ACME inc"
3. He invites the employee to the group
4. The Employee signs up, he gets added to the group
5. All data is shared across the group per default

Besides the feature of collaborating on data, it would give the CEO the possibility to manage users in the group, change their roles and maybe even manage their accounts. What you think?

**Comment by nnarhinen** [comment]
Yes, it would definitely be better like that. So do you have some dream code available for group shares? I guess user2user shares could be later implemented on top of group shares?

**Comment by gr2m** [comment]
we don't have dream code for user groups yet. But let's do it together :) I created https://github.com/hoodiehq/hoodie-plugin-user-groups, you should have full access. 

Just create a dreamcode.md describing your use case + some dream code, cool?

**Comment by nnarhinen** [comment]
Thanks! Will take a stab at it later today!

**Comment by gr2m** [comment]
@nnarhinen cool, looking forward to it! I'd suggest you close this issue and link to your dreamcode once you're done

**Comment by svnlto** [comment]
closing this for now, please reopen if needed.
