### ISSUE TITLE
hoodie.task.cancelAll() does not cancel tasks

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#184]

**Comment by gr2m** [comment]
problem is that `handleCancelledTaskObject` prefixes type with $ although it is already prefixed.

But next problem is: cancellAll also removes `$config/hoodie` and other `$config` objects. That's ... bad.

**Comment by gr2m** [comment]
> But next problem is: cancellAll also removes $config/hoodie and other $config objects. That's ... bad.

This is not an issue any more, `$config/hoodie` is no more via #261

**Comment by janl** [comment]
Should this be closed, then?

**Comment by gr2m** [comment]
no, this still needs to be fixed:

> problem is that handleCancelledTaskObject prefixes type with $ although it is already prefixed.

**Comment by janl** [comment]
Ok

**Comment by gr2m** [comment]
I checked with latest master and it works as expected now
