### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by dirkk0** [hoodiehq/hoodie#196]
Hi,

I tried to install Hoodie today and ran into a problem. I am on Ubuntu 12.04 on EC2, node is v0.10.22, npm is v1.3.14.

Hoodie installed fine, but on `hoodie start` I get this error:
`ERR! Error: EACCES, mkdir '/home/ubuntu/myappname/data'`
My guess: since I installed hoodie with sudo, the ubuntu user cannot create files in this directory.

What did I do wrong?

Thanks,
  Dirk

**Comment by janl** [comment]
Heya Dirk,

the system user that does `hoodie new myapp` and `hoodie start` must be the same.

You could try to `chown` `myapp` to the ubuntu user you ran `hoodie new` with. Or start over :)

**Comment by dirkk0** [comment]
When I started hoodie without sudo, it told me I should run it with root, so I sudoed - I guess that was the problem then. But obviously I had no other option.

Thanks for the `chown` idea: this brought me to this one:
`ERR! Error: The version of CouchDB you are using is out of date.`
which must be a problem of the somewhat outdated Ubuntu 12.0.4.

Adding the ppa with

```
sudo add-apt-repository --yes ppa:longsleep/couchdb 
sudo apt-get update
sudo apt-get install -y couchdb-bin
```

surprisingly didn't give me an newer version, but I guess I will start with a fresh installation to make sure I didn't screw it.

**Comment by janl** [comment]
Hm, Hoodie shouldn’t suggest anything to be run as sudo, it should discourage you, in fact :) Might be something in npm or ubuntu.

You need CouchDB version 1.2 or later. 1.4 or later is recommended.

**Comment by gr2m** [comment]
I'd recommend 1.5, had issues with 1.4 & user bootstrapping, just fyi

**Comment by janl** [comment]
@gr2m we added a workaround in hoodie IIRC

**Comment by dirkk0** [comment]
Ok, [installation of 1.4](https://gist.github.com/dirkk0/7764996) did work (how do I find out the couchdb-bin version btw? there seems to be no `couchdb-bin -v`or something similar) - thanks!

Now - where do I configure the ports? There is a stack.json in the data dir, but my changes therein don't seem to work?

**Comment by dirkk0** [comment]
Any hint where to configure the port?

Thanks,
  Dirk

**Comment by janl** [comment]
Ah sorry to let this linger.

You can configure the ports in `~/.ports.json` where `~` is the user that runs your hoodie :)

**Comment by dirkk0** [comment]
I see, thank you! That is a somewhat surprising place to put this info into.

Also: what happens when I want to run two hoodies on one server?

**Comment by dirkk0** [comment]
Answering my own question: ports.json holds information for each hoodie app. Still I would have preferred a config file in the application folder.

Also note to self: to be able to start it with `0.0.0.0` one needs to start the application like so:
`HOODIE_BIND_ADDRESS=0.0.0.0 hoodie start`

And it's working, thank you!

**Comment by janl** [comment]
@dirkk0 very good point. .ports.json is supposed to be a system-wide registry for ports. Hoodie merely uses it. Sorry for the confusion!

**Comment by gr2m** [comment]
Can we close this issue, maybe create follow up issues at https://github.com/hoodiehq/hoodie-server/issues?state=open if we should change the port handling?

**Comment by dirkk0** [comment]
Absolutely!

**Comment by gr2m** [comment]
thanks Dirk :)
