### ISSUE TITLE
Mechanism to prevent abuse of email feature

### ISSUE THREAD

**Issue by jviereck** [hoodiehq/hoodie#2]
Making sending emails from the client is great, but it also makes it easier for spammers to abuse the functionality. 

I don't know how this is prevented in normal business applications. Here some ideas of mine:
- add the notion of "type" for emails. when setting up the backend email server, it can be setup how to ensure this type of email is not abused. E.g. there could be some upper max limit of emails per week/month or some captcha service should be used. Also, the type of email might have a predefined template and when sending the emails the client can only fill in the missing pieces.
- the hoodie-client.js API has a way to easliy setup a captcha in a div element
- as the developer should know what the email type expects, he should know if it's necessary to solve a captcha first before sending an email or not

The idea of email-types look handy to me to have some generic mechanism to define the emails send during the welcome, confirm and password-lost process.

**Comment by gr2m** [comment]
Thanks for the input! Now I want a CAPTCHA worker ;-) For all kind of stuff

We definitely need to put in some security into the email worker. Another feature would be to force a user to confirm his account's email before he can send emails using the hoodie API.

Keep the ideas coming

**Comment by gr2m** [comment]
moved to the worker-email-out repo, as the worker will need to implement these kind of security features:
https://github.com/hoodiehq/worker-email-out/issues/1
