### ISSUE TITLE
add optional timeout before local changes get pushed

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#202]
this is a follow up for #180.
### Latest Suggestion

``` js
hoodie.store.add('doc', properties, {debounce: true})
```
### Meaning

we do not push this update to remote, until you stop making changes for a moment (with the `debounce` option).
### Question 1

Any objections about adding such an option, and removing the default timeout?
### Question 2

Is the meaning of `debounce` clear? Shall we call it differently?
related: http://underscorejs.org/#debounce

**Comment by gr2m** [comment]
I agree that `debounce` might not be familiar. But its semantic is rather complex, too.
I'd like to start implementing 1. Changing the name of the option later is simple.

**Comment by janl** [comment]
+1 for getting this going.

I also like the idea of being able to specify specific timeouts. A chat app should have zero latency for regular use, but if we also collect app metrics, they can be sent in bulk every minute. Would be nice to be able to have a timeout hierarchy:
1. Hoodie default (hardcode `0` e.g.)
2. hoodie instance default (`var hoodie = new Hoodie(url, {idleTimeout: 3000})`)
3. hoodie.store default (`hoodie.store('name, {idleTimeout: 2000})`)
4. storage operation timeout (`hoodie.store.add('type', 'id', obj, {idleTimeout:60000})`)

**Comment by gr2m** [comment]
closing in favor of https://github.com/hoodiehq/pouchdb-hoodie-api/issues/111
