### ISSUE TITLE
Make hoodieStoreApi accessible to plugin developers

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#204]
Example: https://github.com/alanshaw/hoodie-plugin-memory-store

The [hoodieStoreApi](https://github.com/hoodiehq/hoodie.js/blob/master/src/hoodie/store.js#L41) is currently not accessible from outside. Developers that want to build upon it have no chance to do so. 

This is a follow up issue for #164

**Comment by gr2m** [comment]
@svnlto @alanshaw any thoughts on how we could / should expose internal Hoodie modules to plugin developers? 

Maybe an API like `Hoodie.module("storeApi")` would return the `hoodieStoreApi` function?

**Comment by svnlto** [comment]
> `Hoodie.module("storeApi")` 

seems ok.

**Comment by alanshaw** [comment]
`Hoodie.storeApi`? Or something similar.

If you're using an IDE like WebStorm then you'd probably be able to "click through" directly to the place where it was assigned, and then to the actual function source from there, which would be useful for people actually using the hoodieStoreApi function.

**Comment by gr2m** [comment]
I see the benefit for IDE's, but I'd like to keep the amount of exposed JS methods to a minimum. Maybe there is some comment syntax you can use for WebStorm to teach it the available API returned by Hoodie.module("storeApi")?

**Comment by svnlto** [comment]
Not particularly concerned about IDE's to be honest. What are the use cases of needing to have `hoodieStoreApi` exposed ?

**Comment by gr2m** [comment]
building custom store API's in plugins, like in @alanshaw  pull request at https://github.com/hoodiehq/hoodie.js/pull/164

Alan copied the entire code of store.js & scoped_store.js into the plugin:
https://github.com/alanshaw/hoodie-plugin-memory-store

I think there is at least one other plugin that does the same

**Comment by svnlto** [comment]
just expose it as `Hoodie.module("storeApi")` then, or simply as a global: `hoodie.storeApi`.

**Comment by svnlto** [comment]
I mean this is by no means to perfect solution but for now it does the job. I'd imagine we'd refactor how we expose / export some of hoodie's functionality (plugins, modules) in the future anyways.

**Comment by ghost** [comment]
Just hit this one as well.
Can I suggest a pattern similar to abstract-leveldown from the level eco system?
https://github.com/rvagg/abstract-leveldown 
The nice thing about the approach is that you get a test harness for free as well as the ability to allow the implementer to leverage the default set of input sanitisation if that is required. 
Usually for this type of scenario the implementer mearly wants to replace the default CRUD operations provided by localstorage with something different.
It would be nice to offer hybrid/phonegap users different options.
If you think this has merit then I will put it together but it would be a substantial enough pull request as the tests will also move into this scenario so wanted to get thoughts first.

**Comment by gr2m** [comment]
@alanshaw hoodieStoreApi is accessible meanwhile, sorry I missed to update the ticket. Hoodie internal libs & utils are now passed to `Hoodie.extend`, for example

``` js
Hoodie.extend(function(hoodie, lib, utils) {
  // hoodieStoreApi can be accessed via lib.store.api
});
```

@tearmann Could you create a separate ticket, with code examples how the resulting API would look like? I'd like to close this one
