### ISSUE TITLE
unable to require('hoodie') in browserify app

### ISSUE THREAD

**Issue by svnlto** [hoodiehq/hoodie#205]

**Comment by keybits** [comment]
I'd love this to be fixed. Happy to help. Any pointers on how to approach? (nb typo in issue title: 'browerify'...)

**Comment by svnlto** [comment]
I think the path needs to be amended., require('hoodie/src/hoodie') or something like that.

**Comment by keybits** [comment]
Thanks for the quick reply! Will have a look tomorrow.

**Comment by mlouro** [comment]
Getting the same issue as described here. I can't do 

> var Hoodie = require('hoodie')

but

> var Hoodie = require('hoodie/src/hoodie')

works.

If I use _require('hoodie')_ in my app, I'm getting this when building it through browserify:

``` bash
Running "browserify:dev" (browserify) task
>> Error: module "../events" not found from "/Users/mlouro/webapps/mondo/mondo/node_modules/hoodie/dist/hoodie.js"
```

**Comment by gr2m** [comment]
@svnlto could it be that we need to leave that in for the `require('hoodie')` to work? https://github.com/hoodiehq/hoodie.js/commit/fe1c79d6d1b1041b606aad9bc1228a2c3cc5c21a#diff-0fc40edff3dda52f6336176b74618aa0L176

**Comment by svnlto** [comment]
@gr2m nope, we need to export it properly for npm.

**Comment by svnlto** [comment]
@gr2m react has the same issue. here's what they do: https://github.com/facebook/react/blob/master/npm-react/react.js

seem we need to npm publish from a different location.

**Comment by svnlto** [comment]
this is also blocking https://github.com/hoodiehq/hoodie.admin.js/issues/2

**Comment by svnlto** [comment]
@gr2m
