### ISSUE TITLE
(minor) Absolute paths in "todo" example site

### ISSUE THREAD

**Issue by cybear** [hoodiehq/hoodie#209]
The file generated.js that is, well, generated ;) in the example "todo" site has absolute paths in all its filenames: 

{"version":3,"file":"generated.js","sources":["/Users/svenlito/Sites/private/hoodie.js/src/hoodie.js","/Users/svenlito/Sites/private/hoodie.js/src/hoodie/account.js","/Users/svenlito/Sites/private/hoodie.js/src/hoodie/account_remote.js"...

This is maybe not a very serious issue, and I don't know yet how these paths are generated, but I'd assume that they can be shorter which gives slightly less footprint and also doesn't necessarily reveal the filesystem structure and username of the author :-)
I'd love to try and make a PR myself if you let me know where to look.

**Comment by svnlto** [comment]
I have yet to figure out where this file is.. can you tell me what the steps are to reproduce this?

**Comment by cybear** [comment]
Sure, on vacation now though. Will get back to you within a week.

**Comment by cybear** [comment]
1. Install Hoodie on Raspberry Pi according to this tutorial:
   http://blog.hood.ie/2013/07/hoodieberry-pi-hoodie-on-raspberry-pi-3/
   (Probably you will end up with the exact same example site on a normal machine as well, but this was the tutorial and platform I used)

So basically I think what it boils down to is 

``` bash
hoodie new berry
cd berry
HOODIE_BIND_ADDRESS=0.0.0.0 hoodie start
```
1. Open http://website:6001/ in Chrome.
2. Activate developer tools, look in the Network tab at which files are being accessed.
   One file is called data:application/json... well the whole file is a data:uri so I will only quote the start of the filename.
   But it calls itself generated.js.
3. Inspect the object. It contains data which looks a lot like json despite the filename.
   In the object, there's an attribute called "sources" which contains an array of filenames. 
   For me, the urls are prefixed by "Users/svenlito/Sites/private/hoodie.js/src/".

![image](https://f.cloud.github.com/assets/73858/1816730/6f3de7e4-6f4b-11e3-9d9a-95aa5912228a.png)

As I'm not sure how these are generated, I can't suggest the fix. But if  they are autogenerated I'd suggest they be generated as relative paths to the project root and not absolute to the filesystem root.

**Comment by svnlto** [comment]
Thanks for that detailed reply. The response you're looking at is the sourcemaps string that's being generated, not the actually code you're running.

**Comment by gr2m** [comment]
@svnlto is there anything we can do about the paths? Or do we just leave them?

**Comment by svnlto** [comment]
we just leave them as they are. AFAIK they don't really matter.

**Comment by janl** [comment]
We have a similar issue in CouchDB where the paths of the building person are hardcoded and show up in error messages, even when those paths are never used and it keeps leading to confusion. This isn’t the first time this came up, it might be the last, but if it comes up again, we should try and solve this :)

**Comment by svnlto** [comment]
Or just remove source-maps altogether. they only get added if we build in 'dev' mode anyways...

**Comment by svnlto** [comment]
https://github.com/hoodiehq/hoodie.js/commit/f49a629258f90184c7a4b66c87d34f35716d53da
