### ISSUE TITLE
auto-initialize hoodie instance

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#211]
Adding & using Hoodie in your app requires two lines of code today:

``` html
<script scr="/path/to/hoodie.js"></script>
<script>hoodie = new Hoodie();</script>
```

While I think that there are still valid use cases for that, we could offer different versions of `hoodie.js` or do stuff like `data-hoodie-url` on the script tag, or `hoodie-no-initialize`. But the default would initializing hoodie by default, so we could do

``` html
<script scr="/path/to/hoodie.js"></script>
<!-- hoodie is already available -->
```

This should cover by far most use cases and farther simplify the get started with Hoodie.

**Comment by janl** [comment]
+1

**Comment by svnlto** [comment]
yes please.

**Comment by gr2m** [comment]
auto-initialization means there won't be a `Hoodie` class any more, which will break current plugins. I'd suggest we discuss first if we shall make the frontend code provided by plugins commonJS modules, as suggested here: https://github.com/hoodiehq/hoodie-server/issues/281#issuecomment-71333443 – that'd resolve the problem.

**Comment by gr2m** [comment]
done with new Hoodie \o/
