### ISSUE TITLE
API Documentation 

### ISSUE THREAD

**Issue by martinklepsch** [hoodiehq/hoodie#212]
There are a couple of ways to do this. [Smartcomments](http://smartcomments.github.io/) were mentioned in IRC by @svnlto. 
- [x] Choose a documentation system
- [ ] Integrate it into Hoodie’s build system
- [ ] Update inline documentation (if necessary)

/cc @svnlto @espy @gr2m

**Comment by svnlto** [comment]
Thanks for getting this discussion started @mklappstuhl.

> Choose a documentation system

I'd go with YUIDocs, it has themes and supports smartcomments. it's also well established.

> Update inline documentation (if necessary)

smartcomments cli is quite useful for that.

**Comment by gr2m** [comment]
I always wanted to play with https://readthedocs.org/. Anyone have experience with it?

**Comment by janl** [comment]
We are using RTD for CouchDB and the docs team likes it. We haven’t tackled translations yet, which we will be solving soon. I’m personally not too fond of the design and I don’t know how much that can be customised.

**Comment by martinklepsch** [comment]
I visually enjoy [Backbone’s docs](http://backbonejs.org/) but I'm not sure how it's built. Thought it was docco but cant correlate the source of backbone to their docs. Also it's probably not plain “API documentation” by definition. 
**update:** Looked at YUI and compared to it I really like the sidebar in Backbone's docs to quickly explore functionality. YUI docs feel pretty heavy as well.

**Comment by martinklepsch** [comment]
@janl What don't you like about RTDs design? Looks pretty good to me at a first glance.

**Comment by janl** [comment]
@mklappstuhl dunno, feels a bit clunky, but don’t let that inform your decision :)

**Comment by martinklepsch** [comment]
Apparently RTD can render docs in many different ways:
- CouchDB: http://docs.couchdb.org/en/latest/
- Stackless: http://stackless.readthedocs.org/en/latest/
- Write The Docs: http://write-the-docs.readthedocs.org/en/latest/
- Read The Docs: http://read-the-docs.readthedocs.org/en/latest/theme.html

The last one seems to be the default theme as well.

**Comment by janl** [comment]
Excellent find. Don’t mind me then :)

Could you find out anything about documentation translations?

**Comment by ro-ka** [comment]
They mention translations in their [FAQ](https://read-the-docs.readthedocs.org/en/latest/faq.html#how-do-i-support-multiple-languages-of-documentation):

> This is something that has been long planned. In fact, we have a language string in the URLs! However, it isn’t currently modeled and supported in the code base. However, you can specify the conf.py file to use for a specific version of the documentation. So, you can create a project for each language of documentation, and do it that way. You can then CNAME different domains on your docs to them.

**Comment by martinklepsch** [comment]
I remember @felixge speaking positively about it on Twitter too: 
https://twitter.com/felixge/status/414684756794966016

This seems to be a particular nice example of documentation on RTD: 
http://salt.readthedocs.org/en/latest/

**I really like RTDs look but I wonder if it's the right tool to provide a compehensive (auto-generated) overview over hoodie's API. Looks more like a tool to provide guides and more verbose introductions.**

@janl regarding localization: http://docs.readthedocs.org/en/latest/localization.html

**Comment by janl** [comment]
So we can do `de.docs.hood.ie/hoodie/module/method`. Looks good enough to me :) cc @espy

**Comment by felixge** [comment]
@mklappstuhl RTD seems indeed targeted for User documentation, not API documentation. So if you already have a program that can generate API documentation from source, it's probably not worth tweaking it to use RTD. However, if you were to construct such a generation generator from scratch, I'd say that RTD would make a great "compilation" target.

**Comment by martinklepsch** [comment]
Any opinions on Backbone like documentation? I like it for giving a good overview and some context around API methods. With “real” API doc tools (Ruby's Yard / YUI Doc) it always feels like most is hidden away and you have to click through a lot of stuff to find whatever you're looking for.

**Comment by ro-ka** [comment]
:+1: on Backbone like docs.

**Comment by svnlto** [comment]
http://ricostacruz.com/flatdoc also seems quite nice.

**Comment by martinklepsch** [comment]
Ohh, flatdoc indeed looks pretty nice and the API Reference section looks good too.
Docs are written by hand though and not auto generated from comments in the code.

**Comment by svnlto** [comment]
> Docs are written by hand though and not auto generated from comments in the code.

Yeah, this is what I like about smartcomments, generation is really handy. Not sure if RTD has a feature like that.

**Comment by martinklepsch** [comment]
So Smartcomments are good because they are auto-generated and that makes maintainance of documentation easier. Something like Flatdoc is good because it can contain more verbose documentation/guides and makes it more accessible (mostly referring to the interface here).

Any suggestions how to get the best of both?

**Comment by janl** [comment]
RTD now officially supports translations: http://docs.readthedocs.org/en/latest/localization.html

**Comment by martinklepsch** [comment]
@janl see last line in [that comment](https://github.com/hoodiehq/hoodie.js/issues/212#issuecomment-32192089)

**Comment by janl** [comment]
@mklappstuhl _facepalm_

**Comment by martinklepsch** [comment]
:laughing:

**Comment by martinklepsch** [comment]
In case no one did that so far here's Hoodie's current README [rendered using Flatdoc](http://www.martinklepsch.org/hoodie.html).
The Readme's structure doesn't suit Flatdoc very well at the moment but splitting up code blocks could easily fix this.

**Comment by gr2m** [comment]
we discussed docs the other day and agreed to go with smartcomments & yuidocs.

**Comment by gr2m** [comment]
the stage is set for whom ever wants to turn current comments into YUIDOC style comments. Please fork of `dev` branch

**Comment by svnlto** [comment]
Ok, I've dug this up again and did some more research, I really think JSDoc Style comments is the way to go (so smartcomments is a go) , but in terms of documentation generation using YUIDocs I've always been on the fence as I seems it's bloated and a pain to customise. So I did some more digging and found https://www.npmjs.org/package/dox which I think is more suitable for our needs, esp. a tool that uses dox at it's core. 

Please have a look at https://www.npmjs.org/package/doxx, It'll take our JSDoc style comments through whatever jade template we give it which basically means we can have a fully customised docs page without adding much YUI magic at all (total win scenario here.. )

**Comment by ro-ka** [comment]
@svnlto: Sounds good.

**Comment by boennemann** [comment]
Have you looked into https://github.com/angular/dgeni yet?

**Comment by boennemann** [comment]
Closing this issue, because it is not directly related to hoodie.js. Please continue meta-discussions [here](http://github.com/hoodiehq/discussion) and ideas for the docs [here](http://github.com/hoodiehq/documentation).

**Comment by gr2m** [comment]
@svnlto Hey Sven, can you help to get the API docs setup going based on your research here: https://github.com/hoodiehq/hoodie.js/issues/212#issuecomment-35479846

You can work right on top of hodoie.js#master. We've a little little time pressure, it'd be great if you could help here. It would already be very helpful if you could get the basic setup done with `grunt` and what not, so we can all go in and add comments in the right format

**Comment by svnlto** [comment]
@gr2m will do, should have some time for this later today.

**Comment by gr2m** [comment]
thanks Sven!

**Comment by svnlto** [comment]
@gr2m do we have an idea what the new docs page should look like yet? I'd be cool If we'd have layout and styles ready so I can factor it right in while I'm at it.

**Comment by zoepage** [comment]
@svnlto  just go for the standard template. i'll fix that later, if it's okay?

**Comment by svnlto** [comment]
fair enough..

**Comment by zoepage** [comment]
@svnlto so Flatdocs it is?

**Comment by svnlto** [comment]
@zoepage https://www.npmjs.org/package/grunt-doxx

**Comment by svnlto** [comment]
implemented doxx on https://github.com/hoodiehq/hoodie.js/tree/docs
