### ISSUE TITLE
update README.md

### ISSUE THREAD

**Issue by svnlto** [hoodiehq/hoodie#213]
overall tidy up

**Comment by svnlto** [comment]
also, document `tasks`

**Comment by svnlto** [comment]
this might be one for @zoepage ?

**Comment by zoepage** [comment]
if i'll get more info, i'll take this task :)

**Comment by svnlto** [comment]
What sort of info can I get you? Hoodie tasks documentation is missing completely from the website, but I've had a look, it's in the projects readme (yay! ;) https://github.com/hoodiehq/hoodie.js#tasks

**Comment by gr2m** [comment]
I guess that's fixed via https://github.com/hoodiehq/hood.ie/pull/56? If not, please create more specific follow up issues
