### ISSUE TITLE
undefined: undefined in bootstrap signup modal

### ISSUE THREAD

**Issue by martinklepsch** [hoodiehq/hoodie#214]
I'm not sure how to reproduce this but this is what I roughly did before it happened:
1. signup 
2. create some data
3. `hoodie.store.removeAll()`
4. then trying to signup:

![screenshot 2014-01-14 18 14 58](https://f.cloud.github.com/assets/97496/1912862/77af6b2a-7d40-11e3-9a95-b79463ed3f59.png)

**Comment by gr2m** [comment]
I fixed that issue, if you create a new app, it should show you the proper error message.

Here's the change if you want to fix your current app:
https://github.com/hoodiehq/my-first-hoodie/commit/5812fca303729e2a9f9a23ceb6879b92c41d91ff

On 14 Jan 2014 at 18:25:57, Martin Klepsch (notifications@github.com) wrote:

I'm not sure how to reproduce this but this is what I roughly did before it happened:

signup
create some data
hoodie.store.removeAll()
then trying to signup:

**Comment by svnlto** [comment]
https://github.com/hoodiehq/my-first-hoodie/commit/5812fca303729e2a9f9a23ceb6879b92c41d91ff
