### ISSUE TITLE
rethink hoodie.config

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#216]
- the current `hoodie.config` API is synchronous, although it's using async hoodie.store API internally. That works today, but will break once hoodie.store is truly async
- `hoodie.config` is only used to persist the current hoodieId, username, last sequence nr (for sync) and a pending passwort reset request. All these are meant to remain local anyway, no sync is intended
- I thought `hoodie.config` would make a nice API that other developers could use, too. But to be honest, this is not based on a real use case and if that comes up, it might not be the right solution for it.

I would suggest we remove the API entirely, have a `config` module that is only accessible internally, and that implements it's own localStorage methods, so it works independently from hoodie.store, and always will be synchronous.

It would also prevent the weird problems that are happening when `_hoodieId` and `createdBy` properties from the `$hoodie/config` object diverge. 

Last but not least, the `$` prefix is now used for task object, which `$config` is not.

**Comment by svnlto** [comment]
Somewhat related to this. Currently all calls to `hoodie.store.removeAll()` will also log you out as the above config seems to be removed from the store..

**Comment by svnlto** [comment]
Can you create a dreamcode / gist for your above `config` module implementation please.

**Comment by gr2m** [comment]
1. hoodie.config API gets removed, it's only used internally
2. the API stays at is (get, set, remove, clear), synchronous
3. It doesn't use hoodie.store internally, instead accessing localStorage directly, storing an object like `_hoodie_config` or something, not following the `type/id` key convention of usual objects.
4. Even if we migrate to Pouch, we'd keep using localStorage for local config, to keep it sync
5. On signout, it needs to be cleared (I think it does that today already)

Does that all make sense? If you'd like to take it on, we can also chat

**Comment by svnlto** [comment]
I've been working on a refactor, https://github.com/hoodiehq/hoodie.js/tree/refactor/config with submit PR so we can discuss this further.

**Comment by gr2m** [comment]
fixed via #261
