### ISSUE TITLE
Add a grunt task / pre commit hook that prevents Gregor from leaving .only statements in tests

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#217]
cause he's stupid and lazy

**Comment by svnlto** [comment]
:smile: 

Good idea, pre-commit hooks are a local thing tho.

**Comment by svnlto** [comment]
as long as you push to `dev` it's all good. that way the 'only' statement won't make it into production code.

**Comment by svnlto** [comment]
Since we've decided to drop the `dev` branch, you might want to add https://www.npmjs.org/package/grunt-githooks
