### ISSUE TITLE
add grunt bump task

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#218]
if possible, also add current version to hoodie object itself. We should store that using `hoodie.config`. That way we can find out if the current version of hoodie and the version when the local store was last updated diverge and run migrations if there are any. That's a separate issue, just wanted to have that put somewhere

**Comment by gr2m** [comment]
see also https://github.com/yeoman/yeoman/wiki/Deployment

**Comment by lewiscowper** [comment]
Would using something like this:

https://github.com/vojtajina/grunt-bump

Be advisable? Or is it a case of adding something to the Gruntfile that will do what we want?

**Comment by svnlto** [comment]
@tenmilestereo It's what we are using already. But I think there are issues around it.. 

https://github.com/vojtajina/grunt-bump/issues/47

**Comment by lewiscowper** [comment]
Ah, sorry, I didn't notice that. Okay, I'll leave this for now then, I've no idea how to do it at this stage.
