### ISSUE TITLE
Allow setting of custom attributes within hoodie.account

### ISSUE THREAD

**Issue by martinklepsch** [hoodiehq/hoodie#220]

**Comment by gr2m** [comment]
Adding to that, I'd like to have two kind of attributes
- attributes that the user can change (name, birthday, etc)
- attributes that a user cannot change (plan, etc.)

For example, when a user upgrades to a payed plan, I'd store that in the user account and would like to have that information accessible via hoodie.js, so I can adjust the app accordingly

**Comment by gr2m** [comment]
closing in favor of #328
