### ISSUE TITLE
associate localstorage with hoodie instance

### ISSUE THREAD

**Issue by svnlto** [hoodiehq/hoodie#222]
when creating a new hoodie app and running it on a port that been previously used for a different app. we've run into some issues around calls to _session erroring.

**Comment by gr2m** [comment]
The solution for that would be to not use cookies at all, but store a session ID in localStorage and pass it as header in every request. But I think that CouchDB does not support that, we'd need to add the logic for that. I'd suggest to close this issue and move the discussion to https://github.com/hoodiehq/discussion

**Comment by gr2m** [comment]
This is going to be resolved with #323 which will replace cookies with a locally stored bearer token.
