### ISSUE TITLE
define dev tools (frontend/backend)

### ISSUE THREAD

**Issue by zoepage** [hoodiehq/hoodie#223]
Which dev tools are used for the front & backend?
- [ ] Grunt
- [ ] Browserify
- [ ] phantomjs
- [ ] mocha
- [ ] karma
- [ ] jshint

**Comment by svnlto** [comment]
hoodie.js:
- grunt
- browserify 
- karma / phantomjs
- jshint

hoodie-server:
- grunt
- mocha / nodeunit
- jshint

**Comment by gr2m** [comment]
Cool! let's keep a list in the issue

**Comment by svnlto** [comment]
going to close this, please reply if I'm meant to keep this open.

**Comment by zoepage** [comment]
it was? :)
