### ISSUE TITLE
change /src folder structure 

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#230]
see https://gist.github.com/gr2m/809ae8f31923139e5a0a cc @svnlto

**Comment by svnlto** [comment]
While I kind of get that you want to create visibility in terms of what sort of api's you're exposing I don't really think what you propose is for the better. I think the new layout would make things even more complicated but perhaps others ( @janl / @caolan ) could share their opinion too.

**Comment by gr2m** [comment]
Here's what I want:

As a developer who's into Hoodie, and who wants to look into the code, it should be as clear as possible where the starting points are.

The same way we want to structure docs to  have meaningfull URLS `docs/hoodie/store/findAll`, I want to make as clear as possible where the code lies e.g. for hoodie.store, and `src/hoodie/store` is as clear as I can think it, while `src/core/store/{local|remote|scoped|store}` is confusing me, it's not clear why there are 4 files and what they do. I've to look into all of them and eventually I'm going to find out. Of the 4 files in `src/core/store`, only `local` is exposed, all the others are internally used libraries, and I would make that clear by moving them to `src/lib` folder and get them out of the way of a developer looking behind the curtain for the first time.

**Comment by gr2m** [comment]
@espy / @zoepage do you have thoughts on it?

**Comment by zoepage** [comment]
i think, this is a problem atm and for me, the new structure looks way more understandable.
still like the idea of the URL structuring, like we've talked about it before.

**Comment by caolan** [comment]
At first glance the new layout looks easier for developers new to the project. Not having a clue about the internals though, I don't know if it's a good layout for core devs... so feel free to disregard my opinion on this one ;)

**Comment by janl** [comment]
what @caolan said. New looks clearer to me, and if that helps getting more people in, I’d vote for it. But I can’t comment on whether it gets in the way of anyone who actually works on the code.

**Comment by gr2m** [comment]
I changed `src/core` to `src/hoodie`, so that URLs will look like the hoodie API when we auto-generated it out of the files. I'd like to put that in so I can work on other things without having a trillion merge conflicts again. Let's chat if you've still objections @svnlto

**Comment by svnlto** [comment]
@gr2m I think you got this wrong. My main objections were not against  `src/hoodie` but rather it's layout (getting rid or folders inside `src/core` or `src/hoodie` for that matter) and introducing the `src/lib`  folder as it just adds more complexity.

**Comment by gr2m** [comment]
when new developers want to look into the code and understand how things work, the structure should guide her/him on where to look. The current structure doesn't not tell that. Moving internally used modules into `src/lib` helps to do exactly that. I disagree this adds complexity, not to new developers. It makes things simpler to understand and to get started with working on hoodie

**Comment by janl** [comment]
Heya, I talked it over with @svnlto in person. I think the bigger issue here is that this is while easy on the surface, the devil is in the details and this is hard to talk about in written communication. @gr2m happy to have a call/hangout over this some time.

Here is how I understand people’s preferences:
1. mirror the public hoodie API in code (e.g. `hoodie.account.signUp()` lives in `hoodie/account.js`)
2. the private API should still be in a logical place, but tucked away a bit as to not confuse people new to the source.

Here is a suggestion that I think works for both items:

```
src/hoodie.js // main entry point
src/hoodie/store.js // public hoodie.store api
src/hoodie/store/local.js // private hoodie.store api
src/hoodie/store/remote.js // etc
src/hoodie/store/scoped.js
src/hoodie/account.js
src/hoodie/account/remote.js
src/hoodie/config.js
src/hoodie/connection.js
src/hoodie/error.js
src/hoodie/error/object_id.js
src/hoodie/error/object_type.js
src/hoodie/events.js
src/hoodie/request.js
src/hoodie/task.js
src/hoodie/task/scoped.js
src/utils
src/utils/dispose.js
src/utils/generate_id.js
src/utils/index.js
src/utils/open.js
src/utils/promises.js
```

Public API modules are reflected in .js filenames in the same lave as they appear in the API:
- `src/hoodie/store.js`
- `src/hoodie/account.js`
- `src/hoodie/config.js`
- `src/hoodie/connection.js`
- `src/hoodie/error.js`
- `src/hoodie/events.js`
- `src/hoodie/request.js`
- `src/hoodie/task.js`

Code internal APIs are tucked away in directories of appropriate names:
- `src/hoodie/store/`
- `src/hoodie/account/`
- `src/hoodie/error/`

We are not using the CommonJS pattern `modulename/index.js` to expose the public API here.

For Utils we do use the CommonJS pattern. Utils are under `src/utils/` and grouped by file. `src/utils/indexjs` just requires all other `*.js` files, so one can do `require("utils");` to get all utils, or `require("utils/promises.js")` to just get a specific one.

I hope I got everybody’s preferences right and this makes all sense :)

**Comment by svnlto** [comment]
:thumbsup:

**Comment by gr2m** [comment]
There is another reason why I'd like to separate internal libraries from core modules: exposing internal libraries to plugin developers. This is a problem that we faced several times already.

I'd like to provide an API like this:

```
Hoodie.extend( function(hoodie, lib, utils) {})
```

passing the internal libraries as second paramter to the extend method. utils as third, unless we want to expose them in `hoodie.utils`. Separating core modules for library modules would make clear what is passed as lib, it's just and index. 

So I agree with @janl's file structure, but I want to move all files that are not exposed as `hoodie.xxxx` in the /lib folder. Happy to chat anytime until 6pm today.

If we agree that "private API should still be in a logical place, but tucked away a bit", why not put it in a separate folder? I still feel very strong about that. Also, things like `src/hoodie/events.js` is not a module representing a public API, it's an internal library. So is error.js and soon config.js. The idea of separating internal stuff by putting the min subfolders doesn't work out here.

**Comment by janl** [comment]
Ok, we are a step further here. There are two levels of abstractions that we are trying to solve with sub-folders. The one is just hierarchy of the public API (`hoodie.store.remote`) and the other is encapsulating private and public APIs.

The second one was missing from my considerations, now the lib folder makes more sense. Let’s take the lib folder as a pattern for private APIs. We can use that on the store module as well as the top level `hoodie` object:

```
src/hoodie.js
src/hoodie/store.js
src/hoodie/store/local.js
src/hoodie/store/remote.js
src/hoodie/store/scoped.js
src/hoodie/store/lib/store.js // @svnlto explained that this code currently lives in `hoodie/store.js`, that would need refactoring. E.g. private code goes here and can be `required()` by `hoodie` itself and by plugin authors.

src/hoodie/account.js
src/hoodie/account/lib/remote.js

src/hoodie/connection.js

src/hoodie/lib/config.js
src/hoodie/lib/error.js
src/hoodie/lib/error/lib/object_id.js
src/hoodie/lib/error/lib/object_type.js
src/hoodie/lib/events.js
src/hoodie/lib/request.js
src/hoodie/lib/task.js
src/hoodie/lib/task/lib/scoped.js

src/utils
src/utils/dispose.js
src/utils/generate_id.js
src/utils/index.js
src/utils/open.js
src/utils/promises.js
```

(Note that I am not actually familiar with the actual code here, so I’m all a bit hypothetical, but @svnlto is filling in some details for me)

Now that it is all written up, I see that the adding of a `lib/` directory for private APIs leads to a few unwieldy directories, it’s not too bad, but I think I can understand the allure of having a top-level `lib/` directory with a flat hierarchy now a bit better.

I think we are getting there, let’s keep talking :)

---

Ideally we could do something like the below, but @svnlto tells me that would only work in a browserify context, which we can’t expect (yet?).

``` js
Hoodie.extend( function(hoodie) {
  var private_store = require("hoodie/store/lib/store.js");
  var events = require("lib/events");
  var utils = require("hoodie/utils"); // all utils
  var promises = require("hoodie/utils/promises"); // just promises
});
```

**Comment by gr2m** [comment]
yes, we can't expect a browserify context, passing lib as parameter to the extend method makes most sense to me for plugin developers.

Your example confuses me, because there is no such thing as `hoodie.store.remote`, there is only a `hoodie.store`. And there is no such thing as `hoodie.account.remote` there is only `hoodie.remote`.

And eventually, `hoodie.store` & `hoodie.remote` will be merged into one thing, as it has a lot of duplicated behavior, see #91. 

So here is a list of public APIs, that we'll have soon

``` js
hoodie.id
hoodie.account
hoodie.store
hoodie.task
hoodie.open
hoodie.connection
```

If I wonder how these work, I look into `src/hoodie` folder and see 

```
src/hoodie.js
src/hoodie/id.js
src/hoodie/account.js
src/hoodie/store.js
src/hoodie/task.js
src/hoodie/open.js
src/hoodie/connection.js
```

That makes absolutely clear, on where to look. I care little about the rest of the files. But I want this folder to be free of anything but the logic that makes the public API. The rest could look like

```
src/hoodie/lib/error.js
src/hoodie/lib/error/object_id.js
src/hoodie/lib/error/object_type.js
src/hoodie/lib/events.js
src/hoodie/lib/store.js
src/hoodie/lib/store/local.js
src/hoodie/lib/store/scoped.js
src/hoodie/lib/store/remote.js
src/hoodie/lib/task.js
src/hoodie/lib/task/scoped.js

src/utils/config.js
src/utils/generate_id.js
src/utils/index.js
src/utils/request.js
src/utils/promises.js
```

**Comment by janl** [comment]
@gr2m I think what you describe there is what I meant, just with knowing what actually us public and private.

**Comment by svnlto** [comment]
I'd be happy to go with the following:

```
// removing the hoodie directory here because its pointless, we know it's hoodie...

src/lib/error.js
src/lib/error/object_id.js
src/lib/error/object_type.js
src/lib/events.js
src/lib/store.js
src/lib/store/local.js
src/lib/store/scoped.js
src/lib/store/remote.js
src/lib/task.js
src/lib/task/scoped.js

// seems fine.
src/utils/config.js
src/utils/generate_id.js
src/utils/index.js
src/utils/request.js
src/utils/promises.js
```

**Comment by svnlto** [comment]
the folder structure in that pull request doesn't reflect what @janl or myself have suggested. How so?

**Comment by gr2m** [comment]
I thought it does? The utils & lib folder look very similar to what you said. I only moved the core modules in the hoodie folder, that's all.

```
src/hoodie.js
src/hoodie/account.js
src/hoodie/config.js
src/hoodie/connection.js
src/hoodie/dispose.js
src/hoodie/id.js
src/hoodie/open.js
src/hoodie/remote.js
src/hoodie/store.js
src/hoodie/task.js

src/lib/error
src/lib/events.js
src/lib/store/api.js
src/lib/store/remote.js
src/lib/store/scoped.js
src/lib/task/scoped.js

src/utils/generate_id.js
src/utils/index.js
src/utils/promises.js
src/utils/request.js
```

**Comment by svnlto** [comment]
Ah ok, well fair enough then.
