### ISSUE TITLE
rename hoodie.task.cancel to hoodie.task.abort

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#233]
and `cancelledAt` to `abortedAt`. 

To follow jQuery's example, that supports `$.ajax({}).abort()`. Also prevents potential confusion with AE / BE

I'd add an abort method to all async hoodie methods, allowing to abort a pending promise.

**Comment by lewiscowper** [comment]
I'm going to have a go with this at some point soon, hopefully have a PR in by the end of next weekend.

**Comment by svnlto** [comment]
@tenmilestereo :thumbsup:
