### ISSUE TITLE
implement hoodie.account.confirm(token)

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#24]
At the moment, every new user that signs up gets automatically confirmed. To enable confirmation emails, we need a method to confirm an account with a token that gets send via email, e.g.

> to activate your account, please click the following link:  
> http://www.myapp.com/#/activate/hash123

In my App, I'd read out "hash123" and then run `hoodie.account.confirm( token )`

Question now is: how could the CouchDB Magic work?

**Comment by janl** [comment]
This will have to love in the proxy until CouchDB gains this functionality. But that is easily done. :)

**Comment by gr2m** [comment]
Here's one Idea:

When a user signes up and manual user confirmation has bin activated for the app, the users worker creates a new document in /_users, with an id looking like "confirmation/token12345" . Then the users worker will send out an email with a link that contains the token. 

We'll have a valid CouchDB user that can login with user: "confirmation/token12345" & pass: "token12345". 

That's what `hoodie.account.confirm` would do. It would update the document "confirmation/token12345" in _users with a property like `"$confirmedAt": "2013-02-02T12:40:40.767Z"`. The users worker would then listen to such an update on "confirmation/{token}" docs in _users and would confirm the respective user and remove the confirmation doc.

Makes sense? Any better idea? +@janl

**Comment by janl** [comment]
Roughly yeah, I probably would make it so that the frontend code doesn’t have to anything here and match myapp.domain/token/12345 in the proxy and set verified = true when that gets hit. Then redirect to the app proper (make it say thanks) and have the confirmation state trickle back from the server to the browser like we do with email state.

Does that make sense?

**Comment by gr2m** [comment]
I'm not sure if that will work. 

If I understand you right, `myapp.domain/token/12345` should hit the worker directly, so he can confirm the user and then redirect to the actual app. So the URL would more like like `wherethemagihappens.myapp.domain/token/12345` and that would redirect to `myapp.domain`.

Next problem is, that it's different to how it's working with email state. The email state is in the user db, and we are listening to its changes. After sign up, we cannot listen to changes to _users. What we currently do is send a sign in every second until the account got confirmed. But that only works in the current window until next page reload.

Or do I get it wrong?

**Comment by janl** [comment]
See, you have thought about this more than I have :)

**Comment by gr2m** [comment]
That's something I'd like to hack on during Offsite or the week after, because it involves all of us. We need the backend / workers, wee need the frontend code and we need pocket.

cc @caolan @espy
