### ISSUE TITLE
"Could not connect to Hoodie server at http://IP:PORT."

### ISSUE THREAD

**Issue by inator** [hoodiehq/hoodie#244]
App created using Version: 0.4.8 (node v0.10.24, npm 1.4.4, platform: linux)

Server runs error free, but when I try to log in a user from the frontend using:

```
    <body>
        <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
        <script src="http://IP:PORT/_api/_files/hoodie.js"></script>
        <script>
            var app = new Hoodie('http://IP:PORT');

            //sign out
            app.account.signOut();

            //register a new user
            if (!app.account.username) app.account.signUp('joe@example.com', 'pass');

            //sign in the new user
            app.account.signIn('joe@example.com', 'pass')
            .done(function(data){
                console.log(data);
            })
            .fail(function(data){
                console.log(data);
            });
        </script>
    </body>
```

I get:

```
message:"Could not connect to Hoodie server at http://IP:PORT."
name:"HoodieConnectionError"
url:"http://IP:PORT"
```

Here's the versions I extracted from the package file of the cached my-first-hoodie that was used for the new app build:

```
"version": "1.0.16"
"hoodie-server": "0.9.19",
"hoodie-plugin-appconfig": "~0.1.0",
"hoodie-plugin-email": "~0.1.1",
"hoodie-plugin-users": "0.1.0"
```

**Comment by inator** [comment]
Chrome reports this:
    A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true. Origin 'null' is therefore not allowed access.

**Comment by svnlto** [comment]
> Chrome reports this:
> A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true. Origin 'null' is therefore not allowed access.

You're running this from a different port other then the one hoodie starts at right?

**Comment by inator** [comment]
@svnlto - I’m running in the typical app to remote backend scenario, hitting the remote server www port directly as allocated.  It has worked on early versions of Hoodie, but no longer.  The Playground app runs fine from the server, so all signs are on a cross-site problem.  Has the implementation of CORS in hoodie-server changed by chance?  I’ve been picking through commits but haven’t uncovered anything.

**Comment by inator** [comment]
@svnlto (& @gr2m)  It still seems to be a CORS issue with the new Hapi server approach.  I did some research and experimentation and here's what now allows for the cross site requests.

In hoodie-server/lib/server/index.js:

```
pack.server(server_config.www_port, {
  labels: ['web'],
  cors: {
    origin: ['null'],
    credentials: true
  }
});
```

I'm not real sure what the implications would be across implementation scenarios, but I'll leave it in your capable hands to evaluate that.

Now being able to log in successfully, I am getting some 404's from a changes long poll that is established immediately following new Hoodie instance (please note... the referenced user hash is not my signed in user).  A clear of local storage and cache yields no different result.

```
"NetworkError: 404 Not Found - http://ip:port/_api/user%2Fylivdux/_changes?include_docs=true&since=0&heartbeat=10000&feed=longpoll"
{"error":"not_found","reason":"no_db_file"}
```

The corresponding logged entry on the server is

```
Error getting update from changes pool
{ [Error: not_found
no_db_file]
  error: 'not_found',
  reason: 'no_db_file',
  response: 
...
```

I'm not entirely sure it's related, so I'll happily open a new issue for it if you see fit.

**Comment by svnlto** [comment]
Can we start discussing one problem per gh issue please? :)

**Comment by inator** [comment]
Sure. I'll open a new issue. Wasn't sure if it was related.

**Comment by inator** [comment]
@sven - Sorry for any confusion I've caused with the wide-scoped discussion. Should I open a new issue under the hoodie-server repo for the CORS problem?

**Comment by svnlto** [comment]
@inator I think what you're experiencing is similar to https://github.com/hoodiehq/hoodie-server/issues/214 which only happens if you try to access hoodie-server from a port other then the specified one.

**Comment by inator** [comment]
My issue is cross site, not cross port, but caused by the same thing described there.  Thanks very much for the follow up. I'll pitch in what I can there.  Much appreciated!

**Comment by svnlto** [comment]
> My issue is cross site, not cross port

Yeah, that counts as CORS request, hence the error.
