### ISSUE TITLE
Out of sync docs

### ISSUE THREAD

**Issue by jzaefferer** [hoodiehq/hoodie#249]
The docs in the README.md here in the repo seem quite out of sync with the docs on hood.ie. The details on [background workers ("tasks")](https://github.com/hoodiehq/hoodie.js/blob/master/README.md#tasks) where [added six months ago](2ddfd0419c5910670aa1ed42baa501e985dd2e73), but don't show up on [hood.ie](http://hood.ie/#docs) at all.

In general I can't tell if the documentation on the site is preferable over the README, or the other way round. A canonical source for docs would be great.

**Comment by gr2m** [comment]
fixed via cf5c682aaa130ea37d04b7f2de4769c202142596

**Comment by jzaefferer** [comment]
The commit link is a 404 - is that in a different repo?

**Comment by gr2m** [comment]
I'm sorry, here's the correct link: https://github.com/hoodiehq/hood.ie/commit/cf5c682aaa130ea37d04b7f2de4769c202142596
