### ISSUE TITLE
Abstract about hoodie's authentication and authorisation implementation

### ISSUE THREAD

**Issue by jzaefferer** [hoodiehq/hoodie#250]
I'd like to know more about how hoodie handle's authentication and authorisation. So far the only thing I found is this warning in the docs:

> Important: Hoodie will only sync data to the database if it belongs to a user! So you need to sign up/sign in a user using the methods above before the hoodie.store methods below will actually sync anything. If you don't have a user, hoodie.store will read/write using local browser storage only.

I would like to know more about how this is implemented, without having to the full source code to figure this out myself. Even if I read the source myself in the end, an overview would be a great help to get started in understanding the implementation.

I suspect anyone considering hoodie for a production app would eventually want to have that information available, but personally I'd be happy with a gist or blog post that has some details.

**Comment by gr2m** [comment]
good point, we should improve docs on that.

Hoodie stores all date locally, it gets cached in your browser and therefore works even when you're offline or without an account. As soon as you sign up, your local store gets synchronized to your remote store, each user account has a separate one, and each user can only access data belonging to her/him.

Makes sense?

**Comment by jzaefferer** [comment]
> As soon as you sign up, your local store gets synchronized to your remote store, each user account has a separate one, and each user can only access data belonging to her/him.

This is the part I could figure out from the docs myself, and I would like to know how this is actually implemented. What happens to the password the users enters? How is he kept logged in? How does the server identify the user?

Somewhat related, is there anything preventing the user from storing arbitrary data in the database, e.g. opening the console and calling `hoodie.store.add`?

**Comment by gr2m** [comment]
> Somewhat related, is there anything preventing the user from storing arbitrary data in the database, e.g. opening the console and calling `hoodie.store.add`

No. It's just the API. User's could just go ahead and run it in the console the same way they could POST random data to a RESTful API. Preventing abuse of the API is happening on the backend side.

**Comment by jzaefferer** [comment]
I never got an actual answer to my main question:

> I would like to know how this is actually implemented. What happens to the password the users enters? How is he kept logged in? How does the server identify the user?

Was this documented somewhere?
