### ISSUE TITLE
Catch rename to self

### ISSUE THREAD

**Issue by janl** [hoodiehq/hoodie#251]
Issue description here: https://github.com/hoodiehq/hoodie-plugin-users/pull/18

**Comment by gr2m** [comment]
Good point. `hoodie.account.changeUsername(currentPassword, newUsername)` should reject if `newUsername === hoodie.account.username`

**Comment by lewiscowper** [comment]
I'm having a crack at this one too. Just need to sort the error message, but it should work soon.
