### ISSUE TITLE
.remove(type, id) doesn't work.

### ISSUE THREAD

**Issue by 01AutoMonkey** [hoodiehq/hoodie#258]
Delete node, it's gone, refresh, it's still gone, refresh, it's back!

Tests show that when this happens it usually happens on the third refresh, not the first and not the fourth.

They also show that once it's back, deleting it again will result in the same bug, but this time, or after a one or more iterations, when it comes back it's reverted to it's first _rev, so any attributes that had been changed are now gone, e.x. updatedAt, _except_ for _syncedAt, which has an updated value.

I also notice that if I go into futon and delete these nodes/documents there, I need to hit delete 2 or 3 times before it works.

What could be causing this?

Hoodie 0.4.8
Couchdb 1.5.0
Chromium 33.0.1750.146 (254388)
Arch Linux

Relevant code:
## Get

``` js
var nodes;
hoodie.store.findAll("node").done(function (objects) {
    console.log(objects)
    nodes = objects;
    /*nodes = [{id: "athif1", kind: "purpose", title: "Having Fun Doing Awesome Shit", description: "", on: false, length: [0,0,0], linksTo:[]},
             {id: "ewfsdf3", kind: "milestone", title: "Eternity", description: "", on: false, length: [0,0,0], linksTo:["athif1"]},
             {id: "sdfsd", kind: "task", title: "New data structure", description: "", on: false, length: [0,0,0], linksTo:["ewfsdf3"]},
            ];*/
    initialize();
    updateRadius();
    updateNodes();
});
```
## Create

``` js
  var attrs = {kind: "task", title: "New Node", description: "", on: false, length: [0,0,0], linksTo:[]};
  attrs.x = point[0];
  attrs.y = point[1];
  hoodie.store.add("node", attrs).done(function (node) {
    console.log("Added to database..")
    nodes.push(node);
    updateRadius();
    updateNodes();
  });
```
## Update

``` js
  var type = d.type;
  var id = d.id;
  var update = jQuery.extend({}, d);
  var keysToIgnore = ["createdAt", "createdBy", "id", "type", "updatedAt", "_rev", "_syncedAt"];
  for (key in keysToIgnore) {
    delete update[keysToIgnore[key]]
  }
  console.log(update);
  hoodie.store.update(type, id, update)
    .done(function (updatedObject) {
      console.log("Node updated in database..")
    });
```
## Remove

``` js
    var type = selected_node.type;
    var id = selected_node.id;
    hoodie.store.remove(type, id)
      .done(function (removedObject) {
        console.log("Removed from database..")
      });
    nodes.splice(nodes.indexOf(selected_node), 1);
```

**Comment by gr2m** [comment]
Hey @mrbellyrumble, thanks a lot for taking the time to reporting the bug with all the details, much appreciated! 

Any chance you can put up the entire code somewhere? Or can you reproduce the problem with https://github.com/hoodiehq/my-first-hoodie?

**Comment by gr2m** [comment]
closing, can't reproduce, maybe it has been fixed meanwhile. Please reopen and add code that we can use to reproduce the bug
