### ISSUE TITLE
TypeError: _ref is null when a document is created directly within CouchDB

### ISSUE THREAD

**Issue by inator** [hoodiehq/hoodie#259]
If a document is created directly within CouchDB without the type/id convention, the error is thrown.

See https://github.com/inator/hoodie-plugin-social/issues/2#issuecomment-36957023 for more details.

**Comment by gr2m** [comment]
Can you elaborate on the use case(s), why you'd manually add objects to a user database?

One way to solve this would be to prevent objects that do not follow a certain format from being stored into user databases in the first place. But I'ld like to your your use cases first

**Comment by inator** [comment]
@gr2m  -  I can't imagine a use case personally, but I do have a user (Appback) that has requested direct access to CouchDB to do some bulk additions.

I raised it only because it's possible to break the default behavior of Hoodie on the frontend, since the error seems to kill polling.  Short of adding some sort of validation doc to prevent an addition that does not adhere, perhaps the only approach would be to detect a non-conventional doc id and pass on it from a Hoodie "changes" perspective.  I tend to favor the later, as I think it allows the best flexibility for those who are inclined to dabble on the admin side of CouchDB.

**Comment by gr2m** [comment]
I agree that we could simply ignore changes coming from remote that do not match the required format by Hoodie. What you need to do is look into `handlePullResults` & `parseFromRemote`. Add a test after this line 

``` js
matches = id.match(/([^\/]+)\/(.*)/);
```

To make sure there are matches at all. If not, ignore the object.

Does that help? Wanna send a pull request? Please add a test for it, too. You can extend `test/fixtures/changes_response` with one object that doesn't match the `<type>/<id>` convention. Let me know if you need help with it!

**Comment by inator** [comment]
Will do.  Quick questions on the tests.  Is it just a mater of adding another doc object to the results array (one that does not conform)?  If so, should I just add the next “seq” number to that object?

**Comment by gr2m** [comment]
yeah, just add something like 

``` js
{
  seq     : 6,
  id      : 'bogus',
  changes : [{'rev': '1-123'}],
  doc     : {'_id': 'bogus', '_rev': '1-123', 'foo': 'bar'}
}
```

in `changes_response.js`
