### ISSUE TITLE
replace events with backbone events

### ISSUE THREAD

**Issue by svnlto** [hoodiehq/hoodie#266]
https://github.com/madebymany/eventable/blob/master/eventable.js

**Comment by gr2m** [comment]
I don't mind using it as long as it has the same footprint and we don't add underscore as dependency

**Comment by svnlto** [comment]
cool, we can remove the underscore dependency, it's only used in a couple of places as far as i can see.

**Comment by hendrikcech** [comment]
I think this is what you are looking for: https://www.npmjs.org/package/backbone-events-standalone

**Comment by svnlto** [comment]
yes! :clap:

**Comment by boennemann** [comment]
This is outdated as we want to use `EventEmitter` now, right?
Please update and (re)open accordingly.

**Comment by svnlto** [comment]
> This is outdated as we want to use EventEmitter now, right?

yup.
