### ISSUE TITLE
lastActiveAt timestamps for users

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#27]
we want to have a lastActiveAt timestamp for users. 

Current idea would be to update my _users doc each minute with a new lastActiveAt timestamp.

That would produce tons of revisions in the _users docs, not sure if that's feasible

**Comment by espy** [comment]
Wouldn't it be easier to have Hoodie write the current timestamp to the user object whenever there's an authenticated action by that user? After all, it is called last **Active** At. That would take care of the rough timing, if anything more precise is needed, the dev can update the value programmatically as needed, for example when the tab is closed. Can devs actually write additional data to a user object right now?

I think the main use case is analytics, just to see who is active at all, not to track everyone by the second.

**Comment by gr2m** [comment]
Problem is that there can be a lot of requests. Take minutes.io as example. Each time you stop typing for 2s, it will send 2 requests, push & pull. 

I think we could add some magic in hoodie world with some alternative store that is more suited for logging. But this is a non issue at the moment, so I'll close it for now
