### ISSUE TITLE
signIn as a user that has an error gets rejected but also ends session of currently singed in user

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#273]
In that case we reject the sign in, but towards the backend we still get
a new session, and the old one gets removed. That leads to a state like
a session timeout: I'm still signed in with the old username, but not
authorised anymore. A better approach might be to send an extra 
GET /_users/<user-doc-id> with HTTP basic auth to see if the user account
is valid and only if it is, we'd send the POST /_session request.

Besides user's having an error, the user account might also be pending (not yet confirmed). That case would be also handled with the approach described above.

The problem I see with this approach is that it's rather an edge case but would add an extra request to every `hoodie.account.signIn()`

**Comment by gr2m** [comment]
I just tested it and it works. But it requires a change in the CouchDB config.

`httpd.authentication_handlers` is per default set to:

```
{couch_httpd_oauth, oauth_authentication_handler},
{couch_httpd_auth, cookie_authentication_handler},
{couch_httpd_auth, default_authentication_handler}
```

but to make this work, we need this order, so that `BASIC AUTH` is used before a cookie authorisation.

```
{couch_httpd_oauth, oauth_authentication_handler},
{couch_httpd_auth, default_authentication_handler},
{couch_httpd_auth, cookie_authentication_handler}
```

That will also be needed for password-protected, shared databases and I think I made a ticket for it somewhere, I think I even opened a ticket on CouchDB. I don't see a reason why `httpd.authentication_handlers` this shouldn't be set that way per default.

@janl do you see any problem with changing the default CouchDB setting here for Hoodie?

**Comment by janl** [comment]
Nope, changing this is fine. We should automate that in hoodie-server.

Not sure about PW-protected DBs though. That should be done with roles.

**Comment by gr2m** [comment]
> Not sure about PW-protected DBs though. That should be done with roles.

roles don't work for visitors without an account.

**Comment by janl** [comment]
Got it.
