### ISSUE TITLE
Public data via plugins

### ISSUE THREAD

**Issue by aaronmoodie** [hoodiehq/hoodie#275]
@gr2m Just following up regarding the discussion we had late last year https://github.com/hoodiehq/hoodie.js/issues/121

I just went to look at those examples, and they're no longer there. Any chance you would be able to post them again? Is this still the best way to achieve a 'public' post? 

thanks, 
Aaron

**Comment by janl** [comment]
See https://github.com/hoodiehq/hoodie-plugin-global-share :)

**Comment by aaronmoodie** [comment]
ah, awesome thanks @janl !
