### ISSUE TITLE
feature request: connect to a remote couch?

### ISSUE THREAD

**Issue by hems** [hoodiehq/hoodie#277]
Let's say i'm developing an app with another developer at the same time on the same network.

How can our hoodies point to the same couchdb instance, for instance everyone connects to my local couch.

Or for instance, we setup a hoodie server at an online server and then everyone runs the code locally connecting to the online couch?

Sorry if this already exists / is documented somehwere, but I couldn't find this information.

**Comment by gr2m** [comment]
yes, that's already possible. For example, if your hoodie app runs at https://myhoodieapp.com, you simply do

``` js
var hoodie = new Hoodie('https://myhoodieapp.com')
```

It will communicate to the remote Hoodie instance at `https://myhoodieapp.com/_api`, instead of connecting to the local one at `/_api`

Does that help?

**Comment by hems** [comment]
That helps. 

Is there a way to run the server locally and just connect to my online couch ?

**Comment by gr2m** [comment]
If you connect to your online Hoodie (it must be Hoodie Server, it won't work with direct access to a couch), you can run a static server of your choice locally, doesn't matter. Appache works, or if you're on a mac, just run `python -m SimpleHTTPServer` in the terminal to start a server for the current folder

**Comment by hems** [comment]
Cool, i understood that.

My goal was to make it as simple as possible, by just pointing hoodie to an online couch ( in my case, cloudant ) this way i wouldn't need to install hoodie on online linux box just in order to use a remote couch.

**Comment by gr2m** [comment]
yeah that's right, if you're using a remote Hoodie instance, you don't need to install it locally. All you need is a static server. That's the beauty of Hoodie :)

**Comment by hems** [comment]
As i said, my feature request is a local hoodie instance to connect to a remote couch instance.

I don't believe this is exactly sorted by installing hoodie on a box online.

**Comment by hems** [comment]
I do agree i would achieve the "same result", but still i would need to install couch and hoodie online VS just having a couchdb hosted by an online service ( therefore eliminating my need to keep my box always alive )

**Comment by gr2m** [comment]
Oh gotcha, sorry, misunderstood. Yes, you can connect your local hoodie server to a remote couch. You have to create an admin user and then set these ENV variables, something like that should work

```
$ COUCH_URL= <URL TO YOUR REMOTE COUCH> HOODIE_ADMIN_USER=admin HOODIE_ADMIN_PASS= <yourpassword> hoodie start
```

**Comment by janl** [comment]
Hoodie is currently not compatible with Cloudant as they are on an older version of the CouchDB API. We need at least 1.2.0 (latest is 1.5.1), they are on 1.0.1 or 1.1.0, IIRC. — I know they are working on getting towards API parity, but as it stands, it’d require some more work to get this going.

What OS are you on, @hems?

**Comment by hems** [comment]
i have osx locally, linux online ( which i would like to avoid installing hoodie / couch as it might be restarted at any time, as it is a testing machine )

Which online couchdb service would be recommended then? 

I would love to have a central db so then all developers would always be "up to date" and all developers would be "slave" to that DB, instead of having one "master" that can't be shut down ( in this case the master would be the online couch server )

**Comment by janl** [comment]
How about installing CouchDB’s locally and using continuous replication through Cloudant to keep devs in sync?

The only alternative at this point is IrisCouch, or custom hosting. If you are interested in custom CouchDB hosting, I might be able to help, but best to discuss in email: jan@apache.org :)

**Comment by hems** [comment]
cool janl! 

thanks a lot!

I already have an account on iris couch ( from previous plays with couch ) !

Will give a shot on the environment variables ( as suggested by gr2m ) and let you know how things are going ( :

thanks a lot guys!

:8ball:
