### ISSUE TITLE
hoodie.store.remove not deleting data

### ISSUE THREAD

**Issue by redgeoff** [hoodiehq/hoodie#283]
I'd like to start by saying that hoodie rocks and you guys are awesome!

Unless I have missed a detail somewhere, after executing the following code and waiting 5 seconds, there should be no new items in local storage or in couchdb. In other words, the hoodie.store.remove call doesn't appear to be working.

``` html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
    <script src="/_api/_files/hoodie.js"></script>
    <script>

      var hoodie  = new Hoodie();

      function afterSignUp() {
        hoodie.account.signIn('delete@example.com', 'secret').then(function() {
          console.log('adding...');
          hoodie.store.add('todo', {txt: 'clean dishes'}).then(function(item) {
            setTimeout(function() {
              console.log('removing... ' + item.id);
              hoodie.store.remove('todo', item.id);
            }, 5000);
          });
        });
      }

      hoodie.account.signUp('delete@example.com', 'secret').then(afterSignUp, afterSignUp);

    </script>
  </body>
</html>
```

If I get some extra time, I'll try to clone the repos and isolate the bug, but it may take me a while and I'm not sure if the bug is in the client or server side code or both.

**Comment by redgeoff** [comment]
Upon further inspection it looks like the _deleted attribute is being set to true and a call is being made to _bulk_docs, however the data is not being deleted from couchdb. I suspect that the problem is probably in the server code.

**Comment by gr2m** [comment]
looking into it. Btw, you don't need to signIn after you signUp. That happens automatically for you.

**Comment by gr2m** [comment]
confirmed, there is a bug. I've tested it also with latest hoodie.js. This is caused by conflicts on the server, but it's a hoodie.js problem. It sends multiple `POST _bulk_docs` requests with the same object but with different `_rev` IDs. I unfortunately have no time to look into it right now, but if you can find hoodie sends multiple `POST _bulk_docs` requests, you like find the reason for this. There really should be only two requests (one for creating, one for deleting), but I see at least 3

**Comment by redgeoff** [comment]
You're right, I focussed on just the `hoodie.store.add` call and it is in fact resulting in two calls to `_bulk_docs`. It looks like the intention was for the first call to `_bulk_docs` to send the data to the server, then a call to `_changes` would be made to retrieve the new id and clear the item from the dirty items list before any subsequent calls to `_bulk_docs`. Instead, it looks like there is a race condition and two calls to `_bulk_docs` are occurring before the call to `_changes`.

Here's what I am wondering: I've seen mention of using pouchdb as the underlying data synchronization layer for hoodie and I think this is a great idea. How is this effort coming along? In other words, is it worth it to spend a bunch of time trying to figure out where these syncing bugs are in the `_bulk_docs` and `_changes` code or should the effort really be spent in adapting hoodie to use pouchdb?

**Comment by gr2m** [comment]
I think it's worth looking into it, maybe the effort to fix this problem is not very complicated once we found its cause. We did not started to work on migriting Hoodie on PouchDB, we still need to finish up a few things beforehand like merging the `hoodie.store` and `hoodie.remote` API. So this will take some time

**Comment by redgeoff** [comment]
@gr2m, I'm trying to debug this and need to setup a dev env with the latest code. I've cloned [hoodie.js](https://github.com/hoodiehq/hoodie.js) and [hoodie-server](https://github.com/hoodiehq/hoodie-server) and tried to follow the [quickstart_for_developers](https://github.com/hoodiehq/hoodie.js/blob/master/quickstart_for_developers.md), but I still don't fully understand the setup env. Is there a more detailed guide?

**Comment by gr2m** [comment]
@redgeoff happy to pair on it this week to help you with the setup. I'm in Berlin timezone, just ping me on IRC or [twitter](https://twitter.com/gr2m)

**Comment by redgeoff** [comment]
I've been looking further into this and it appears that the problem has something to do with `remote.connect` being called multiple times by the above code, which I think is then generating multiple conflicting calls to `_bulk_docs`. There still appears to be a bug and I'm going to continue debugging it, but it looks like it can be sidestepped by only executing code after a successful return of `hoodie.account.authenticate` as referenced in https://github.com/hoodiehq/hoodie.js/issues/292.

**Comment by redgeoff** [comment]
I think I've found the problem. As I suspected, the 3 calls to `remote.connect` are causing a race condition which results in 3 calls to `_bulk_docs` before a response is received. (This is hard to debug as breakpoints can easily change the timing and prevent the race condition). The easiest solution I can think of is to modify _lib/store/remote.js_ and insert a new `connecting` state:

``` javascript
  var connecting = false; // PROPOSED CHANGE

  // start syncing. `remote.bootstrap()` will automatically start
  // pulling when `remote.connected` remains true.
  //
  remote.connect = function connect(name) {

    // PROPOSED CHANGE - BEGIN
    if (connecting) {
      return remote.bootstrap();
    }
    connecting = true;
    // PROPOSED CHANGE - END

    if (name) {
      remoteName = name;
    }
    remote.connected = true;
    remote.trigger('connect');
    return remote.bootstrap().then(function() {
      remote.push();
    });
  };
```

And then in `remote.push` (in the same file):

``` javascript
    pushRequest.done(function() {
      connecting = false; // PROPOSED CHANGE
      for (var i = 0; i < objects.length; i++) {
        delete objects[i]._revisions;
        remote.trigger('push', objects[i]);
      }
    });
```

@gr2m if you like this solution then I'd be happy to submit a pull request--I just wanted to check with you first to make sure that this fits with your architecture.

**Comment by gr2m** [comment]
Thanks Geoff, excellent catch! I'm looking into it now

**Comment by gr2m** [comment]
@redgeoff As simple way to fix it would be to simply add

``` js
if (remote.connected) {
  return resolve();
}
```

The proper way to fix it would be to return the pending promise, without re-executing the bootstrap & push, like so

``` js
var connectDefer;

remote.connect = function connect(name) {

  if (name) {
    remoteName = name;
  }

  if (remote.connected) {
    return connectDefer.promise();
  }

  connectDefer = defer();
  remote.connected = true;
  remote.trigger('connect');
  remote.bootstrap().then(function() {
    remote.push();
  }).then( connectDefer.resolve, connectDefer.reject);

  return connectDefer.promise();
};
```

What you think? Wanna pair on it? Would have the benefit to also chat a bit :) Find me on IRC or ping me [on Twitter](https://twitter.com/gr2m) if you like. I'm in Berlin timezone

**Comment by redgeoff** [comment]
@gr2m your solution works great, the only question I have is whether the

``` javascript
if (name) {
  remoteName = name;
}
```

should be moved until after

``` javascript
if (remote.connected) {
  return connectDefer.promise();
}
```

**Comment by gr2m** [comment]
Hmm. First I thought to keep it above. That way `connect("new-remote")` could be used to change the remote. But I just wonder if it makes sense to change the remote at all. So put it below, I'll create another issue for this.

**Comment by redgeoff** [comment]
Did you want me to create a pull request? I will if you want... I just don't want to take credit for your code.

**Comment by gr2m** [comment]
:) please do 

On 14 May 2014 at 22:04:40, Geoff Cox (notifications@github.com) wrote:

Did you want me to create a pull request? I will if you want... I just don't want to take credit for your code.

**Comment by gr2m** [comment]
This has been resolved in latest master.

@redgeoff just fyi: you don't need to call `hoodie.account.signIn` after `hoodie.account.signUp`, you're signed in already.
