### ISSUE TITLE
admin password not working

### ISSUE THREAD

**Issue by ramstein74** [hoodiehq/hoodie#285]
hello
i created an app in windows 7, and set admin password to admin 
when i try to log to admin panel port 6005 it does not accept my "admin" password.

Why?

I created 5 apps using hoodie new appx
i dont remember the admin for the first app. 
does it matter ? every hoodie app has its own admin pass right?

thank you

**Comment by boennemann** [comment]
I think I have the same problem running Version: 0.4.9 (node v0.10.26, npm 1.4.3, platform: darwin).

Both the app and the couch are working, but Pocket rejects the admin password. Having a look at the console reveals that it simply can't connect to the API.

I reinstalled hoodie, created a new app, cleared cookies, localStorage, npm and hoodie caches and logged into Futon.

![screen shot 2014-04-27 at 18 15 43](https://cloud.githubusercontent.com/assets/908178/2811609/997e08e6-ce27-11e3-8141-7ef3f20eb5c7.png)

![screen shot 2014-04-27 at 18 19 30](https://cloud.githubusercontent.com/assets/908178/2811610/c6aa92ee-ce27-11e3-921d-7928f57640e8.png)

**Comment by boennemann** [comment]
Seems like the newest versions of hoodie-server are broken. Once I changed the version from 0.9.21 back to 0.9.19 (copied from the last working demo I saw: https://github.com/zoepage/codequiz/blob/master/package.json#L10) it works again.

**Comment by gr2m** [comment]
> I created 5 apps using hoodie new appx
> i dont remember the admin for the first app. 
> does it matter ? every hoodie app has its own admin pass right?

You can change the admin password directly in `path/to/app/data/couch.ini`. Just set `admin = yourpassword` in the `[admins]` section and restart the server. CouchDB will encrypt the password automatically

@boennemann it might be a problem with local-tld, I see that you use the `admin.` subdomain. Do you see the same error when directly trying to access `localhost:<admin port number>`?

**Comment by boennemann** [comment]
@gr2m At first I didn't even use local-tld, so yes.

**Comment by ramstein74** [comment]
i tried setting my password in couch.ini

[couchdb]
database_dir = C:\Users\Antonio\h8\data
view_index_dir = C:\Users\Antonio\h8\data
uri_file = C:\Users\Antonio\h8\data\couch.uri
uuid = a9e1cf3d410feb0add19ea497219de30

[httpd]
port = 6006
authentication_handlers = {couch_httpd_oauth,
oauth_authentication_handler},{couch_httpd_auth,
default_authentication_handler},{couch_httpd_auth,
cookie_authentication_handler}

[log]
file = C:\Users\Antonio\h8\data\couch.log

[couch_httpd_auth]
timeout = 172800

[admins]
_hoodie =
-pbkdf2-541efe7eada72627f6b48415e6f85a689bb7a145,a7d54baebd3dd4ed5b614b5f6082f234,10
admin = abcd123

Restarting hoodie , it still does not accept my abcd123 password

2014-04-29 12:32 GMT+01:00 Stephan Bönnemann notifications@github.com:

**Comment by ramstein74** [comment]
i see errors in chrome console
[image: Imagem inline 1]

2014-04-29 14:20 GMT+01:00 António Ramos ramstein74@gmail.com:

**Comment by svnlto** [comment]
try running `hoodie reset password` and then restart your app.

**Comment by ramstein74** [comment]
nope,wrong password again...
Still errors in the console before i write the password. Is that normal???
[image: Imagem inline 1]

2014-04-29 14:37 GMT+01:00 Sven Lito notifications@github.com:

**Comment by gr2m** [comment]
I was just able to reproduce the problem, I can't fix the problem as I'm not the backend guy, but I try to find someone. If you have some backend knowledge, please feel free to raise your hand and look into it, I'm happy to try helping as good as I can

**Comment by boennemann** [comment]
Thanks @gr2m, should me move this over to https://github.com/hoodiehq/hoodie-server then?

**Comment by gr2m** [comment]
good idea! @caolan suspects it to be a problem with the proxy setup, as we  just migrated from the nodejitsu http proxy to hapi.js

**Comment by gr2m** [comment]
fyi

```
[21:52:43]  <svnlto>     caolanm: i think i found the culprit https://github.com/hoodiehq/hoodie-server/commit/5302b47c9ae546911b7151838cebaa8dda0b6e2f#diff-e09bca3f48fed5aa8460eb81b1612dc8R45 /cc gr2m
```

**Comment by gr2m** [comment]
closing in favor of https://github.com/hoodiehq/hoodie-server/issues/269

**Comment by jammy-git** [comment]
No idea what is causing the problem, but I'm experiencing the same issue. Hoodie version 0.6.3
