### ISSUE TITLE
CORS not working for dev environment

### ISSUE THREAD

**Issue by boennemann** [hoodiehq/hoodie#286]
What the documentation says:

> You also have the option of defining the Hoodie API endpoint yourself, too. This is useful if you're using a dev environment that runs its own server, like yeoman.io. You'd have Grunt running your frontend at http://localhost:9000, and your Hoodie instance at http://localhost:6007.

What Chrome says:

> XMLHttpRequest cannot load http://127.0.0.1:6005/_api/_session. A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true. Origin 'http://127.0.0.1:9000' is therefore not allowed access.

With `open -a Google\ Chrome --args --disable-web-security` it works though.

**Comment by svnlto** [comment]
You'd have to use a proxy. See: https://github.com/hoodiehq/snug/blob/master/Gruntfile.js#L56

**Comment by boennemann** [comment]
Thanks, I hope that will work.

There a ton of undocumented tricks you need to know to get hoodie running. Especially because the knowledge is spread among so many repositories. Please let me me know if I can help there in any way.

**Comment by paidon** [comment]
I am still not able to get it working.
Could anyone provide a "newbie" guide please?

This is my setup:
- hoodie running on EC2 instance
- js app running on my local machine

Thank You!

**Comment by gr2m** [comment]
hey @paidon, this depends on #323. Once merged, it should work out-of-the-box

**Comment by paidon** [comment]
hi gr2m,

thank you. Do you know when this is going to happen? In the mean time, I will work on my local machine :-)

Thanks!

**Comment by gr2m** [comment]
@paidon unfortunately we cannot commit to any shipping dates for features, unless someone is willing to sponsor their implementation. It's not a top priority at the moment, so it might take some time, I'm afraid

**Comment by paidon** [comment]
no worries, thanks a lot!
