### ISSUE TITLE
live updates in all clients when one client updates

### ISSUE THREAD

**Issue by ramstein74** [hoodiehq/hoodie#287]
hello i have one user logged in 2 browsers.
I use the sample app .
he adds a record
The page he is in , updates ok. but the same page in the other browser does not, unless he refreshes it.

is the code hoodie.store.on('add', function (newObject) {});

suited to live update all browser instances or just the page where the update was made?
If not, how do i do it?

Regards
Antóino

**Comment by gr2m** [comment]
Hey Antóino, the code `hoodie.store.on('add', function (newObject) {})` looks correct. I'll look into it tomorrow

**Comment by boennemann** [comment]
Hello @ramstein74,

the code `hoodie.store.on('add', function (newObject) {});` is suited to do live updates.
Please report back if the problem still exists.

Best Stephan
