### ISSUE TITLE
Plugins API broken between 0.8.0 and 0.8.1

### ISSUE THREAD

**Issue by varunnaik** [hoodiehq/hoodie#291]
Plugins do not seem to return success or failure to the browser as of 0.8.1.

``` javascript
hoodie.task.success(originDb, object, handleError);
```

does not seem to work anymore both for success and errors.

The plugin handler in my worker.js runs fine, but the call to hoodie.task.success does not seem to have any effect.

I have checked and found that 0.8.0 works fine, but not 0.8.1.

cc @peetersn @gr2m

**Comment by gr2m** [comment]
cc @caolan—
Gregor Martynus

**Comment by lupomontero** [comment]
Im experiencing similar behaviour here. I can mark tasks as `success` or `error` in worker (using `hoodie.task.success()` and `hoodie.task.error()`). On success, tasks get deleted from the database as expected, but in the front-end, the task object doesn't get cleared from localStorage and `success` and `error` events are not fired (nor promise callbacks). The only task event that seems to be fired in the front end is `start`.

**Comment by laurens** [comment]
I am having the exact same problem as @lupomontero 
Odd thing is, the events do get fired when I create a task while I am not logged in.

**Comment by varunnaik** [comment]
Although 0.9.2 does make some changes related to tasks, this particular issue is still not resolved. Any idea on when this will be addressed?

**Comment by gr2m** [comment]
Yes I can confirm that the issue still exists. A bit of Node.js/CouchDB knowledge should be sufficient to investigate this problem, I can't do it myself, unfortunately

**Comment by varunnaik** [comment]
Thanks for the quick response :-)

**Comment by janl** [comment]
@gr2m what backend stuff needs looking at?

**Comment by gr2m** [comment]
@varunnaik can you upload your testcase to GitHub, maybe including the node_modules folder, for debugging? Today it seemed to have worked for me, but not always. Something is not right with the `hoodie.task.success` / `hoodie.task.error` API, would be good to isolate the problem

**Comment by gr2m** [comment]
fyi I have a task object locally that has already been completed on the server by removing it (the way it's supposed to be). It should have been synced back to the frontend and the local object should have been removed, so it looks like a frontend bug, I'm investigating

**Comment by gr2m** [comment]
Okay everyone, I _think_ I found the cause of the trouble here. If you could double check it, that'd be great. It's in hoodie^0.9.3 & hoodie-server^0.9.29 (should be released in a few minutes)

Could you please check if it works as expected for you now?

PS: Sync is hard™ :/

**Comment by lupomontero** [comment]
Awesome! Just tested this and it seems to be working as expected. :+1:

**Comment by varunnaik** [comment]
I too can confirm that this now works. Thank you.

**Comment by peetersn** [comment]
Thanks @gr2m

**Comment by gr2m** [comment]
Thanks for testing everyone!
