### ISSUE TITLE
Best way to start your app after authentication

### ISSUE THREAD

**Issue by redgeoff** [hoodiehq/hoodie#292]
What is the best way to execute code upon a successful authentication? There doesn't appear to be an `onready` event and it appears that hoodie does not automatically attempt to reauthenticate if the user reloads the page and is already authenticated. I've extracted the following practice of calling `hoodie.account.authenticate()` from the sample hoodie app. Is this the recommended practice?

The following code attempts to automatically re-authenticate if the user is already signed in. If they are not signed in then it will attempt to sign in. If the sign in fails then it will attempt to sign up. This exact example is not likely to be found in a real world application, but I think it is important that these flows are well understood.

``` html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>

    <script src="assets/vendor/jquery-2.1.0.min.js"></script>
    <script src="/_api/_files/hoodie.js"></script>

    <script>

      var hoodie = new Hoodie(),
          email = 'user@example.com',
          pwd = 'secret';

      function doStuffAfterAuthentication() {
        console.log('now doing stuff');
      }

      function signUp() {
        hoodie.account.signUp(email, pwd).then(function() {
          console.log('signUp');
          doStuffAfterAuthentication();
        });
      }

      function signInOrSignUp() {
        hoodie.account.signIn(email, pwd).then(function() {
          console.log('signIn');
          doStuffAfterAuthentication();
        }, function() {
          signUp();
        });
      }

      // This doesn't appear to be triggered, even after we call hoodie.account.authenticate()
      hoodie.account.on('authenticated', function() {
        console.log('authenticated');
      });

      // This doesn't appear to be triggered, even after we call 
      hoodie.account.on('signin', function() {
        console.log('signin');
      });

      hoodie.account.authenticate().then(function() {
        console.log('automatically authenticated');
        doStuffAfterAuthentication();
      }, function() {
        console.log('not authenticated');
        signInOrSignUp();
      });

    </script>
  </body>
</html>
```

Here are some things to consider:
1. Should a call to new Hoodie() automatically call `hoodie.account.authenticate()`
2. Should the `authenticated` or `signin` events be triggered when `hoodie.account.authenticate()` is called?

**Comment by gr2m** [comment]
First thing to understand is that there are two different things:
1. signed in
2. authenticated

To check if a user is signed in, use `account.hasAccount()`. I'd then be optimistic about being authenticated (having a valid session). If hoodie tries to pull/push data and it fails due to `401 unauthenticated`, an `error:unauthenticated` event will be triggered, so you could do this:

```
hoodie.account.on('error:unauthenticated', showSignIn)
```

Once you do `hoodie.account.signIn(user, pass)`, it will go all smoothly again.

The `hoodie.account.authenticate()` is a way to make sure that you are signed in and have a  valid session.

All in all, I find this all still way to confusing. One reason is that it's quite complicated with all the cases that we have to respect. But I'm sure we can make this simpler, we're very open for suggestions. Feel free to write some dummy dream code of what methods you'd love to have, and how you'd expect them to work. Also, let's chat :)

**Comment by svnlto** [comment]
FYI:

> @svnlto: isn’t signed in and authenticated essentially the same thing?
> 
> @gr2m: no, signed in means you have all data from one account (hoodie.account.username) available offline. authenticated means, that you have a valid session towards the backend, so that sync works
> 
> @svnlto: that’s just confusing, because i think that you’re exposing internals here :)

Ideally I'd just want to call `hoodie.account.authenticate()` (or similar) to find out whether I can let the use 'in'. 

> signed in means you have all data from one account (hoodie.account.username) available offline

I feel that this is internal code and should not be directly exposed, since it leaks internal scope.

**Comment by redgeoff** [comment]
In my **dream world** I'd be able to write something like the following:

``` javascript
var hoodie = new Hoodie(),
    email = 'user@example.com',
    pwd = 'secret';

function doStuffAfterAuthentication() {
  console.log('now doing stuff');
}

function signIn() {
  hoodie.account.signIn(email, pwd);
}

hoodie.account.on('authenticated', doStuffAfterAuthentication, signIn);
```

Here's what I would expect to happen:
1. Hoodie would automatically call `hoodie.account.authenticate()`
2. If the user was already signed in then `doStuffAfterAuthentication()` would be executed
3. If the user was not already signed in then `signIn()` would be called and afterwards the `authenticated` event would be fired and `doStuffAfterAuthentication()` would be executed

The problem I foresee is that if `hoodie.account.authenticate()` is automatically called by `new Hoodie()` then the `hoodie.account.on('authenticated', ...` binding needs to executed before `new Hoodie()`

**Comment by gr2m** [comment]
note that hoodie is calling `hoodie.account.authenticate` today on initialization: 
https://github.com/hoodiehq/hoodie.js/blob/master/src/hoodie.js#L128

To achieve what you want, just do: 

``` js
hoodie.account.authenticate().then( doStuffAfterAuthentication, signIn);
```

It won't send multiple requests. But what I'd recommend you do is this:

``` js
if (hoodie.acccount.hasAccount()) {
  // user is signed in
} else {
  // user is not signed in
}

hoodie.account.on('unauthenticated', signIn);
```

Being signed in but unauthenticated is the edge case, so be optimist about it and only react if it actually occurs.

**Comment by redgeoff** [comment]
This is an example for anyone wanting code that will ensure that you are signed in with a valid user account before executing the main code, e.g. for testing:

``` javascript
var hoodie = new Hoodie(),
    email = 'user@example.com',
    pwd = 'secret';

function doStuffAfterAuthentication() {
  console.log('now doing stuff');
}

function signUp() {
  console.log('sign up');
  hoodie.account.signUp(email, pwd).then(doStuffAfterAuthentication);
}

function signIn() {
  console.log('signing in');
  hoodie.account.signIn(email, pwd).then(doStuffAfterAuthentication, signUp);
}

if (hoodie.account.hasAccount()) {
  doStuffAfterAuthentication();
} else {
  signIn();
}
```
