### ISSUE TITLE
inconsistent object type validation

### ISSUE THREAD

**Issue by merlinran** [hoodiehq/hoodie#296]
https://github.com/hoodiehq/hoodie.js/blob/master/src/lib/error/object_type.js#L23

``` js
var validTypePattern = /^[a-z$][a-z0-9]+$/;
```

https://github.com/hoodiehq/hoodie.js/blob/master/src/lib/error/object_type.js#L30

``` js
HoodieObjectTypeError.prototype.rules = 'lowercase letters, numbers and dashes allowed only. Must start with a letter';
```

There's no dash in the pattern.

It's worth discussing whether dash, underscore, or camelCase is allowed as type name, and write it down to the documentation.

**Comment by gr2m** [comment]
good point. Back when I set the restrictions for types / IDs, I wanted to make them as restrictive as possible. But meanwhile I think that we should at least allow for `-`, for both. Let's leave that open, maybe get more opinions on it. @janl @caolan Any objections?

**Comment by janl** [comment]
I don’t see an issue with dashes or underscores. I’d not do camel case.
