### ISSUE TITLE
Investigate running Hoodie in node

### ISSUE THREAD

**Issue by mmalecki** [hoodiehq/hoodie#299]
I thought it'd be neat to try and get Hoodie running in Node so that we can make offline-first CLI applications.

I'm going to experiment with this when I have some spare time.

**Comment by gr2m** [comment]
That sounds super cool! If things become more concrete, please create an issue at https://github.com/hoodiehq/discussion/issues/new, others might be interested, too!

I'll close this issue though, as there is nothing actionable in hoodie.js to resolve it

**Comment by janl** [comment]
Let's keep this open, collecting the actionables?

**Comment by gr2m** [comment]
actually, yes, why not :)
Maciej, note that we plan to migrate hoodie.js soon to PouchDB as its sync layer. I'm not sure how it works exactly, but I think PouchDB can use LevelDB as its persistance layer in a Node.js environment. 

So if I understand correctly, plan here is to make hoodie.js a client for node apps, e.g. for CLI apps, right?

**Comment by eth0lo** [comment]
Hi, 

Yesterday I actually tried to do so, but the first thing that happened was that it was unable to find jQuery, because it try to alias Deferred from jQuery.Deferred, so I would suggest to look at #311 as a starting point.

As a side note, this weekend I can work on a pull request for #311 if you are interested

**Comment by gr2m** [comment]
Sounds great @eth0lo! @svnlto already started to work on the promises, he's working on the `promise` branch: https://github.com/hoodiehq/hoodie.js/tree/promise. Maybe you two want to team up?

**Comment by eth0lo** [comment]
@gr2m Yeah sure, tomorrow I´ll be at your IRC channel to discuss it with @svnlto 

Cheers

**Comment by louisremi** [comment]
From jQuery we also use the .ajax API and two fairly trivial methods: .isEmptyObject and .isArray
I guess the PouchDB replacement layer will also deal with xhr, but would you be interested in a simple PR dealing with the latter two methods?

**Comment by boennemann** [comment]
Hello @louisremi

Thanks for your help here. We're currently in the process of refactoring hoodie's frontend code, or to be precise merging the changes made back into master.

We're trying to come up with enough integration test screnarios to confidently release a new version without breaking things.

If you want to replace the trivial jQuery methods, which is greatly appreciated, please make sure to work against the [promise_restored](https://github.com/hoodiehq/hoodie.js/tree/promise_restored) branch and bear with us until this finally lands as a new version.

Thanks, 
Stephan

**Comment by gr2m** [comment]
@mmalecki @eth0lo @louisremi I think this could be possible with the new Hoodie client. Check out the https://github.com/hoodiehq/hoodie-client repository. Only note that there is no state persistance right now, as `localStorage` falls back to an in-memory store. We could probably come up with a better solution if you need state persistance.

Ping me in the [Hoodie Chat](http://hood.ie/chat) if you have any questions. If someone’s up for it, let’s create a sample CLI application using `hoodie-client` and see where we get, and discuss on the repositorie’s issues?
