### ISSUE TITLE
admin password not working

### ISSUE THREAD

**Issue by ramstein74** [hoodiehq/hoodie#300]
I cannot access with admin password.Why?

![image](https://cloud.githubusercontent.com/assets/1210858/3072673/205d909e-e2cc-11e3-9c05-4f35dd05b3be.png)

**Comment by gr2m** [comment]
when you press the `Sign in!` button, do you see a `POST /_api/_session` request? If yes, what does the server respond with?

**Comment by svnlto** [comment]
Also, what's the hoodie version you see when you start your app?

**Comment by ramstein74** [comment]
When i start hoodie i see
Version 0.4.10 (node (V0.10.26 npm 1.4.3 platform:win32)

 when i press the login button
1. POST http://127.0.0.1:6005/_api/_session 404 (Not Found)
   plugins.js:8526
2. XHR finished loading: POST "http://127.0.0.1:6005/_api/_session".
   2.
   3.

2014-05-24 16:10 GMT+01:00 Sven Lito notifications@github.com:

**Comment by gr2m** [comment]
we could reproduce the issue and will look into it. @caolan if you have so time, that'd be great. You see it with current my-first-hoodie. Signing in to futon works, but pocket doesn't

**Comment by caolan** [comment]
There was a problem with hapi proxying of requests that looked similar to this. But I think it was fixed in current my-first-hoodie...
