### ISSUE TITLE
add {ignoreLocalChanges: true} option to hoodie.account.destroy()

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#306]

**Comment by HipsterBrown** [comment]
So the functionality of this option is to not clear the local cache when an account is destroyed when true?

Does that mean it shouldn't trigger a signOut either?

**Comment by gr2m** [comment]
actually, I can't recall what I was thinking about this issue. It doesn't make any sense to me :)

**Comment by HipsterBrown** [comment]
Alright, on to the next one then!
