### ISSUE TITLE
returning standard-compliant promise

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#311]
Until now, we use jQuery's implementation of promises for now. Reason being that we think that there is (or will be) a big intersection between users jQuery and potential users of Hoodie.

We now decided to go with standard-compliant promises as well. Reasons being
1. Developer happiness (both internal and plugin developers)
2. Integration with other libraries, like Ember, Pouch, etc
3. We can still provide `.done` / `.fail` / `.progress` callbacks that have the same signature as the counterparts of jQuery. And to the end users, these three will be the most important ones, while `.then` is more important do pluging developers

Next steps:
- [x] Find a polyfill library library for browsers that do not have native support for `Promise` (https://github.com/petkaantonov/bluebird)
- [x] Make it a Hoodie dependency
- [x] add `.done` / `.fail`
- [x] add `.progress` callbacks
- [x] replace all internal usage with the new implementation

---

Current work on this lives in the promise branch:
https://github.com/hoodiehq/hoodie.js/tree/promise_restored

**Comment by calvinmetcalf** [comment]
2 options to do:
- use a basic promise library (like my own [lie](https://github.com/calvinmetcalf/lie) or [then/promise](https://github.com/then/promise)) and extend it with your own methods. 
- pick an existing solution that has similar functionality but might have it implemented slightly differently [when](https://github.com/cujojs/when) Is a very fast library that supports progress and I believe it has done style stuff (though might call it finally)

**Comment by svnlto** [comment]
@calvinmetcalf I have started looking into conversion and think that the pouchdb approach would suite us best (congrats on the job well done btw), using bluebird and lie where applicable. 
It'd be really cool if you want to give us a hand actually :smiley:

**Comment by gr2m** [comment]
> It'd be really cool if you want to give us a hand actually

That'd be fantastic. I can't wait to finally replace our self cooked sync solution with PouchDB, and it would be great to have a PouchDB committer helping us out a bit.

**Comment by calvinmetcalf** [comment]
Thanks, I'd be happy to lend a hand, one thing to bear in mind is that
while done and fail are very easy to patch onto browser type promises
progress isn't, PouchDB uses events for this.

**Comment by svnlto** [comment]
Cool. started of by lifting PouchDB's `toPromise` util. https://github.com/hoodiehq/hoodie.js/commits/promise Thoughts?

**Comment by calvinmetcalf** [comment]
I actually have a stand alone version of that one https://github.com/calvinmetcalf/pouchdb-topromise

**Comment by gr2m** [comment]
@calvinmetcalf you have foreseen this, and now we got bit by it:

> Thanks, I'd be happy to lend a hand, one thing to bear in mind is that while done and fail are very easy to patch onto browser type promises progress isn't, PouchDB uses events for this.

We currently use the progress callback at several places in Hoodie Core.

### `hoodie.account.signUp`

A sign up has two steps:
1. Create new user account
2. User account gets confirmed by the backend. This currently happens automatially, but we will soon support email confirmation and custom plugin-based workflows

`1.` triggers the progress event, `2.` resolves.

``` js
hoodie.account.signUp()
  .progress(showWaitingForConfirmationMessage)
  .done(showWelcomeMessage)
```

### `hoodie.task.start`

This is our underlying API for background tasks. Plugins usually wrap it with their own API, like the email plugin, which provides `hoodie.email.send(properties)`

The Process looks like this
1. Store JSON object for task locally 
2. Replicate to remote
3. Gets picked and handled by respective plugin
4. When done, remove task object
5. Replicate removal to frontend

`2.` triggers progress, `5` resolves.

As an app developer, this is important, as I can still cancel the task before 2. is triggered. I could show a notification like "sending email" with a cancel button. On the progress event, I'd hide the notification and in case an error occurs, which should be the exception, I'd show an error notification. That also means that I'd like to provide an `.abort()` callback like [jQuery's ajax](http://api.jquery.com/jquery.ajax/) method, but lets focus on `.progress()` for now.

``` js
showSendingEmailNotification()
hoodie.task.start('email', emailProperties)
  .progress(showEmailSentNotification())
  .fail(showEmailErrorNotification)
```

### `hoodie.store.findAll` (and all other store methods)

Usually the `hoodie.store` methods like `findAll` do not progress, they resolve immediately. But it changes its behavior when a user signs in.

Signing in triggers a bootstrap of all data. In this state, all `hoodie.store` methods are queued, until the bootstrap finished. But while Hoodie is receiving objects from the bootstrap, it triggers the progress callback so I can fill up the app with content and don't need for the bootstrap to finish.

``` js
hoodie.signIn(user, pass)
  .then( hoodie.store.findAll ) // returns new promise by hoodie.store.findAll
  .progress(handleNewObject)
```

Another common use case will be once we diverge local and remote store. Currently all data is mirrored. We plan to make this optional, so only a relevant subset of data is synchronized. `hoodie.store.findAll()` will then only find data that is locally available, unless something like `remote: true` option is passed. I could see something like this be supported by Hoodie soon

``` js
startLoader()
hoodie.store.search('keyword here', {in: ['title','name','description','note'], remote: true})
  .progress(updateResults)
  .done(stopLoader)
```

---

Just 3 examples to show the value of a way to handle progress on an asynchronous task.

For Hoodie, the API is the most critical part. It's more important than performance, and even standards compatibility. That doesn't mean that we need the exact syntax shown above, I just can't think of a more or equally elegant API to handle progress. I'm very open for suggestions.

The questions I currently have
1. What are your thoughts on this?
2. How would you suggest to approach this problem?
3. Whom else should we ask for opinion?

**Comment by gr2m** [comment]
suggest by @jaz303 to extend promise with progress callback before returning it https://gist.github.com/jaz303/5e702c797819c388ac98

**Comment by gr2m** [comment]
Thanks for your input so far! I've added support for progress callbacks trough our custom defer implementation:

``` js
function getDefer() {
  var defer = {};
  defer.promise = new Promise(function (resolveCallback, rejectCallback) {
    defer.resolve = function resolve() {
      defer.notify = function noop () {};
      resolveCallback.apply(null, arguments);
    };
    defer.reject = function reject() {
      defer.notify = function noop () {};
      rejectCallback.apply(null, arguments);
    };
  });

  defer.promise._progressCallbacks = [];
  defer.notify = function notify() {
    var args = Array.prototype.slice.call(arguments);
    defer.promise._progressCallbacks.forEach(function(callback) {
      callback.apply(null, args);
    });
  };

  defer.promise.done = function done(callback) {
    this.then(callback);
    return this;
  };
  defer.promise.fail = function fail(callback) {
    this.then(null, callback);
    return this;
  };
  defer.promise.always = function always(callback) {
    this.then(callback, callback);
    return this;
  };
  defer.promise.progress = function progress(callback) {
    if (this._progressCallbacks) {
      this._progressCallbacks.push(callback);
    }
    return this;
  };

  return defer;
};
```

The custom Promise methods `done`, `fail` and `progress` to return the same promise instance, so they can be chained without side effects, while `then` returns a new promise as per spec.

``` js
d = getDefer()
d.promise
.progress( function(value){ console.log('progressed with', value) })
.done(  function(value){ console.log('resolved with ', value) })
.fail(  function(error){ console.log('rejected with ', error) })

d.progress(1)
// progressed with 1
d.progress(2)
// progressed with 2
d.resolve('done')
// resolved with done
d.progress(3)
// nothing happens, has promise is settled.
```

It works™ But still open for suggestions to improve it.

**Comment by gr2m** [comment]
Let's move on. If anyone wants to improve the internal implementation, go ahead. If you want to discuss our promise API, open a follow up ticket please

**Comment by calvinmetcalf** [comment]
looks like a good solution, glad I could help :)

On Tue, Sep 9, 2014 at 6:37 AM, Gregor Martynus notifications@github.com
wrote:

> Let's move on. If anyone wants to improve the internal implementation, go
> ahead. If you want to discuss our promise API, open a follow up ticket
> please
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hoodiehq/hoodie.js/issues/311#issuecomment-54969559.

## 

-Calvin W. Metcalf
