### ISSUE TITLE
Outside modifications of the database won't get synced to clients without server restart

### ISSUE THREAD

**Issue by mart-jansink** [hoodiehq/hoodie#312]
I'm trying to use hoodie in a situation where another application is writing to the same CouchDB document store while adhering to the format (fields, id's, etc.) defined by hood.ie. In principle this works, the clients eventually receive the added items, however, it only happens after the hood.ie server is restarted. This of course is undesired..

Is this done by design, e.g. does hoodie keep an in memory copy of all documents? And can something be done to force hoodie to sent the clients the added documents without restarting?

**Comment by janl** [comment]
this doesn’t sound right. Hoodie uses CouchDB’s _changes feature and everything should work as you describe you expect it.

**Comment by mart-jansink** [comment]
Apologies, it indeed does work. Apparently, another instance of CouchDB was running and causing issues.. Adding documents now works as expected: they show up immediately in the client. However, documents that are removed (either through the _utils interface or using curl) still remain until the client is reloaded.

**Comment by janl** [comment]
cc @gr2m can you comment on propagating deletes?

**Comment by gr2m** [comment]
you have to remove objects by adding a `"_deleted": true` property, a `DELETE` request won't do, as the new revision looses all the other properties that Hoodie depends on to trigger its events correctly
