### ISSUE TITLE
grunt release does not publish to npm

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#314]
the travis tests do pass now, but hoodie.js version wasn't published to npm automatically. I thought it should as part of the release process?

@boennemann @svnlto

**Comment by gr2m** [comment]
same for hoodie-server. Tests passed, I just run `grunt release`. Do I need to do anything else?

fyi I know published latest versions for both manually using `npm publish`

**Comment by boennemann** [comment]
The Travis log shows an npm error https://travis-ci.org/hoodiehq/hoodie.js/builds/26837612#L4266-L4318
Seems to me like it's not exactly our fault. You published manually in the meantime, right @gr2m?

**Comment by gr2m** [comment]
> Seems to me like it's not exactly our fault

Oh sorry, I missed that, all good then

> You published manually in the meantime

Yes sir!

**Comment by boennemann** [comment]
Maybe you could trigger a rerun on Travis next time this happens, so we can verify that this was indeed just a temporary npm hiccup (:  

![travis_ci_-_free_hosted_continuous_integration_platform_for_the_open_source_community](https://cloud.githubusercontent.com/assets/908178/3186027/831ab10c-ec9b-11e3-86ae-49b236c0cf5e.png)

**Comment by boennemann** [comment]
Uh-oh, and for hoodie-server it's our fault. I'll open an issue in a few.
