### ISSUE TITLE
failed to login to admin hoodie 0.4.14

### ISSUE THREAD

**Issue by ramstein74** [hoodiehq/hoodie#317]
why cant i log to my admin? 
![image](https://cloud.githubusercontent.com/assets/1210858/3187350/afdda942-ecaf-11e3-9d30-b7b0d120107a.png)

**Comment by boennemann** [comment]
Hello @ramstein74,

Thank you for your report. This should be fixed with the latest hoodie versions. Please report back if the problem persists.

Best Stephan
