### ISSUE TITLE
Support pagination with findAll()

### ISSUE THREAD

**Issue by ndarilek** [hoodiehq/hoodie#320]
Perhaps this already exists and I haven't spotted it. I'd like to see pagination via skip: and limit/count: options in findAll(). At the moment it looks like you're limited to finding all objects of a given type or a filter function. Not sure how I might use those mechanisms to, say, only return my first 50 photos or todo items.

**Comment by gr2m** [comment]
there is no feature build in for pagination yet, but I think @espy put some thought into how it could work.

What you'd do now is something like

``` js
var skip = 100;
var limit = 20;
hoodie.store.findAll('document').then( function(documents) {
  documents = documents.slice(skip, skip + limit);
  // do something with documents now
});
```

**Comment by peetersn** [comment]
I would be looking forward for such a feature. Any chance this will ever come to an upcoming release anytime soon?

**Comment by gr2m** [comment]
That is something we can look into once we migrated to PouchDB, as it offers a pagination API:
http://pouchdb.com/2014/04/14/pagination-strategies-with-pouchdb.html

What `hoodie.store` API would you wish you'd have for pagination?

**Comment by peetersn** [comment]
Something super simple with `skip` and `limit`. 

```
var skip = 100;
var limit = 20;
hoodie.{store|remote}.findAll('document', skip, limit).then(...);
```

In our use case, we have to load messages (from `remote` (so this is also where we'd like this API)) in each users's store, which is inefficient. So we end up loading all and then we trim the results' list.

PS: Any rough timelines for PouchDB?

**Comment by ndarilek** [comment]
Maybe an options hash:

Hoodie.store.find("document", {limit: 10, skip: 1}, function() { ... })

where the options hash is optional.

**Comment by peetersn** [comment]
Even better suggestion from @ndarilek indeed.

**Comment by gr2m** [comment]
Yeah I'd definitely go with an options hash as @ndarilek suggests, I'll just would like to think about what the options would be. Besides `limit` and `skip` it could for example also be `perPage` and `page`, I'd like to gather more input here, with dreamcode & use cases.

> Any rough timelines for PouchDB

This year. Before 1.0.0

**Comment by ndarilek** [comment]
I like limit and skip; perPage and page seem more forgettable to me but 
I won't bikeshed. :) Also, perhaps you have a situation where the user 
has moved down some number of records not equal to a full page, so you 
may want to display 10 records but skip 25.

I also like how ReQL structures its queries with distinct, function-like 
operations and a final run() method on the end. Maybe bring the store 
API in line with existing promises, something like:

Hoodie.store("todo").limit(10).skip(10).orderBy("title").then(function(results) 
{
     })

**Comment by peetersn** [comment]
@gr2m If we don't want to (or can't) wait for PouchDB support, can you give a few hints of what we can do (where we need to hack this in the hoodie server)?

**Comment by gr2m** [comment]
Im travelling today, but I'll look into it tomorrow or Thursday latest—
Gregor Martynus

**Comment by peetersn** [comment]
@gr2m No rush :-)

**Comment by gr2m** [comment]
I think the best would be to define custom [CouchDB views](http://guide.couchdb.org/draft/views.html) on the database(s) in question, and then do something like

``` js
var store = hoodie.open(dbName)
store.request('get', 'design/designdocname/_view/viewname')
```

You could encapsulate that logic in a nice plugin, too.  This of course solves the problem of pagination only for remote stores, but I hope that helps @peetersn already?

**Comment by varunnaik** [comment]
I tried something like this:

```
flight.request('/_design/chat/_view/messages?startkey=["'+
                chatroomId+'"]&include_docs=true&limit=10&descending=true').then(function(d) {
                console.log("Got documents", d);
            }, function(e) {
                console.log('Error getting docs', e);
            });
```

But it results in `HoodieConnectionError: "Could not connect to Hoodie server at /."`

Hoodie itself works fine elsewhere, though.

**Comment by gr2m** [comment]
can you look what exact request the browser is sending, with the full URL? Is the app where the request comes from and the Hoodie backend on the same Domain?

**Comment by varunnaik** [comment]
The browser doesn't seem to send any request, strangely. I don't see a thing in the network tab of the dev tools.

Calling `flight.request()` with no parameters at all gives this error in the console: `GET http://localhost:9000/_api/flightundefined 404 (Not Found)`

This is on my local dev setup, grunt serves the app at localhost:9000, Hoodie is up at localhost:6004 and localhost:9000/_api is proxied to Hoodie. However, the browser does not seem to send a request at all so I don't know if this matters. Everything else Hoodie-related works properly in my setup. Using Hoodie 0.9.4.

**Comment by gr2m** [comment]
ahhh got it. Sorry, my bad. First parameter for `request` is the http verb.

So correct code for the example above would be

``` js
var store = hoodie.open(dbName)
store.request('get', 'design/designdocname/_view/viewname')
```

Does that work?

**Comment by varunnaik** [comment]
That works beautifully, thank you :-) Sorry I couldn't reply sooner, I was away from my PC this weekend and couldn't test it sooner.

I have a final question: How do I create views within a Hoodie plugin? I would like to do this programatically on server startup, if the view does not already exist.

**Comment by gr2m** [comment]
> I was away from my PC this weekend 

That's the very last thing you have to explain :) We all should be off PC over weekends :)

> How do I create views within a Hoodie plugin? I would like to do this programatically on server startup, if the view does not already exist.

In the `index.js` (or `worker.js`, what ever you specified as main in package.json), you get a `doneCallback` passed to the plugin initialziation. I'd simply try to create the view every time. If it fails because it already exists, call the doneCallback anyway.

I'll close this issue, but if you still have a question regarding plugin, please open another issue on the hoodie-server repo
