### ISSUE TITLE
Clarify relationship between accounts and sync

### ISSUE THREAD

**Issue by ndarilek** [hoodiehq/hoodie#321]
Not sure if this issue belongs here or in another repository. I'm unclear on the distinction between having no account, an anonymous account and a full account. I'm also unclear on what degree of synchronization these setups permit. In particular:
1. When am I permitted to use Hoodie.store? Can I use it with no account or an anonymous account?
2. When is local storage synced with the server? Anonymous accounts seem to permit adding tasks for things like sending emails, but given Hoodie's offline-first nature, can I build apps that store some information offline via Hoodie.store, then only sync with the server at some point later in the process once an account is created?

I'm trying to prototype a simple wizard-based app with Hoodie. Initially I want users to enter values and treat Hoodie.store like a local storage convenience, but once they've hit a certain point and see the value we provide, I plan on asking them to create an account and push their data to our servers. I'd like to understand whether this can work, and at what point Hoodie expects to go beyond local storage, or even if it will let me use local storage without asking the user to sign up.

Thanks.

**Comment by gr2m** [comment]
Hey Nolan, you've hit a nerve here, we are aware that the `hoodie.account` module can be somewhat confusing to people, and we will soon rethink the provided methods and add sufficient documentation.

In a nutshell:
1. You can always use `hoodie.store` methods. If you create an account later, the data created beforehand will be synced then.
2. no account  
   That's how you start. No account means that all data is stored locally only, there is no synchronization. 
3. anonymous account  
   This is more of an implementation detail, you shouldn't have to care about it. Technically it means that your data gets synced to the backend. An anonymous account gets created automatically the first time you call `hoodie.task.start`, as tasks depend on being synced to the server. If you call `signUp` while having an anonymous account, it's internally a username & password change. But as I said, usually you shouldn't care about it.
4. account (as you say "full account")  
   when you call `hoodie.account.signUp`, you will have an account and `hoodie.account.username` will be set.

I hope that clarifies things a bit. To answer your questions:

> When am I permitted to use Hoodie.store?

always.

> When is local storage synced with the server?
1. when you call `hoodie.account.signUp`
2. when you call `hoodie.account.anonymousSignUp` (e.g. to prevent data lass of users that do not sign up)
3. when you call `hoodie.task.start` the first time

> can I build apps that store some information offline via Hoodie.store, then only sync with the server at some point later in the process once an account is created?

Yes.

---

Your wizard-based app sounds like a great fit for Hoodie. What you describe should work perfectly as you expect. In fact, I'll do a similar thing for an app, where I will ask users to sign up to prevent data loss. And signing up will also be where people will have to pay for it.
