### ISSUE TITLE
Seperation of Concerns for Accounts

### ISSUE THREAD

**Issue by yangvz** [hoodiehq/hoodie#322]
Organizing everything with accounts is impossible, unless scientists figure out better alternatives to relational databases. Any heavy website have more complex relationships than what nosql offers.

Rather, accounts can be separated into `users` and `memberships`.One user imitates one person, but only merged into the network of relations being a member. hoodie handles user authentication and such, while user.membership is made explicitly available as a database object, something you write sql calls with. Not something you'd dream about but something you live with.

**Comment by janl** [comment]
I’m not sure I understand the problem here, or the question you are asking.
