### ISSUE TITLE
method to check whether a username is available or not.

### ISSUE THREAD

**Issue by louisremi** [hoodiehq/hoodie#327]
I'm aware that trying to register a username will return a 409 when the username is already used. But I need a way to tell whether a username already exists or not without creating an account in the case that it didn't exist.

Is it already possible by sending a specific query to the server?

**Comment by gr2m** [comment]
No, unfortunately not, but I agree it's something we should add. It's not trivial though, I'm not sure it's possible at all in CouchDB only. 

@janl @caolan Is there a way in CouchDB to find out if a username is still available, without being authenticated?

**Comment by louisremi** [comment]
To solve my specific use-case I could also allow users to create un-confirmed accounts, and confirm the account at a later stage. Is it already possible with the current API?

**Comment by gr2m** [comment]
no, unfortunately not, if a user doc gets created, it gets picked up automatically by our users worker and confirmed.

I think to solve this, the users plugin should expose a custom API. We did that with other plugins already, I'm not sure if it's documented somewhere. But it's build into https://github.com/hoodiehq/hoodie-plugin-template, there you can check out how to do it. Also note that @caolan is currently reworking the users plugin.

I think to get going quickly, I'd fork the users plugin and build in the custom hook. I think the backend API allows to find out if a user exists or not quite easily

**Comment by louisremi** [comment]
Alright, I'll give this a try.

**Comment by gr2m** [comment]
With the new Hoodie, you can define custom "requests" in the account module. We already use it for a password reset, but you could define a "username-exists" request to achieve what you want. Check out [the client API](https://github.com/hoodiehq/hoodie-account-client#accountrequest) and the example of the [server API options](https://github.com/hoodiehq/hoodie-account-server/blob/master/plugin/README.md). Please let me know if you have any farther questions, either comment here or find me in the [Hoodie Chat](http://hood.ie/chat) `#dev` channel or dm me `@gregor`
