### ISSUE TITLE
hoodie.store.updateAll 

### ISSUE THREAD

**Issue by ghost** [hoodiehq/hoodie#329]
Version: 0.4.9 (node v0.10.28, npm 1.4.13, platform: darwin)

Hello all!

While documenting the hoodie.store i recognized a unregularity in the API. Please see the following example code:

```
var todoStore  = hoodie.store('todo'),
    objectUpdate = {done: true};

todoStore
    .updateAll(objectUpdate)
    .then(function(updates) {
        console.log('the following todos are done', updates);
    });
```

Then the promise is resolved an .then() has been called, the `updates` parameter seems to have the first updated object only. Similiar to findAll the user would most likely await to work with an array of updated objects here.

When I see `arguments.length` of .then(), it has the same length as I have todo objects in my store. It seems as if the array of updates is applied to the promise closure instead just passing the array as first parameter.

Thanks for looking into this! :)

Regards,
Dennis

**Comment by gr2m** [comment]
thanks!
