### ISSUE TITLE
hoodie.account

### ISSUE THREAD

**Issue by zoepage** [hoodiehq/hoodie#330]
- review all methods before 1.0 release
- add hoodie.account.isSignedIn() / isSignedOut;

**Comment by janl** [comment]
cc https://github.com/hoodiehq/documentation/issues/33

**Comment by zoepage** [comment]
We could think about implement the additional account data in this step...

 Options?

**Comment by gr2m** [comment]
closing in favor of https://github.com/hoodiehq/discussion/issues/47
