### ISSUE TITLE
hoodie.account.username is not undefined after signOut()

### ISSUE THREAD

**Issue by zoepage** [hoodiehq/hoodie#331]
hoodie.account.username is not undefined after signOut(). I still get the username, also after refreshing the page.

**Comment by zoepage** [comment]
i might found the problem. (tested in my-first-hoodie)
after revisiting the page, i'm not signed in officially in the account-bar, but in the background i still am.

this might be also a use case for hoodie.account.isSignedIn()

**Comment by gr2m** [comment]
I can't reproduce the problem. In my-first-hoodie, after I sign up I have to reload the page (which seems like a UI bug). But after I hat the sign out button, `hoodie.account.username` is undefined, as expected. Am I missing something?
