### ISSUE TITLE
Idea for hoodie.store.validation

### ISSUE THREAD

**Issue by ghost** [hoodiehq/hoodie#332]
I spoke to @gr2m about that recently and he wanted me to create an issue for this. So this shall just be my 2 cent to the subject.

The hoodie.js store has a validation function, that checks objects before saving for a proper userId. How about enabling the users to pass a validation function of their own? I tried to figure out to pass a custom validation, that would look something similiar to this:

``` js
function(todo) {
  if(typeof todo.due !== 'number'  || todo.due < 0) {
     throw new Hoodie.Error('The due date has to be a valid Unix timestamp.')
 }
 return todo;
}
```

For sure this should only be one part of the validation process. The final validation should happen on the serverside. Validating on the clientside should be vital in order to build offline first applications here. 

Since CouchDB uses JavaScript for serverside valiations, we can have a benefit here, too. Perhabs it would would be nice to configure validations per store with pocket, and the first time a application user enters the hoodie app, those validations will be delivered to the webbrowser.

**Comment by espy** [comment]
That's probably the best way to go in the long run: the ability to define allowed object types and their attributes in Pocket. And also maybe do configurable rate-limiting via the validation plugin as well at some point.

**Comment by gr2m** [comment]
closing in favor of https://github.com/hoodiehq/hoodie-store-client/issues/101
