### ISSUE TITLE
Nested/child data

### ISSUE THREAD

**Issue by redgeoff** [hoodiehq/hoodie#334]
Is there a way to access nested/child data? For example, if I am storing a _task_ like:

``` javascript
var type = 'task';
var attributes = {status: 'open', tags: ['thing1', 'thing2']};
hoodie.store.add(type, attributes)
  .done(function (newObject) {});
```

is there then a way to perform a hoodie.store.update or hoodie.store.find on **just** the _tags_? e.g. something like `type = 'task/<task-id>/tags'`

**Comment by gr2m** [comment]
You can pass a filter function to `hoodie.store.findAll`, like so

``` js
var tagStore = hoodie.store('tag');
tagStore.findAll(function(obj) { return obj.id === 'taskId'; }).done(showTags)
```

does that work?

**Comment by redgeoff** [comment]
Thanks @gr2m, but unfortunately, I don't think this addresses my question.

``` javascript
hoodie.store('tags').findAll(function(obj) { console.log(object); });
```

doesn't find anything, nor does using:

``` javascript
hoodie.store('tag').findAll(function(obj) { console.log(object); });
```

Sure, my example seems silly as the data is so simple, but what if our task contained one more level of nesting?

``` javascript
task = {
  id: 1,
  description: 'do something',
  note: [
    {id: 1, text: 'my note 1', tags: ['thing1', 'thing2']},
    {id: 2, text: 'my note 2', tags: ['thing3', 'thing4']}
  ]
};
```

How could we write/read just the _tags_ for _my note 2_ without reading/writing the entire task? I know this is still a silly example, but you can see how repeated nesting could complicate things. The point I'm trying to make is that it appears to me that in order to write/read these nested attributes we have to load the entire _parent_ object (in this case the task).

Is this an intentional design? Is the assumption in hoodie that most nesting will consist of reference ids to other _root_ objects? If so, I think this is fair as the _offline-first_ nature of hoodie makes things more complicated.

Consider how firebase appears to handle the nesting, they [append a _child_ to the firebase URL](https://www.firebase.com/docs/creating-references.html).

Does it make sense to consider something similar in hoodie via some sort of chaining? For example:

``` javascript
hoodie.store.find('task', 1).find('note', 2).done(function (object) {
  // object == ['thing3', 'thing4']
});
```

**Comment by gr2m** [comment]
Relations between objects is not something that we plan to support in Hoodie core. Code like

``` js
hoodie.store.find('task', 1).find('note', 2).done
```

Looks a lot like a SQL based query library, which works great for relational databases. But Hoodie is object based. You can either store the child objects as property in the parent object.

A `findAll` returns a promise, you have to add callbacks to react on it, like so:

``` js
hoodie.store('tag').findAll().done(function(objects) { console.log(objects); });
```

One thing I could imagine to add later (either core or as plugin) are views, similar to [CouchDB Views](http://guide.couchdb.org/draft/views.html). Once defined, you'd be able to do something like

``` js
hoodie.store.view('tasksByTag', ['thing1']).findAll().done( showTasks )
```

Would that work?
