### ISSUE TITLE
Missing "add" events

### ISSUE THREAD

**Issue by redgeoff** [hoodiehq/hoodie#335]
Steps to reproduce:

1 - Run the following code in 3 different tabs:

``` html
<html>
<body>
  <script src="../../assets/vendor/jquery-2.1.0.min.js"></script>
  <script src="/_api/_files/hoodie.js"></script>
  <script>
    var hoodie = new Hoodie();

    hoodie.remote.on('add:task', function(newObject) {
      console.log('add of task =');
      console.log(newObject);
    });

    function addTask() {
      hoodie.store.add('task', { data: (new Date()).toUTCString() });
    }
  </script>
  <button onclick="addTask()">Add</button>
</body>
</html>
```

2 - In tab 1 click _Add_ then **quickly** switch to tab 2 and click _Add_

3 - Wait a few seconds and in tab 3 you'll see that only the second of the two _add_ events is received (see console).

It is interesting to note that if you wait longer, e.g. 10 seconds, between clicks, then tab 3 receives both _add_ events.

I'll try to look into this further, but wanted to note the problem first.

**Comment by gr2m** [comment]
Good catch @redgeoff, I was able to reproduce the problem. I don't know yet what is causing it though. The reason why it works if you wait for longer than a few seconds is the build in 2s timeout (that we will get rid off soon). It must have to do something with this timeout.

This problem will go away for sure once we  migrate to PouchDB, that I'm sure of. Is this a big problem for you at the moment?

**Comment by redgeoff** [comment]
Any idea when the migration to PouchDB will be completed? Have you begun work on it? It's going to be a great addition to hoodie!

**Comment by svnlto** [comment]
We're working on changes that are required in order to implement PouchDB integration, switching out jQuery dependencies etc.

**Comment by gr2m** [comment]
> Any idea when the migration to PouchDB will be completed

This year. We'll announce more precise time frames as fast as possible

**Comment by gr2m** [comment]
closing in favor of https://github.com/hoodiehq/hoodie.js/issues/362
