### ISSUE TITLE
destroyed usernames cause db conflict upon re-use attempt

### ISSUE THREAD

**Issue by xpollen8** [hoodiehq/hoodie#34]
when a user account is destroyed (in the default app), re-use of the username causes a db conflict

**Comment by gr2m** [comment]
sorry for the late response, @xpollen8.

This is a problem we are aware of. And I know how to fix it, it's just not the priority at the moment. But I'll get back to it

**Comment by gr2m** [comment]
hm that issues seems to be resolved in latest CouchDB (v1.3.0), can you confirm?
