### ISSUE TITLE
Best document structure design for collaborative flow using hoodie

### ISSUE THREAD

**Issue by steve21124** [hoodiehq/hoodie#341]
Best document structure/code structure design collaborative design using hoodie using less round trip to server.

Collaborative task list 
- User A : create task1, task2
  
  User A add list_a to task1 and list_b to task1
  
  User A share task1 to User B
- User B : create task3
  
  User B add list_c to task1

=========== Method 1 
User A

hoodie.store("tasks",{"task":"task1","list":{"list_a","list_b"}) 

hoodie.store("tasks","task2")

hoodie.store.find('tasks', 'task1').share();   --> How to Share to User B  but not User C?

User B
hoodie.store("tasks","task3") 

hoodie.store("tasks","")   ====> How User B add "list_c" to task1 ?

========== Method 2

**Comment by gr2m** [comment]
Hey Steve,

if I understand you correctly, private shares is what you want. The API for it is ready, but the plugin still needs to be implemented, I'm afraid. Find out more on the current state of shares at https://github.com/hoodiehq/documentation/wiki/The-Hoodie-FAQ-%E2%80%93%C2%A0Work-in-Progress#what-about-shares

**Comment by steve21124** [comment]
thanks. I wish the implementation is ready :) hehehe

**Comment by gr2m** [comment]
@steve21124 are you good with Node.js / CouchDB? In that case you could help to make it happen. If you need it for a client project or your company, there's also the possibility to sponsor its implementation, in case that is an option.

Trust me we all wish the implementation would be ready, I need it badly for an own app myself :) But it's not a top priority at the moment.

**Comment by steve21124** [comment]
Thanks. i after evaluating, I might not have urgent need for it right now. though it might be in the future.  If that time come, I might sponsor implementation or try to contribute coding it. 
thanks
