### ISSUE TITLE
Refactor hoodie.js: externalize state for simpler testing

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#343]
this is in process, see https://github.com/hoodiehq/hoodie.js/commit/b3f53975e468198fc66f831feb3444bc649d11f5 for example.

**Comment by boennemann** [comment]
I'll maintain my todo list here, where I'll check off modules :shipit: 
- [x] hoodie
  - [x] :red_circle: account
  - [x] :red_circle: connection 
  - [x] :red_circle: id 
  - [x] open
  - [x] :red_circle: remote 
  - [x] :red_circle: request 
  - [x] :red_circle: store 
  - [x] :red_circle: task 
- [x] lib
  - [x] error
    - [x] error
    - [x] object id
    - [x] object type
  - [x] store
    - [x] :red_circle: api 
    - [x] :red_circle: remote 
    - [x] :red_circle: scoped
  - [x] task
    - [x] scoped
  - [x] ~~events~~ replaced w/ EventEmitter wrapper
- [x] utils
  - [x] promise
  - [x] :green_heart: events
  - [x] config
  - [x] generate id
  - [x] hoodiefy request error name
  - [x] :green_heart: local storage wrapper

:red_circle:: Tests don't even run before the refactoring.

**Comment by svnlto** [comment]
If you don't mind I steal the above and add test status to the rest.

**Comment by boennemann** [comment]
@svnlto Sure go ahead. You wanna do this right here? I could then focus on refactoring the ones where tests pass (:

**Comment by svnlto** [comment]
> You wanna do this right here? 

will do.

**Comment by gr2m** [comment]
fixed via https://github.com/hoodiehq/hoodie.js/pull/356
