### ISSUE TITLE
Is hoodie good for where one table only need to be store in server but not local scenario ?

### ISSUE THREAD

**Issue by steve21124** [hoodiehq/hoodie#348]
Let say I have 1 millions cities data profile. I only want user to search the cities profile but not sync it locally. Is hoodie can search table in remote database which are not local? or it is better to add additional method nodejs code to search table in server and only use hoodie for sync local and server(if published)

I did checkout
Selective Sync
https://github.com/hoodiehq/hoodie.js/issues/152

Hoodie Global Share Plugin
https://github.com/hoodiehq/hoodie-plugin-global-share

**Comment by davidpfahler** [comment]
You can write a hoodie plugin that essetially wraps the node.js code you are talking about. You could create a new database in couch (or whatever database you want to use) and let the plugin talk to the database and return results to the client. Of course, this would not be "offline first".

**Comment by davidpfahler** [comment]
@gr2m @ffffux A variation of this question might be a candidate for hoodiehq/faq. "Can I access databases with hoodie, that I don't want to sync to each user?" or similar.

(Please close as you see fit)

**Comment by lenareinhard** [comment]
@davidpfahler good point, created https://github.com/hoodiehq/faq/issues/33
