### ISSUE TITLE
password confirmation screen not used/ignored

### ISSUE THREAD

**Issue by xpollen8** [hoodiehq/hoodie#35]
reproduce: in the default app - decline to fill in the 2nd password field, account will be created anyway

**Comment by gr2m** [comment]
that's by design, the Hoodie method doesn't take a confirmation, you need to handle that yourself. But I've added a ticket at https://github.com/hoodiehq/my-first-hoodie/issues/9 to fix it in the example app

**Comment by gr2m** [comment]
thanks for bringing that up!
