### ISSUE TITLE
Add methods to change end point(s)

### ISSUE THREAD

**Issue by davelab6** [hoodiehq/hoodie#351]
Following #8 I'd like to suggest Hoodie add methods to allow web developers to allow users to choose their Hoodie API end points - that is, where their data is being remotely stored.

At the moment, the end point is used as the arg for the `Hoodie()` method:

``` js
hoodie = new Hoodie('http://server:port/_api');
```

And, maybe I missed it, but there seems no way for a user to choose another end point. 

Perhaps something like this:

``` js
hoodie.endpointUpdate('http://server:port/_api');
```

Or perhaps this could have multiple end points:

``` js
hoodie.endpoint.add('http://server:port/_api');
hoodie.endpoint.remove('http://server:port/_api');
hoodie.endpoint.removeAll();
hoodie.endpoint.find();
hoodie.endpoint.findAll();
```

The ability to do so is already now very practical, since there are a few 'CouchDB as a Service' providers. Switching from the custom localStorage shim to PouchDB can make the choice of datastore providers even wider. Also, some users might want to turn off remote storage of their data and rely solely on localStorage. 

I think this important because it is part of the answer to the challenge of ['Who does that server really serve?'](https://www.gnu.org/philosophy/who-does-that-server-really-serve.html): Put all of copyleft free software web applications client-side, and make it easy to pick a server.

A 'Pick your datastore' preference seems important to me for every Web app with a political ideology of autonomy. You choose no store at all, or localhost, or a remote one that you own/control at the level that matters to you - the jurisdiction, the hardware, the property.

**Comment by gr2m** [comment]
> `hoodie = new Hoodie('http://server:port/_api');`

You actually just need `hoodie = new Hoodie('http://server:port');`, the `/_api` part gets added automatically.

I don't understand the problem yet. If you want to build an app that connects to different Hoodie Endpoints, why not put that into the app's logic and ask the user to put in a URL that can be stored locally and be used in future to initialize `hoodie new(customUrl)`.

Please clarify

**Comment by davelab6** [comment]
> the /_api part gets added automatically.

Its given in the example on the homepage :)

I was thinking of an app changing end points after hoodie is initialized.

**Comment by gr2m** [comment]
@davelab6 you can pass a full URL to `hoodie.request` or `hoodie.open`. I don't see a use case why you'd like to change the endpoint after Hoodie got initialized.
