### ISSUE TITLE
Possible performance issue: Hoodie pooling request

### ISSUE THREAD

**Issue by steve21124** [hoodiehq/hoodie#353]
hoodie pooling every 2-3 seconds and every plugin has its own pooling.

the read request easy run out for couchdb hosting
http://i.imgur.com/eQ7iq7K.png

**Comment by steve21124** [comment]
I have another possible scenario use. if I only want to use hoodie to sync data only once a day, is hoodie a right tool to use? usually, this use for content base that only "refresh only once in a day'

**Comment by gr2m** [comment]
yeah you can run `hoodie.remote.disconnect()` after you signed in, and then manually call `hoodie.remote.sync()` at your convenience

**Comment by steve21124** [comment]
Thanks good solution.
