### ISSUE TITLE
Error when creating a new Hoodie app

### ISSUE THREAD

**Issue by metpb** [hoodiehq/hoodie#354]
Hi, maybe I did something wrong here, but an error shows up when creating an app which says, "stream.js:94 
throw er; // Unhandled stream error in pipe."

The app gets created, but shows up empty in my directory.
Below is the screenshot. Thanks.

![hoodie-issue](https://cloud.githubusercontent.com/assets/7520672/3919627/8330a43e-23ab-11e4-8379-5cfd641f25e4.png)

**Comment by orribl** [comment]
Same, here, also get a similar error message & an empty directory created.

<pre>
<code>
Version: 0.6.0 (node v0.10.31, npm 1.5.0-alpha-4, platform: linux)
[hoodie] Fetching template via npm. This may take some time.
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: ENOENT, utime '/home/florian/Projects/node_modules/my-first-hoodie/node_modules/hoodie-server/node_modules/couchr/node_modules/follow/test/stream.js'
</code>
</pre>

**Comment by orribl** [comment]
Starting the command as sudo worked for me....

Had to run 
<code>sudo chown -R user /path/to/dir</code>
afterwards for the project dir

**Comment by metpb** [comment]
Hi, thanks. It worked. But sadly again there's another problem ;)
Now the directory does have all the assets, but an error shows up on the terminal after I start the app.

I'm able to run the app, but don't I understand this error thingy.

![toodie-issue-two](https://cloud.githubusercontent.com/assets/7520672/3976804/cfbbb6b6-282b-11e4-92f2-a9db4a0f831f.png)

**Comment by orribl** [comment]
Hi,

I updated my previous comment, did you do the following:

<code>sudo chown -R user /path/to/dir</code>?

**Comment by metpb** [comment]
Nope. It's getting hard for me to understand the error.
Okay, I'll try that. :)

**Comment by orribl** [comment]
I think the reason for the error is that the example folder (and all subsequent folders) where created under the super user (sudo), if you run the start instruction under your own id you get a permission error (starting under super user is not permitted as well). Therefore you have to change the ownership (chown), in the command above the 'user' must be replaced with your userid & the path with the path to the example library.

**Comment by gr2m** [comment]
If you got the issue resolved, can you close it? And if not, you might want to move it to https://github.com/hoodiehq/hoodie-cli/issues
