### ISSUE TITLE
[hoodie.account] rename HoodieUnauthorizedError to HoodieUnauthenticatedError

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#359]
... because that's what it is. If the user is signed in correctly, she or he can always fetch the /_users doc, or change the password.

**Comment by svnlto** [comment]
Can you outline why we need to wrap errors within hoodie in new error?

/cc @boennemann

**Comment by gr2m** [comment]
https://github.com/hoodiehq/hoodie.js/blob/master/src/lib/error/error.js

**Comment by svnlto** [comment]
This explains 'what' it does but not really why we've decided to do it..

**Comment by gr2m** [comment]
we tried to normalize all errors in Hoodie, so we can at some point make a glossary of all the Hoodie errors. It also has some placeholder magic in the `message` property, where it replaces placeholders with the error's properties.

**Comment by svnlto** [comment]
> so we can at some point make a glossary of all the Hoodie errors.

This kind of makes sense, thanks for clarification.

**Comment by gr2m** [comment]
Irrelevant with new Hoodie
