### ISSUE TITLE
HTTP Request failed when tapping into Hoodie 

### ISSUE THREAD

**Issue by rr1000** [hoodiehq/hoodie#37]
```
MacBook-Air-2:~ rrichrs$ brew tap hoodiehq/homebrew-hoodie
Cloning into '/usr/local/Library/Taps/hoodiehq-hoodie'...
error: The requested URL returned error: 403 while accessing https://github.com/hoodiehq/homebrew-hoodie/info/refs
fatal: HTTP request failed
Ryans-MacBook-Air-2:~ rrichrs$
```

**Comment by janl** [comment]
Might be an intermittent error with GitHub, definitely works here. Can you just retry?

**Comment by rr1000** [comment]
@janl I retried and it worked the second time. Successfully installed hoodie but then received erros when starting hoodie. Figured it was an issue from the start so I wiped out the install and started fresh. Now I keep having this same error (HTTP request failed), which is what I think caused the later problem.

**Comment by janl** [comment]
I think the problems are unrelated. `brew tap` relies on github infra, if there is an issue, just try again.

the issue with the `hoodie start` error is likely a bug, I am investigating. Running `hoodie start` a second time just after the first fail _should_ work.

**Comment by gr2m** [comment]
@rr1000 I'm closing this ticket, thanks for bringing it up. If the problem is still there, could you please open a new ticket here: https://github.com/hoodiehq/hoodie-cmd/issues
