### ISSUE TITLE
error:unauthorized ?

### ISSUE THREAD

**Issue by donaldej** [hoodiehq/hoodie#375]
Hello,

I may have overlooked this, but how the heck do I capture when a user enters the wrong credentials?

**Comment by zoepage** [comment]
when the credentials are wrong, the promise get's rejected.
so you can grab that and work further ;)

**Comment by gr2m** [comment]
what @zoepage says :)

``` js
hoodie.account.signIn(username, password).fail(handleSignInError)
```

**Comment by donaldej** [comment]
I realized this as soon as I posted the question. Now I feel sheepish. I am still kind of new to promises so I keep failing to think of them.

**Comment by zoepage** [comment]
happens to all of us :)
enjoy your time!

**Comment by gr2m** [comment]
what @zoepage says ;)
