### ISSUE TITLE
Exception after create admin password

### ISSUE THREAD

**Issue by lucaslew** [hoodiehq/hoodie#38]
I'm not sure whether this is the correct sequence when starting hoodie app. I got the issue below, it asked to create a new "admin" password, then follow by an exception:

  $ hoodie start

> mynewapptest@1.0.0 start /Users/tslsf/project/hoodie/mynewapptest
> node node_modules/hoodie-app/lib/hoodie-app.js
> 
> Start local couch on port: 6004
> CouchDB Started
> hoodie server started on port '6003'
> Please set an admin password: admin
> undefined
> setup done
> 
> open http://mynewapptest.dev in your browser
> 
> starting: 'worker-users'
> initializing mynewapptest worker with: 
> { server: 'http://couch.mynewapptest.dev:80',
>   admin: { user: 'admin', pass: 'admin' },
>   persistent_since_storage: false,
>   name: 'users' }
> [users] [Setup] reading global config from modules/module/appconfig …
> All workers started.
> Your App is ready now.
> CouchDB stop triggered by exit
> 
> TypeError: Cannot read property '_id' of undefined
>     at new Response (/Users/tslsf/project/hoodie/mynewapptest/node_modules/hoodie-worker-users/node_modules/hoodie-worker/node_modules/cradle/lib/cradle/response.js:13:14)
>     at Request._onResponse [as _callback](/Users/tslsf/project/hoodie/mynewapptest/node_modules/hoodie-worker-users/node_modules/hoodie-worker/node_modules/cradle/lib/cradle.js:233:60)
>     at Request.self.callback (/Users/tslsf/project/hoodie/mynewapptest/node_modules/hoodie-worker-users/node_modules/hoodie-worker/node_modules/cradle/node_modules/request/index.js:142:22)
>     at Request.EventEmitter.emit (events.js:98:17)
>     at Request.<anonymous> (/Users/tslsf/project/hoodie/mynewapptest/node_modules/hoodie-worker-users/node_modules/hoodie-worker/node_modules/cradle/node_modules/request/index.js:856:14)
>     at Request.EventEmitter.emit (events.js:117:20)
>     at IncomingMessage.<anonymous> (/Users/tslsf/project/hoodie/mynewapptest/node_modules/hoodie-worker-users/node_modules/hoodienpm ERR! mynewapptest@1.0.0 start: `node node_modules/hoodie-app/lib/hoodie-app.js`

**Comment by janl** [comment]
Hi sorry, this is an issue in the worker setup code that snuck in there, I’m investigating. Can you confirm that just running `hoodie start` again works just fine?

**Comment by lucaslew** [comment]
Hi Jan, yes. I tried again and it works fine.
