### ISSUE TITLE
Custom storage adapter

### ISSUE THREAD

**Issue by jakecraige** [hoodiehq/hoodie#383]
I've noticed in the PR #382 y'all have started to make the storage async and potentially plugable. My company is very interested in using hood.ie but using localstorage is a potential large setback.

Does implementing something like localforage or a cordova sqlite adapter seem possible with the new setup? If so, I'd love to start a dialog and I could help to implement it, but I'd rather check if it's feasable first.

Ideally with PouchDB support it would do this automatically, but that seems a ways off still.

**Comment by jakecraige** [comment]
It looks like localForage just got support for custom adapters as well. It seems like implementing it in core would be a good step forward as it allows many adapters and even custom ones. [PR here](https://github.com/mozilla/localForage/pull/282) 

With it, users could use whatever database system they want in the browser and it's an open API if they want to implement something that isnt a.k.a cordova sqlite. 

This also takes the burden off of y'all having to make a pluggable store adapter for now as well. Since the switch to PouchDB is coming, there's no reason to implement that in hoodie so localforage seems like a good way until then.

Let me know what you think

**Comment by janl** [comment]
Our work is indeed to get in PouchDB and this is in fact the next major work item on the roadmap, so I’d say it makes little sense to shim in localForage in the meantime :)

**Comment by gr2m** [comment]
We have a version ready that uses PouchDB now:
https://github.com/hoodiehq/my-first-hoodie/tree/something-tracker#local-setup-to-test-new-hoodie
