### ISSUE TITLE
hoodie.request('GET', 'https://other-domain.com/path') sends bearer token

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#384]
This could potentially be a security issue. We should only send the Bearer token if it's on the same domain as hoodie.baseUrl

**Comment by lewiscowper** [comment]
Would the Bearer token need to be set at all on a domain that isn't hoodie.baseUrl?

**Comment by gr2m** [comment]
> Would the Bearer token need to be set at all on a domain that isn't hoodie.baseUrl?

No, if we send a request to an URL that doesn't match `hoodie.baseUrl`, we should not send the bearer token in the request header at all.

**Comment by andru** [comment]
I'm not sure how to assign this to me but I've been familiarising myself with `request` on #9 so I'd be happy to take this one.

**Comment by janl** [comment]
funny, I can’t seem to assign this to you either, but no worries, all yours! :)

**Comment by gr2m** [comment]
all yours, just assigned to me as a workaround :) Thanks Andru!

**Comment by gr2m** [comment]
not the case any more in new Hoodie
