### ISSUE TITLE
HTTP 401 Error, in admin view

### ISSUE THREAD

**Issue by echo66** [hoodiehq/hoodie#386]
When I open the dev tools in chrome or firefox, I see some 401 for this URL: http://127.0.0.1:6008/_api/app/config?_=<a number>

Such error occurs when I refresh the page or try to create an extra database per user.

**Comment by gr2m** [comment]
It's a known issue that was introduced with the bearer token support (instead of using cookies), and will soon be resolved. Problem is the usage of jQuery for requests, instead of `hoodieAdmin.request`.

**Comment by echo66** [comment]
Aye aye, gr2m. Thanks for the insight!
