### ISSUE TITLE
Precompiling hoodie.js ?

### ISSUE THREAD

**Issue by kfatehi** [hoodiehq/hoodie#388]
Hi I've just started playing around with hoodie.

I've created an app with hoodie-cli and it worked.

Next up I dockerized it by putting a Dockerfile in the generated `www` dir

``` dockerfile
FROM nginx
COPY . /usr/share/nginx/html
```

and built it with `docker build -t hoodie-www www`

and ran it with `docker run -p 8080:80 www`

Everything was swell, I expected the app to load up on `localhost:8080` and it did (nginx served it to my Chrome browser from inside the container)

I definitely did not expect it to find "the backend" (which I still am not sure how/where to specify the location) but I expected the app to work offline.

Instead I got this:

![dqiapq01bqpez-g8h7ggjm3agaygfakdb7hqrgndsd4](https://cloud.githubusercontent.com/assets/175305/4785796/d9413f5e-5d4a-11e4-9f7c-cfd24bae7c48.png)

So now I know about this magic path _api. Where can I learn more about it?

Is there a recommended way to precompile the library instead of referencing this path?

I haven't built my asset pipeline yet, but it will include Browserify w/ the React/JSX transform.

Thanks!

**Comment by gr2m** [comment]
Hoodie apps depends on `hoodie-server`. The `_api` is the rest API `hoodie-server` exposes. Without it, use the `hoodie.account` API in the browser, background tasks cannot be used, and data cannot be synced. 

The hoodie-server can also run at a different domain, it's CORS-enabled. So you can build your frontend app and host it at your preferred static host (gh-pages work, for example). And then setup your hoodie-server somewhere else. You can also look into appback.com, they are the first to offer Hoodie hosting.

Any farther questions?

**Comment by kfatehi** [comment]
Ok thank you, no questions right now -- I'm sure I'll have more later.
