### ISSUE TITLE
Make the GitHub link more prominent

### ISSUE THREAD

**Issue by dandv** [hoodiehq/hoodie#389]
Some sort of "Form me" banner would be great. Right now I've spent more than a minute checking out the site after the [Meteor 1.0 announcement mentioning hoodie](https://news.ycombinator.com/item?id=8523636), without finding the GitHub link. Had to Ctrl+F for it :)

**Comment by gr2m** [comment]
We are working on a new website that will resolve that, and it's due soon™, so we will leave it this time. But really appreciate you took the time to report that. Hope you like Hoodie :)
