### ISSUE TITLE
Error when doing "hoodie start" on fresh project

### ISSUE THREAD

**Issue by rosemarydotworld** [hoodiehq/hoodie#39]
I followed the [installation instructions](http://hood.ie/#installation) and started a project with "hoodie new". I cd'd into the directory and tried "hoodie start". Here's the terminal [output](https://gist.github.com/anonymous/5341760).

I confirmed local-tld is running re: http://twitter.com/hoodiehq/status/321415285519298560

I'm really excited about the project, so I hope you can help me out. :thumbsup:

**Comment by vetri02** [comment]
Even I have got the same issue. See output here http://pastebin.com/9JB7kVKY

**Comment by janl** [comment]
Yeah, this seems to be a bug in the worker setup thing that snuck in last minute. I’mma dig in there now.

Can you confirm that when you run `hoodie start` a second time, it all works?

**Comment by rosemarydotworld** [comment]
@janl Unfortunately, it doesn't seem to matter how many times I run `hoodie start`.

I did `npm list` within my hoodie app's directory and found the following: https://gist.github.com/liamdanger/5352054

Hope this helps!

**Comment by janl** [comment]
What happens if you run `npm install` in your app’s directory and try `hoodie start` again?

**Comment by sander** [comment]
Just tried, it pulled some new dependency versions but still gives this error: http://pastebin.com/SMw6g2hj

**Comment by janl** [comment]
Can you paste the contents of these files?

```
~/Library/Hoodie/Apps/projectname/couch.log
~/Library/Hoodie/Apps/projectname/couch.stdout
~/Library/Hoodie/Apps/projectname/couch.stderr
```

**Comment by sander** [comment]
Here are the files in that folder, no couch.log exists. https://gist.github.com/sander/5407456

**Comment by janl** [comment]
ok, I will try and get this reproduced on a virtual machine, thanks!

**Comment by sander** [comment]
Hoodie started working on my pc after reinstalling Homebrew to the default /usr/local prefix.

**Comment by gr2m** [comment]
Closing this ticket. If you still have problems, feel free to open a new issue at https://github.com/hoodiehq/hoodie-cmd/issues
