### ISSUE TITLE
hoodie stops loading documents when a document id is not in the expected format, without telling you which doc id

### ISSUE THREAD

**Issue by thomasvs** [hoodiehq/hoodie#390]
On loading all docs, if the doc id is not in the format something/somethingelse, hoodie errors out.  It doesn't print on the console which id - it just fails in the line that says

object.type = matches[1], object.id = matches[2]

In addition, it fails even if that wrong doc id is deleted - which imo hoodie should just skip.

**Comment by gr2m** [comment]
I agree, it's a known issue that we just silently ignored, as migrating to PouchDB will resolve it anyway. We started to work on the PouchDB migration if you like to give a hand: https://github.com/hoodiehq/wip-hoodie-store-on-pouchdb

**Comment by thomasvs** [comment]
I think the severity is more than confusing.  In essence, if this happens, you don't get to see all the data that was not synced to local storage after hitting this exception.  This means that to the user the data is effectively inaccessible.

**Comment by thomasvs** [comment]
Here is a fix that works for me: https://github.com/thomasvs/hoodie.js/tree/issue-390

**Comment by gr2m** [comment]
The new hoodie does not require the `type/id` format any more.
