### ISSUE TITLE
hoodie.account.sign_up should sign_out first

### ISSUE THREAD

**Issue by espy** [hoodiehq/hoodie#4]
Calling sign_up() while a user is already logged in returns a 404 and throws an error. 

Expected behavior would be to sign out the current user and then seamlessly sign up the new one.

**Comment by gr2m** [comment]
I'm not quite sure what the correct behavior should be in a situation, when a user is currently signed in and then signs up for a new account. I could sign the user out in case he's signed in before doing the signUp, but that would flush all the local data, I'm not sure if that could lead to any problems.

My suggestion would be to prevent a user from signing up when he is currently signed in, returning an error. I think for a normal app, this shouldn't happen anyway.

What do you think?

**Comment by gr2m** [comment]
closing this for now, let me know if you think we should change the behavior
