### ISSUE TITLE
hoodie.store.add does not accept capital letters in id

### ISSUE THREAD

**Issue by wajerrr** [hoodiehq/hoodie#400]
While having a go with Hoodie I have discovered that it does not accept capital letters in properties ids,
it throws a generic error only. It might takes a while to figure it out if you have UUID generator for ids.
hoodie.store.add('task', {
    title: 'build sweetMasterApp tomorrow.',
    id:'IWILLTHROWERRORID'
  });

As well task does not accept '-' in the names of task 
i.e.
hoodie.store.add('task-list-uuid', {
    title: 'build sweetMasterApp tomorrow.',
    id:'uuid',
  });
will throw the same error.
Which is a not a big deal but... as those limitations are not mentioned in documentation. It takes a bit of time to figure it out.

**Comment by gr2m** [comment]
yes, you're not the first to run into this. We'll get rid of some of the restrictions soon, and will make sure to document the others. I'll leave the issue open as a reminder

**Comment by janl** [comment]
Possibly related: https://github.com/hoodiehq/hoodie.js/issues/421

**Comment by gr2m** [comment]
new hoodie.store API now accepts capital letters and `-`
