### ISSUE TITLE
log uncaught exceptions once hoodie.log is available

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#401]
follow up for https://github.com/hoodiehq/hoodie.js/pull/376

Dreamcode for `hoodie.log`

``` js
hoodie.log("ohaj!")
// (hoodie) ohaj!
hoodie.log.info("This might be of interest. Or not.")
// (hoodie:info) This might be of interest. Or not.
hoodie.log.warn("Something is fishy here!")
// (hoodie:warn) Something is fishy here!
hoodie.log.error("oooops")
// (hoodie:error) oooops
```

The for message would use `window.console` internally, the for `hoodie.log` methods would work as their `window.console` counterparts.

**Comment by gr2m** [comment]
I'd like a default log style like this:

``` js
colors = {
  log: 'grey',
  info: '#2A53CD',
  warn: '#F4BD00',
  error: '#E13438'
}
'log info warn error'.split(' ').forEach(function(type) {
  console[type]('%choodie%c' + type, 'font-size: .8em; color: white; padding: .2em .5em; margin-right: .5em; border-radius: 1em; background-color:' + colors[type], 'color: inherit')
})
```

![console output](https://cloud.githubusercontent.com/assets/39992/5888869/123e2410-a40f-11e4-8b3e-94154dd3a56a.png)

Not sure about cross browser support though. I tested it in latest Chrome / FF / Safari on Mac and it works

**Comment by janl** [comment]
prrretty!

**Comment by NickColley** [comment]
I'd leave the font-size, as is for accessibility reasons.

(Looks cute tho' :D)

**Comment by NickColley** [comment]
Also https://www.npmjs.com/package/debug for inspiration

**Comment by gr2m** [comment]
Yeah I just looked in to debug, it's a different use case though, there is no differentiation in log levels, it's all debug. I think for our target group, it'd be good to show warnings & errors by default, but hide info, and always show log

But I'm open to be convinced otherwise

**Comment by gr2m** [comment]
implementing the log API here: https://github.com/hoodiehq/hoodie-client-log

**Comment by varjmes** [comment]
Oh this is cool, I will keep a close eye on `hoodie-client-log`. A nice small API I can surely learn from!

**Comment by gr2m** [comment]
This is now part of new Hoodie \o/
