### ISSUE TITLE
Cannot use the hoodie playground sample app

### ISSUE THREAD

**Issue by idanb11** [hoodiehq/hoodie#405]
Hi all,

I followed all the steps described in the Hood.ie docs and created the sample app.
Starting the hoodie server was not a problem.
When I try to sign-up in hoodie playground sample app - I get the following error in the console:
`Unhandled promise rejection Promise {_isHoodiePromise: true, done: function, fail: function, always: function, progress: function…}_isHoodiePromise: true_progressCallbacks: Array[0]always: function always(callback) {catch: function catch_(error) {done: function done(callback) {fail: function fail(callback) {progress: function progress(callback) {then: function (onResolve, onReject) {__proto__: Promise[[PromiseStatus]]: "rejected"[[PromiseValue]]: HoodieErrorconstructor: function HoodieError(properties) {arguments: nullcaller: nulllength: 1name: "HoodieError"prototype: Error__proto__: function Empty() {}<function scope>message: ""_design" is invalid object type. lowercase letters, numbers and dashes allowed only. Must start with a letter."name: "HoodieObjectTypeError"rules: "lowercase letters, numbers and dashes allowed only. Must start with a letter"stack: (...)type: "_design"__proto__: Error`

I'm using Apache CouchDB 1.6.1

Please help resolving this issue...

Idanb11

**Comment by gr2m** [comment]
These are warnings, not errors. You can ignore them, we'll get rid of the `Unhandled promise` soon, sorry for the inconvenience

**Comment by idanb11** [comment]
@gr2m - thanks for your feedback.

I'm not sure that this is only a warning since this part is related to creating '_design/permissions',
which control the access to the CouchDB - which in turns causes to my sample hoodie app not to have access to the DB - hence the errors i reported above.

**Comment by idanb11** [comment]
When enter the Admin Dashboard and go to users tab - http://127.0.0.1:6005/#plugin/users 
I get the following error:
`GET http://127.0.0.1:6005/_api/plugins/_changes?include_docs=true&since=0 401 (Unauthorized)vendor.js:5 ab.ajaxTransport.Z.cors.a.crossDomain.sendvendor.js:5 ab.extend.ajaxadmin-dashboard.js:1 badmin-dashboard.js:1 w.requestadmin-dashboard.js:1 w.pulladmin-dashboard.js:1 w.bootstrapadmin-dashboard.js:1 w.connectadmin-dashboard.js:1 cadmin-dashboard.js:1 b.extendadmin-dashboard.js:1 cadmin-dashboard.js:2 (anonymous function)admin-dashboard.js:2 42.../../../helpers/namespaceadmin-dashboard.js:1 eadmin-dashboard.js:1 (anonymous function)admin-dashboard.js:3 86../components/admin-dashboard/entities/adminEntityadmin-dashboard.js:1 eadmin-dashboard.js:1 aadmin-dashboard.js:1 (anonymous function)`

**Comment by gr2m** [comment]
Hmmmmm what system are you on? Could you try the following?

1, In your app's folder: `rm -rf ./data`
2. Make sure no extra CouchDB process is running in the background
3. Make sure you have the latest `hoodie-server` and `hoodie-plugin-users` installed
4. `hoodie start`

If that all doesn't help. Maybe you can give me access to your app's code? Happy to help! We can also pair on fixing this if you like, always glad to get in touch with the community :)

**Comment by idanb11** [comment]
closing this one.
