### ISSUE TITLE
Apache License

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#406]
review (or remove?) the file at:
https://github.com/hoodiehq/hoodie.js/blob/master/LICENSE

I references CouchDB modules like jQuery, we don't use them at all. I don't actually know where all this comes from, to be honest.

---

Thanks @garbas for bringing this to our attention

**Comment by zoepage** [comment]
+1 on review

**Comment by zoepage** [comment]
@gr2m thinking about another license? if not, I'd review and remove the things like jQuery. :)

**Comment by janl** [comment]
Apache 2 is the license, we just need to get the dotfiles update committed: https://github.com/hoodiehq/hoodie-dotfiles/blob/master/static/LICENSE @boennemann (wasn’t that supposed to happen automatically somehow?)

**Comment by gr2m** [comment]
fyi the current [LICENSE] file still references jQuery and other modules that we don't use
