### ISSUE TITLE
Could not start hoodie

### ISSUE THREAD

**Issue by ramstein74** [hoodiehq/hoodie#417]
hello i get this error when running on my windows 7

Could not start hoodie

i have 
version: 0.6.3 (node V0.10.26 npm 2.6.0 platform:win32)

help please

**Comment by janl** [comment]
can you show us the steps you are doing that lead to the error message?

**Comment by zoepage** [comment]
Please try:

```
npm cache clean
npm update hoodie-cli -g
hoodie start
```

**Comment by ramstein74** [comment]
after npm cache clean i get another error

ENOENT, no such file or directory
c:\users.........\app1\data\couch.pid'
at Object.fs.openSync (fs.js:427:18)

Help please

António

2015-02-24 13:09 GMT+00:00 Ola Gasidlo notifications@github.com:

**Comment by zoepage** [comment]
Hey @ramstein74!
Please take a look here: http://faq.hood.ie/#/question/40800762

This should fix your problem. If not, ping me :)

**Comment by ramstein74** [comment]
Not fixed.
Anymore ideas ?

is couchdb the problem ?

2015-02-24 15:03 GMT+00:00 Ola Gasidlo notifications@github.com:

**Comment by janl** [comment]
can you show us the steps you are doing that lead to the error message?

**Comment by ramstein74** [comment]
the steps

hoodie new app1
cd app1
hoodie start

2015-02-24 15:45 GMT+00:00 Jan Lehnardt notifications@github.com:

**Comment by janl** [comment]
how did you install CouchDB?

**Comment by ramstein74** [comment]
from here
http://www.us.apache.org/dist/couchdb/binary/win/1.6.1/setup-couchdb-1.6.1_R16B02.exe

2015-02-24 15:48 GMT+00:00 Jan Lehnardt notifications@github.com:

**Comment by Junkern** [comment]
The issue still persists, as I am encountering it. See also https://github.com/hoodiehq/faq/issues/119#issuecomment-155823956

**Comment by Junkern** [comment]
Ok, now it works. I think the problem was, that I did not install CouchDB in the default directory (C:...). Maybe hoodie has problems with CouchDB being in a different directory?

**Comment by janl** [comment]
Yes, that’s the problem very likely!

This is the culprit: https://github.com/hoodiehq/node-multicouch/blob/master/lib/multicouch.js#L17

If anyone fancies making this more dynamic, please let us know!

We are tracking existing efforts here: https://github.com/hoodiehq/node-multicouch/issues/26

Closing this in favour of that one.

**Comment by timurgepard** [comment]
Install x86 version. It works well
