### ISSUE TITLE
npm/browserify?

### ISSUE THREAD

**Issue by max-mapper** [hoodiehq/hoodie#42]
can I do this?

``` js
var hoodie = require('hoodie')
```

my dev workflow is here: https://gist.github.com/maxogden/5147486

i'm basically trying to figure out how to split my hoodie app up into many node modules and use `beefy` as the dev server, rather than the built in `hoodie start`

**Comment by janl** [comment]
`hoodie start` starts more than the static web server, but you can serve your static HTML from any server as long as you `hoodie start` and use the api.maxapp.dev domain.

I don't know about require() but we are happy to make any required (heh) changes.

**Comment by max-mapper** [comment]
cool, didn't realize I could roll my own static server and it would work fine. CORS won't be an issue?

to fix the module part you need a package.json + publish hoodie.js to https://npmjs.org/hoodie

**Comment by janl** [comment]
api.maxapp.dev is fully CORSified :)

**Comment by gr2m** [comment]
ehhm, question: hoodie.js is a frontend only library. You can install it with [bower](http://twitter.github.io/bower/). Are npm modules not for nodeJS libs only?

**Comment by max-mapper** [comment]
npm is for javascript, a lot of people use tools like
http://browserify.org/to use npm for client side only dev

**Comment by janl** [comment]
Since hoodie is a bunch of things, what would be a good practice for naming this? `hoodie-client` comes to mind to avoid confusion with other modules that are hoodie, as well as the Hombrew package that is a CLI tool `hoodie`.

**Comment by max-mapper** [comment]
I would just call it hoodie since that is simple and available

**Comment by janl** [comment]
There are other things that are also hoodie that are different parts of our system that are likely to be on NPM sooner or later. I don’t want to mess this up. e.g. maybe folks expect `npm install hoodie` to install the whole shebang, (like `brew install hoodie` does currently, I don’t know. I just want to try and avoid confusion down the road.

**Comment by max-mapper** [comment]
Ah well I can't speak to your product roadmap but either way you should park hoodie for now

**Comment by janl** [comment]
Heh, “product” :D

Thanks for your feedback!

**Comment by janl** [comment]
I made up my mind. Let's use `hoodie`  for the client library. And the other parts can be `hoodie-server` and so on.

Cheers

## Jan

**Comment by max-mapper** [comment]
:D

to clarify my viewpoint a bit: I view chrome, firefox, node and internet
explorer (and all the others) as different platforms for portable
javascript. things that should conceptually work in a client side JS
environment (without a DOM) _should_ also work in node and things that just
do JS I/O in a way that browsers are capable of _should_ work in both
places.

I was having a similar discussion recently with a voxel.js module author
who wrote a module for reading minecraft binary level files in node, and I
was really interested in making it work in the browser too.

It was written in a way that was not portable -- traversing folders and
reading files with node's `fs' module. a portable version would involve to
separating the reading from the processing... so you can use XHR/FileReader
in a browser and`fs` in node and end up at the same point: you have a
typed array full of data that you need to parse, since those algorithms
will be the exact same since most of JS is identical on most platforms

**Comment by janl** [comment]
Woot, thanks, so happy to learn from your experiences <3!

**Comment by gr2m** [comment]
fyi still npm-publishing, internet is very bad here ...

I really like the case you brought up. If I don't get it wrong, it totally fits to what exites me about hoodie. You could just make a JS module, that has the same API, but in the backend it's implemented in a entirely different way then in the frontend, where it uses XHR or what ever. As long as the API of the module is async, possibilities are endless. Implementations could even differ for different browsers etc. Happy to discuss that farther
