### ISSUE TITLE
Filterfunction for .findAll() does not work

### ISSUE THREAD

**Issue by nschwa** [hoodiehq/hoodie#422]
Passing in a function as described [here](http://faq.hood.ie/#/question/50709102)  to the `findAll` method does not work correctly.
All objects are passed to the `done` handler.
Tested with Version: 0.6.3 (node v0.12.0, npm 2.5.0, platform: darwin)  
_Example:_

``` javascript
petStore.findAll(function(pet) {
  //  id is unique
   return pet.id === 's1ejgi9'
}).done(function(pet) {
  console.log(pet);
  // [Object, Object, Object]
  // 0: Object
  // 1: Object
  // 2: Object
})
```

Regards, 
Nils

**Comment by svnlto** [comment]
I believe `findAll` filters using the `type` attribute on the doc. But you're right, this seems like a bug to me.

**Comment by nschwa** [comment]
@svnlto sorry I don't know exactly what you mean with the 1st part of your comment. The `type` has been defined before by `var petStore = hoodie.store('pets')`.

**Comment by zoepage** [comment]
Like I understood it, you'll get all types by `findAll`and would filter them in the success event of the promise...

**Comment by nschwa** [comment]
Yeah, but that means to retrieve the whole set of data and filtering then. I thought it's possible to request only a subset from the DB.

**Comment by zoepage** [comment]
Right. Always thought this is just possible in the promise...

**Comment by nschwa** [comment]
@ola I think you're right. That seems due to the constraints of `localStorage`, right? In `indexedDB` for example you can define an index for a key and a range for the values to request. You then only get the subset of data matching the given range. Which seems to be more efficent than to filter the whole result within an array. So let's wait for the implementation of `PouchDB` in hoodie.

**Comment by zoepage** [comment]
@nschwa exactly.

working on it ;)

**Comment by gr2m** [comment]
closing in favor of https://github.com/hoodiehq/pouchdb-hoodie-store/issues/44
