### ISSUE TITLE
Force Gzip

### ISSUE THREAD

**Issue by janl** [hoodiehq/hoodie#423]
This is the frontend counterpart to https://github.com/hoodiehq/hoodie-server/pull/349.

Before I can prepare a PR,  I need some guidance with how this fits into hoodie.js best.

First off, I think this should _not_ be a plugin, as this is useful for all apps and should be built-in.

I also acknowledge that this code does DOM manipulation, which hoodie.js (afaik) does’t do yet, so we need to make sure this is absolutely fail-safe.

If we can’t make it fail-safe, we need to wrap this in a `hoodie.enableForcedGzip()` method that developers have to call themselves (or with `new Hoodie({force_gzip: true})` or something, it doesn’t matter at this point :).

This is the code that we need to be running:

``` javascript
      // Check for a cookie.
      // If absent, set a session cookie saying “compression NOT ok”.
      // Write out an iframe element to the page.
      if(document.cookie.indexOf('hoodie_force_gzip') === -1) {
        document.cookie = 'hoodie_force_gzip=false';
        var bodyTag = document.getElementsByTagName('body')[0];
        var insertingIframe = document.createElement('iframe');
        insertingIframe.src = '/_api/_files/force-gzip.html?gzip=force';
        bodyTag.appendChild(insertingIframe);
      }
```

More background here: http://www.stevesouders.com/blog/2010/07/12/velocity-forcing-gzip-compression/

cc @gr2m @zoepage

**Comment by gr2m** [comment]
I feel like we can just force gzip for all. All browsers who support Hoodie today (IE9+) support gzipped content. Maybe we can give this a try on one of our apps first, as it would need much less added complexity, and only on the backend? We could use a ENV variable like `HOODIE_HTTP_FORCE_COMPRESSION=true` or similar?

**Comment by gr2m** [comment]
We discussed with @janl today. What we'll do now is the following:
1. send the initial bootstrap request with `?force_gzip=true`, the server will always respond with a gzip response, no matter the accept http header
2. if parsing the response fails, we will send another request without the `?force_gzip=true` query param

That should do, simple

**Comment by janl** [comment]
One addition: when the failed request comes back, we should look if it is a gzip response (if we can), so we can differentiate between e.g. broken JSON and gzipped content.
