### ISSUE TITLE
Resolve signup flow when user is unconfirmed.

### ISSUE THREAD

**Issue by mikehedman** [hoodiehq/hoodie#426]
Currently, if a plugin flags a user as unconfirmed, there is no notification to the client that the signup flow has been interrupted (for example, to require to click on a link in a verification email).  With the current behavior, delayedSignIn() just loops forever.

Scope: This issue is to narrowly address the creation of that client notification.  Issue #24 addresses a larger issue, and will be taken up as part of the Milestone 1 effort.

@gr2m and I have been discussing this issue, and I hope to be submitting a PR to resolve it once a strategy has been decided upon.

**Comment by gr2m** [comment]
For more background, this issue will be resolved proper as part of https://github.com/hoodiehq/hoodie.js/issues/24 / https://github.com/hoodiehq/discussion/issues/47.

For the time being, I've an idea:
1. Use the `.progress` callback on `signUp(username, password)` to replace the form with the "check your emails" message. It will keep checking if the account has been confirmed in the background, but that's ok.
2. When the user clicks on the link in the email, just show a message: "Your account has been confirmed, you can close this tab now". 
3. Meanwhile, the`signUp(username, password)` in the first tab will resolve, and you can replace the "check your emails" message with something like "thanks for signing up! `[close]`"

Would that work for you?

**Comment by mikehedman** [comment]
@gr2m - that worked great.  I'll close this up in deference to #24.

**Comment by gr2m** [comment]
awesome, glad to hear that :ok_hand:
