### ISSUE TITLE
HoodieObjectIdError message doesn't explain ID naming restriction

### ISSUE THREAD

**Issue by skibz** [hoodiehq/hoodie#427]
example:

``` js
hoodie.store.findOrAdd(
    'account',
    'abc@123.com', 
    {id:'abc@123.com', abc: 123}
).done(
    console.log.bind(console)
).fail(
    console.error.bind(console)
);
```

results in:

``` js
HoodieError {
    id: "abc@123.com",
    name: "HoodieObjectIdError",
    message: "'abc@123.com' is invalid object id. undefined."
}
```

`HoodieError.message` should also contain:

> `@` or `.` characters are disallowed.

**Comment by gr2m** [comment]
Thanks @skibz, that's a good one! I'll leave it open for reference for the implementation of the new `hoodie.store` API

**Comment by gr2m** [comment]
closing in favor of https://github.com/hoodiehq/pouchdb-hoodie-api/issues/80
