### ISSUE TITLE
Invalid sessions 

### ISSUE THREAD

**Issue by mmichelli** [hoodiehq/hoodie#428]
["to figure out whether the current user is still authenticated towards the backend, hoodie.account.authenticate is being run in the Hoodie constructor, which sends a GET /_api/_session requests and determines based on the response, if the user is still unauthenticated."](https://github.com/hoodiehq/hoodie.js/issues/305)

[But this just raises an error 
 state.events.trigger('error:unauthenticated');](https://github.com/hoodiehq/hoodie.js/blob/a7d5ffad648e40ebffb89cd37439a56556721996/src/hoodie/account/helpers.js#L91)

Shouldn't we be calling config.clear(), removing the config, i.e username + bearerToken

**Comment by mmichelli** [comment]
This works for me: 

``` javascript
 hoodie.account.on('error:unauthenticated', function() {
        utils.config.clear();
    })
```

**Comment by gr2m** [comment]
@mmichelli I would not recommend to do that. `"unauthenticated"` means the user is still signed in locally, and might have local changes that are not yet synced. What you usually want to do is to tell the user that her / his session ended, and that she / he needs to sign in again. Once the user signs in again, all things will get back to normal.

Does that make esnse?

**Comment by gr2m** [comment]
Let me know if you have any farther questions here

**Comment by mmichelli** [comment]
thanks, I ended up with the above solution. :)
