### ISSUE TITLE
list of all events

### ISSUE THREAD

**Issue by max-mapper** [hoodiehq/hoodie#43]
things like `.on('authenticated')` don't show up on http://hood.ie/ or in the hoodie.js readme right now

**Comment by gr2m** [comment]
@espy could you look into this?

**Comment by espy** [comment]
Will do, but not today :)

**Comment by espy** [comment]
Added authenticated and unauthenticated. Any others I should add?

**Comment by gr2m** [comment]
You can also add "signin", "signup" and "signout". Note that "signin" gets triggered after "signup" as well.

**Comment by espy** [comment]
Done, I'll close this for now.
