### ISSUE TITLE
Fails on Windows

### ISSUE THREAD

**Issue by janl** [hoodiehq/hoodie#431]
node 4.1 / npm 2.x

npm install throws:
![screen shot 2015-09-18 at 17 49 33](https://cloud.githubusercontent.com/assets/11321/9964505/f2bd4184-5e30-11e5-8c69-7c382c2347a7.png)

`./node_modules/.bin/hoodie`:
![screen shot 2015-09-18 at 17 48 19](https://cloud.githubusercontent.com/assets/11321/9964520/1004f606-5e31-11e5-8715-42bfaee100aa.png)

**Comment by gr2m** [comment]
Tested in Win 7 with latest Node.js LTS (v.4.4.4) and npm v2.15.1 and it works now. The only problem is that levelDB did not install because it requires python, but Hoodie starts when run in memory
