### ISSUE TITLE
'authenticated' event fires multiple times

### ISSUE THREAD

**Issue by max-mapper** [hoodiehq/hoodie#44]
when I have a `hoodie.account.on('authenticated'` listener it calls the callback 3 times when I do `hoodie.account.authenticate`

**Comment by gr2m** [comment]
Hey Max, I'm gonna look into this after front trends, sorry it takes so long

**Comment by gr2m** [comment]
btw, there is also a `signin` event. Could you describe your use case? Maybe there's a better way, but I'll look into this anyway

**Comment by max-mapper** [comment]
here is the code I have:

``` js
hoodie.account.authenticate().then(function noop(){}, isLoggedOut)

hoodie.account.on('authenticated', isLoggedIn)
hoodie.account.on('signout', isLoggedOut)
```

this works okay but it would be better if .on('authenticated') only fired
once and not 3 times. maybe there is a .on('unauthenticated') or a
.on('signin') ?

**Comment by gr2m** [comment]
here's a list of account events (please give feedback if you'd suggest a name change, now is the time ;-):
- `authenticated`
- `cleanup`
- `error:unauthenticated`
- `password_reset:error`
- `passwordreset`
- `signin:anonymous`
- `signin`
- `signout`
- `signout`
- `signup:anonymous`
- `signup`

I'd do the following:

``` js
hoodie.account.authenticate().then(isLoggedIn, isLoggedOut) 
hoodie.account.on('signin', isLoggedIn)
hoodie.account.on('signout', isLoggedOut)
```

The reason why you get the `authenticated` event multiple times is that Hoodie does run `hoodie.account.authenticate()` itself on startup. But I wonder why you get it 3 times, not twice

**Comment by max-mapper** [comment]
ah so my dilemma is:

when the app starts up it will trigger .on('authenticated') a bunch of
times so I don't use these:
- hoodie.account.on('authenticated', isLoggedIn)
- hoodie.account.authenticate().then(isLoggedIn, isLoggedOut)

but if I rely on .signIn/.signOut it will only trigger when the user
signsIn and not when they are already signed in (when the page first loads)

so, this is why I do this (now with more comments):

```
// check if we are authenticated, but ignore the success callback because
hoodie.account.on('authenticated') is already going to fire
// if we aren't authenticated this is the only way AFAIK that I can get a
callback to fire so I can show the 'you are signed out' UI
hoodie.account.authenticate().then(function noop(){}, isLoggedOut)

// ideally this would only fire once. I have had to change my code so that
it assumes it fires multiple times though
hoodie.account.on('authenticated', isLoggedIn)

// this catches when the user clicks the signout button, but IMO a nicer
solution would be to have hoodie.account.on('unauthenticated') or something
that pairs better with .on('authenticated'). The reason being that I have
no reason to use hoodie.account.on('signin') here since
.on('authenticated') will fire when you sign in AND when you are already
signed in (which is that I want)
hoodie.account.on('signout', isLoggedOut)
```

**Comment by gr2m** [comment]
your comment again for better readablity, dunno what's happening with @github

---

ah so my dilemma is:

when the app starts up it will trigger .on('authenticated') a bunch of
times so I don't use these:
- hoodie.account.on('authenticated', isLoggedIn)
- hoodie.account.authenticate().then(isLoggedIn, isLoggedOut)

but if I rely on .signIn/.signOut it will only trigger when the user
signsIn and not when they are already signed in (when the page first loads)

so, this is why I do this (now with more comments):

```
// check if we are authenticated, but ignore the success callback because
hoodie.account.on('authenticated') is already going to fire
// if we aren't authenticated this is the only way AFAIK that I can get a
callback to fire so I can show the 'you are signed out' UI
hoodie.account.authenticate().then(function noop(){}, isLoggedOut)

// ideally this would only fire once. I have had to change my code so that
it assumes it fires multiple times though
hoodie.account.on('authenticated', isLoggedIn)

// this catches when the user clicks the signout button, but IMO a nicer
solution would be to have hoodie.account.on('unauthenticated') or something
that pairs better with .on('authenticated'). The reason being that I have
no reason to use hoodie.account.on('signin') here since
.on('authenticated') will fire when you sign in AND when you are already
signed in (which is that I want)
hoodie.account.on('signout', isLoggedOut)
```

**Comment by max-mapper** [comment]
ah weird, that was written from gmail, usually that works

**Comment by gr2m** [comment]
The `authenticate()` method is only to also check the user session that needs to be valid for the sync.

The `unauthenticated` event (currently called `error:unauthenticated`) does not only get fired when a user signes out, but also when for whatever reason the backend said that the session is not valid anymore, e.g. session timeout. In this case, the user is still signed in, but his/her data is not synced to remote.

So, my suggestion would be, simply check if the user is currently logged in without checking the session:

``` js
if (hoodie.account.username) {
   // user is logged in
} else { 
   // user is not logged in
}
```

and then, handle only the events when a user intentionally signes in or out, with

```
hoodie.account.on('signin', isLoggedIn)
hoodie.account.on('signout', isLoggedOut)
```

And then, there is the case when a user is signedIn as hoodie.account.username is set, but the session is not valid anymore. To handle that event, you can subscribe to

```
hoodie.account.on('error:unauthenticated', handleUnauthenticated)
```

does that make sense?

**Comment by max-mapper** [comment]
Ahhhhh, I see. I'll fix my code. Thanks! BTW I stole my code from a readme
somewhere so maybe putting these two lines next to eachother in the 'hello
world' examples would help clarify:

```
var hoodie  = new Hoodie()
console.log(hoodie.account.username)
```

**Comment by gr2m** [comment]
Yeah, great idea, cheers! I've made an extra ticket to clarify things in general.
