### ISSUE TITLE
client SDKs for iOS and Android

### ISSUE THREAD

**Issue by Rajan** [hoodiehq/hoodie#448]
I was considering loopback.io and ran into Hoodie, which looks great.
Are there iOS/android SDKs for hoodie to be more useful to build mobile apps.

**Comment by gr2m** [comment]
Hey @rajan, there were iOS/Android SDKs in the works, but they have never been fully finished. We are about to release a new Hoodie version which will bring new APIs, it will be a good time to create an SDK if you’re intersted

**Comment by Rajan** [comment]
Thank you for support @gr2m . I'm still exploring frameworks which are scalable+open-source for a real-time video sharing app that i'm planning to build. If hoodie will serve the purpose, happy to build iOS/Android sdks.

**Comment by Rajan** [comment]
Question: If there isn't offline-first + realtime-sync for mobile apps, it won't be as great to build mobile apps with. What would be the effort involved in building offline-first iOS library in Swift? If you can offer some guidelines, that'd be useful.

**Comment by gr2m** [comment]
Hoodie in it’s core has an account & a store module. 

The JavaScript SDK for account looks like this:
https://github.com/hoodiehq/hoodie-client-account#api

It wraps this RESTFul JSON API:
http://docs.accountjsonapi.apiary.io/#

For store, the JavaScript SDK looks like this:
https://github.com/hoodiehq/hoodie-client-store#api

It wraps a [CouchDB](http://couchdb.apache.org/) for which there likely already exist libraries.

Besides that, there is a [Task API](https://github.com/hoodiehq/hoodie-client-task#api) and the JavaScript API / REST API will be extended-able with plugins.

Hope that helps?

**Comment by Rajan** [comment]
Thank you for the ideas and quick response. I explored possibilities of building it for mobile and it seems like it's a significant project as these guys are building it: www.telepat.io .. will explore more and take a call in 1-2 weeks.

**Comment by gr2m** [comment]
Hey @Rajan, if you are still interested to get involved, we have a new Hoodie release coming up with well defined REST APIs for account & store functionality. Happy to chat on how an Android client could look like for the new Hoodie, ping me here or in our [Hoodie Chat](http://hood.ie/chat/) `@gregor`
