### ISSUE TITLE
[next] getting new Hoodie to work on Windows

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#449]
@toh82 tried to get the new Hoodie work on Windows, but keeps running into problems

Can someone on Windows try to help? Follow the instructions here:
https://github.com/hoodiehq/my-first-hoodie/tree/something-tracker#local-setup-to-test-new-hoodie

**Comment by janl** [comment]
what “problems”?

**Comment by janl** [comment]
> @gregor: actionable item: someone with windows follow setup instructions and see if it works

I’m happy to set up an EC2 instance with windows for anyone who wants to debug, just get in touch here.

**Comment by toh82** [comment]
@janl the problems were all related to missing dependencies, in the first step it was 
`Error: Cannot find module 'are-we-there-yet'` from npmlog module, then after i installed it, it was missing python.

but as mentioned in slack `npm install --no-optional` solves these issues.

**Comment by gr2m** [comment]
I’ll close this for now, we will re-open or create a follow up issue once we plan to support PouchDB with levelDB as a drop-in replacement for CouchDB. Thanks @toh82
