### ISSUE TITLE
undefined errors in account.signIn if XHR error

### ISSUE THREAD

**Issue by max-mapper** [hoodiehq/hoodie#45]
if `api.appname` isn't reachable you get `undefined` error message in the signIn callback, probably other callbacks as well

![Screen Shot 2013-04-18 at 9 16 12 AM](https://f.cloud.github.com/assets/39759/397642/4fe82ba4-a843-11e2-8516-868fa4659071.png)

**Comment by janl** [comment]
+1, seeing this as well and got a report on IRC.

**Comment by gr2m** [comment]
apparently, nodejitsu broke it with their load balancer update. They say they work on it. Since 2 days now. All Jan told me. A bit frustrating :-/

**Comment by max-mapper** [comment]
ah that sucks. it should still give a proper XHR error though

**Comment by gr2m** [comment]
you mean the cors errors? I see these 
![screenshost](http://f.cl.ly/items/3c1Z2Y3I27371V3D2X1f/Image%202013.04.19%2023%3A06%3A01.png)

**Comment by max-mapper** [comment]
Yea the hoodie code should return an error message, right now it's undefined (that's what this issue is about)

**Comment by gr2m** [comment]
gotcha. And yes. I'll get back to it

**Comment by gr2m** [comment]
Max, you can work around the nodejitsu issue with subdomains by initializing Hoodie with `/_api`

``` js
hoodie = new Hoodie("/_api")
```

you'll also need this (latest commit in master)
https://github.com/hoodiehq/hoodie-app/commit/0ca705fb9a61213acb5b4ba966ba5af24786b7b4

**Comment by gr2m** [comment]
had to revert changes, will fix another day
