### ISSUE TITLE
Adding Browserify plugins?

### ISSUE THREAD

**Issue by girvo** [hoodiehq/hoodie#456]
Hey there,

Absolutely love the idea of Hoodie, and it's a very impressive implementation! 

One thing I'd love to add to a Hoodie project is compatibility with ECMAScript 2015 on the client-side. This is simple enough with `browserify` which I see the project is already using, and the [`babelify`]() plugin. 

What's the easiest way to adjust the Hoodie browserify call (which I can see is in `hoodie-server` as a `package.json` script) to add a browserify plugin? I can't seem to work out where it gets called :)

Cheers,
Josh

**Comment by gr2m** [comment]
Hey Josh,

we use `browserify` to build the [Hoodie client](https://github.com/hoodiehq/hoodie-client) lib and serve it at `/hoodie/bundle.js`. If you want to add the hoodie client to your app assets / build process, you can add the `hoodie-client` to your dependencies directly and do whatever you want with it :) You’ll have to initialise it yourself then, when loading from `/hoodie/bundle.js`, then you get a pre-initialised `window.hoodie` instance.

Does that make sense / work for you?

**Comment by girvo** [comment]
Thats exactly what I ended up doing! I have it working under `webpack` actually, with `babel-loader`. Working wonderfully :)

**Comment by gr2m** [comment]
that is awesome! You are way ahead of us :) Any chance you could share your setup at some point?
