### ISSUE TITLE
simplify Internal Module Architecture

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#458]
Progress overview, find background info below
- [x] https://github.com/hoodiehq/hoodie-log/issues/31
- [x] https://github.com/hoodiehq/hoodie-connection-status/issues/46
- [x] https://github.com/hoodiehq/hoodie-store/issues/1
- [x] https://github.com/hoodiehq/hoodie-store-server/issues/32
- [x] https://github.com/hoodiehq/hoodie-store-client/issues/90
- [x] create `hoodie-account` repository / module as in https://github.com/hoodiehq/hoodie-store/issues/1
- [x] migrate hoodie-server-account / hoodie-client-account as in https://github.com/hoodiehq/hoodie-store-server/issues/32 and https://github.com/hoodiehq/hoodie-store-client/issues/90

Once all released
- [x] update [hoodie-client package.json](https://github.com/hoodiehq/hoodie-client/blob/65ccb7c346979f76831e7696336179bd67d326c1/package.json#L9-L12)
- [x] update [hoodie-client README.md](https://github.com/hoodiehq/hoodie-client/blob/65ccb7c346979f76831e7696336179bd67d326c1/README.md) (links to repos)
- [x] update [hoodie-client/lib/get-api.js](https://github.com/hoodiehq/hoodie-client/blob/master/lib/get-api.js#L5-L8)
- [x] update `hoodie-server/lib/hapi.js` [here](https://github.com/hoodiehq/hoodie-server/blob/c7e7528415834685356c07573074954ef5b5d8dc/lib/hapi.js#L40) and [here](https://github.com/hoodiehq/hoodie-server/blob/c7e7528415834685356c07573074954ef5b5d8dc/lib/hapi.js#L28)
- [x] update hoodie’s [README.md](https://github.com/hoodiehq/hoodie/blob/tent/README.md#why-is-there-no-code-in-this-repository) with new architecture

---

Today we have this for new Hoodie

```
hoodie/
├── hoodie-client
│   ├── hoodie-client-account
│   ├── hoodie-client-connection-status
│   ├── hoodie-client-log
│   └── hoodie-client-store
└── hoodie-server
    ├── hoodie-server-account
    └── hoodie-server-store
```

Additionally there are these two repositories:
- https://github.com/hoodiehq/hoodie-standalone-account
- https://github.com/hoodiehq/hoodie-standalone-store

We use these to test client & server together and have a simple generic web app UIs.

The problems with this architecture are
- the standalone repos are overhead and confusing
- it’s pretty hard to anderstand how e.g. hoodie-client-account interacts with hoodie-server-account. Like where are the two coming together, exactly
- It sounds / feels unnaturl. `hoodie-client-account`, when talking in natural language is the "Hoodie Account Client", not "Hoodie Client Account"

What we suggest instead is this:

```
hoodie
├── @hoodie/account
│   ├── @hoodie/account-client
│   └── @hoodie/account-server
├── @hoodie/store
│   ├── @hoodie/store-client
│   └── @hoodie/store-server
├── @hoodie/connection-status
└── @hoodie/log
```

This architecture combines all logic for the different places that Hoodie touches into one place. Right now that is server & client logic, but in future that will be an admin UI and a generic app UI. This will make the "standalone" repos obsolete too, the role of `hoodie-standalone-account` is now covered by `@hoodie/account`

All these core modules follow the same folder structure. All folders are optional. 

```
@hoodie/<module-name>
├── README.md
├── package.json
├── client
│   └── index.js
├── server
│   └── index.js
├── public
│   └── index.html
└── admin
    └── index.html
```
- `client/index.js`, exports a Hoodie client plugin, it will be added dynamically to the `/hoodie/client.js` bundle
- `server/index.js`, exports a hapi plugin with server logic
- `public/index.html` and all other assets in `public/` will be served at `/hoodie/<module-name>/`. So for example `@hoodie/account` could come with it’s own generic account UI to sign in / sign out / reset password etc. That way when I build a Hoodie app, I have an account UI out of the box for free.
- `admin/index.html` will be added to the Hoodie Admin Dashboard – how ever that will work :) We can ignore this part for now and get back to it later.

So this will then work exactly the same with Hoodie Plugins, too. Only that they will not be scoped with `@hoodie`, but probably have a package name prefix like `hoodie-plugin-<name-here>`

---

I thought a lot about this in the past weeks and months, and finally I feel like we figured it all out, it all make sense

![Mind: blown](https://images.duckduckgo.com/iu/?u=http%3A%2F%2Fmedia4.giphy.com%2Fmedia%2FyoJC2sk5DhU7attXry%2F200.gif&f=1)

Let us know what you think :)

**Comment by NickColley** [comment]
:+1:

**Comment by lewiscowper** [comment]
![](http://media1.giphy.com/media/u23zXEvNsIbfO/giphy.gif)

I really like the scope idea, and the naming/optional dir structure. The big problem I see with small module architectures is differences in internal plugin structures, because the plugin docs are focussed on the external APIs. With having a set of optional directories setting up the plugin architectures for the plugins, I can see this being a really great way of bringing new contributors up to speed with making a plugin, and being able to easily dip in to any plugin, internal to hoodie, or external, is a really great thing for usability.

**Comment by janl** [comment]
+1

**Comment by gr2m** [comment]
We are moving forward with this now :)

**Comment by gr2m** [comment]
@finnp next up would bei either `@hoodie/account` or `@hoodie/store`. Maybe `@hoodie/store` is better as we have more pending PRs on the account module

The `@hoodie/store` is an entire new module:
- Create a new repository `hoodie-store`
- add the current `hoodie-server-store` and `hoodie-client-store` as dependencies
- create `server/index.js` which returns `hoodie-server-store`
- create `client/index.js` which returns `hoodie-client-store`
- create `public/index.html` as a placeholder similar to https://github.com/hoodiehq/hoodie-server. This is what later on would be shown at `https://myapp.com/hoodie/store`. It would load `<script src="/hoodie/client.js"></script>` and would show a generic UI for store related tasks.

It would be great if we would have a built in demo server in this repository, so that `npm start` would show the index.html page in `public/`, and `/hoodie/client.js` would load a pre-initialised `hoodie-client-store`, with a hack like this:

```
var hoodie = {
  store: Store.defaults({remoteBaseUrl: '/hoodie/store/api' })('mydb')
}
```

so that `window.hoodie.store` is available, but none of the other `hoodie.*` APIs. If we have that, we can create a few integration tests that test the store client with the store server REST API in isolation, which will make debugging simpler. 

Once we have `@hoodie/store`, we can rename `hoodie-server-store` to `@hoodie/server-store` and `hoodie-client-store` to `@hoodie/store-client`. We don’t need to change the internals of these repos like we did for `@hoodie/log` and `@hoodie/connection-status`, as `@hoodie/store-client` & `@hoodie/store-server` don’t need to have the `server/` or `client/` folders, they are just internal modules to split up `@hoodie/store`

Hope that all makes sense :) It’s been a long day here. Good luck! Let me know if you have any questions

**Comment by finnp** [comment]
I created PRs for `hoodie-store-client`  (https://github.com/hoodiehq/hoodie-store-client/issues/90) and `hoodie-store-server` (https://github.com/hoodiehq/hoodie-store-server/issues/32).

Also I started off with https://github.com/hoodiehq/hoodie-account, but the example is not working yet. Maybe someone could look into it? Basically running `npm start` should start the account server, but it doesn't seem to work.

**Comment by gr2m** [comment]
@finnp does the issue still persist for you? I did setup the `hoodie-acount` repo from scratch, run `npm install` and `npm start` and did not run in any issues, it works as expected.

**Comment by finnp** [comment]
@gr2m Yes. When I do `npm start` and then try to do `hoodie.account.signUp({username: 'test', password: 'test'})` it errors, because `http://finns-air:4663/hoodie/account/api/session/account` doesn't seem to work. I also tried to remove `hoodie/account` from that url as well as `/api`, but that didn't help as well.

**Comment by gr2m** [comment]
@finnp I know what’s up, the `server.register` for the plugin [here](https://github.com/hoodiehq/hoodie-account/blob/f6e9db6/example/index.js#L31) gets run after `server.start`, because `db.installUsersBehavior()` is async, and the flow continuous below. 

I found that out with the help of https://www.npmjs.com/package/lout, really helpful to quickly understand what the current exposed routes are, I think hapi should have something similar by default :)

anyway, here’s the diff for my changes that make it work. I get another error now, but I’ll leave it to you :) 

``` diff
diff --git a/example/index.js b/example/index.js
index ef36df4..14aeb2f 100644
--- a/example/index.js
+++ b/example/index.js
@@ -28,46 +28,56 @@ var server = new Hapi.Server({})
 var db = new PouchDB('http://localhost:5984/_users', {db: memdown})

 db.installUsersBehavior().then(function () {
+  server.connection({
+    port: 4663
+  })
+
   server.register({
     register: hapiAccount,
     options: {
-      usersDB: db
+      usersDb: db
+    },
+    routes: {
+      prefix: '/hoodie/account/api'
     }
   }, function (err) {
     if (err) throw err
   })
-})

-server.connection({
-  port: 4663
-})
+  server.route({
+    method: 'GET',
+    path: '/hoodie/client.js',
+    handler: function (request, reply) {
+      if (!ACCOUNTJS) {
+        return bundleEE.once('done', function (error, buffer) {
+          if (!error) reply(buffer).type('application/javascript')
+        })
+      }
+      reply(ACCOUNTJS).type('application/javascript')
+    }
+  })
+
+  server.register(inert, function (err) {
+    if (err) throw err
+  })

-server.route({
-  method: 'GET',
-  path: '/hoodie/client.js',
-  handler: function (request, reply) {
-    if (!ACCOUNTJS) {
-      return bundleEE.once('done', function (error, buffer) {
-        if (!error) reply(buffer).type('application/javascript')
-      })
+  server.route({
+    method: 'GET',
+    path: '/',
+    handler: function (request, reply) {
+      reply.file(path.join(__dirname, '..', 'public', 'index.html'))
     }
-    reply(ACCOUNTJS).type('application/javascript')
-  }
-})
+  })

-server.register(inert, function (err) {
-  if (err) throw err
-})

-server.route({
-  method: 'GET',
-  path: '/',
-  handler: function (request, reply) {
-    reply.file(path.join(__dirname, '..', 'public', 'index.html'))
-  }
+  server.start(function (err) {
+    if (err) throw err
+    console.log('Server running at %s', server.info.uri)
+  })
 })

-server.start(function (err) {
-  if (err) throw err
-  console.log('Server running at %s', server.info.uri)
+.catch(function (error) {
+  console.log(error)
+  console.log(error.stack)
 })
```

**Comment by gr2m** [comment]
here’s the full code for `example/index.js` as I got it, the diff might be a bit hard to read: https://gist.github.com/b3d53107b9fddb0a8d55

**Comment by finnp** [comment]
Here are the PRs for
- hoodie-client https://github.com/hoodiehq/hoodie-client/pull/65
- hoodie-serverhttps://github.com/hoodiehq/hoodie-server/pull/485

**Comment by inator** [comment]
@gr2m & @finnp - Thanks for all the work on this.  I'm gonna chime in a bit on something near and dear to my heart - the plugin architecture.  This structure you're running with certainly seems well thought out, and I like the approach a lot!

I'd like to add some thoughts to the discussion for consideration:

1)  I suggest that plugin modules should be installed globally for use across several Hoodie apps
2)  Plugins should be identified in some sort of "plugins.json" config file that is watched by Hoodie Server
3)  plugins.json should trigger a hot (re/un)load of the plugin(s) using something like [this](https://www.npmjs.com/package/require-reload).
4)  I suggest that plugins should both consume and emit events (to/from Hoodie core and other plugins).
5)  Plugins should be able to expose new API routes and associated handlers through HAPI

I'm sure some of this has already been explored, but should you have any thoughts, I'd really like to keep the discussion going on this very important feature.  If you would prefer a new issue, I'd be happy to create one and jump over there as well.

Thanks very much for the fantastic work!

**Comment by gr2m** [comment]
> 1)  I suggest that plugin modules should be installed globally for use across several Hoodie apps

We will use npm for plugins, you can install them as you wish. I’m not sure if `npm install` installs local dependencies if the package is already installed globally, worst case is you can do a custom script to remove dependencies from package.json that you have installed globally

> 2) Plugins should be identified in some sort of "plugins.json" config file that is watched by Hoodie Server

Config will be in `package.json`, but you can set a path to a config file that  you can watch

The rest is too early to discuss now I think :)

**Comment by ashanaweb** [comment]
-})
+  })

-server.register(inert, function (err) {
-  if (err) throw err
-})

-server.route({
-  method: 'GET',
-  path: '/',
-  handler: function (request, reply) {
-    reply.file(path.join(__dirname, '..', 'public', 'index.html'))
-  }
+  server.start(function (err) {
+    if (err) throw err
+    console.log('Server running at %s', server.info.uri)
+  })
 })

-server.start(function (err)

**Comment by ashanaweb** [comment]
-})+  })
-server.register(inert, function (err) {-  if (err) throw err-})
-server.route({-  method: 'GET',-  path: '/',-  handler: function
(request, reply) {-    reply.file(path.join(__dirname, '..', 'public',
'index.html'))-  }+  server.start(function (err) {+    if (err) throw
err+    console.log('Server running at %s', server.info.uri)+  })
 })
-server.start(function (err)


2016-04-01 20:31 GMT+02:00 Gregor Martynus <notifications@github.com>:

**Comment by gr2m** [comment]
added one more task to update the README of the repo

**Comment by ashanaweb** [comment]
},
 +    "message": {
 +      "type": "string"
 +    },
 +    "request_id": {
 +      "type": "string"
 +    },
 +    "documentation_url": {
 +      "type": "string"
 +    },
    },
    "required": ["objects"],
    "additionalProperties": false

**Comment by ashanaweb** [comment]
},
+ "message": {
+ "type": "string"
+ },
+ "request_id": {
+ "type": "string"
+ },
+ "documentation_url": {
+ "type": "string"
+ },
},
"required": ["objects"],
"additionalProperties": false

2016-04-02 4:39 GMT+02:00 Gregor Martynus <notifications@github.com>:

**Comment by ashanaweb** [comment]
Content-Type: application/vnd.git-lfs+json
 +> Authorization: Basic ... (if authentication is needed)
 +>
 +> {
 +>   "operation": "upload",
 +>   "objects": [
 +>     {
 +>       "oid": "1111111",
 +>       "size": 123
 +>     },
 +>     {
 +>       "oid": "2222222",
 +>       "size": 123
 +>     }
 +>   ]
 +> }
 +>
 +< HTTP/1.1 200 Ok
 +< Content-Type: application/vnd.git-lfs+json
 +<
 +< {
 +<   "objects": [
 +<     {
 +<       "oid": "1111111",

**Comment by ashanaweb** [comment]
Content-Type: application/vnd.git-lfs+json
+> Authorization: Basic ... (if authentication is needed)
+>
+> {
+> "operation": "upload",
+> "objects": [
+> {
+> "oid": "1111111",
+> "size": 123
+> },
+> {
+> "oid": "2222222",
+> "size": 123
+> }
+> ]
+> }
+>
+< HTTP/1.1 200 Ok
+< Content-Type: application/vnd.git-lfs+json
+<
+< {
+< "objects": [
+< {
+< "oid": "1111111",

2016-04-02 8:28 GMT+02:00 Marianna Ashafein <mariannaweb9@gmail.com>:

**Comment by finnp** [comment]
@gr2m What about hoodie-server-task and hoodie-client-task? I guess they should be migrated as well, right?

**Comment by gr2m** [comment]
the task module is out of scope right now so I ignored it in the list, but yeah, we have to migrate it as well :) It shouldn’t be too much work, if you find time, would be great if you could prepare it like you did account & store :+1:

**Comment by gr2m** [comment]
I guess we are done :clap: :tada: chapeau Finn :)
