### ISSUE TITLE
clarify `authenticated` & `unauthenticated` events

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#48]
follow up for #44

**Comment by gr2m** [comment]
also:
A question we have to answer clearly: "How do I know if a user is logged in?". 

Answer is 

``` js
if (hoodie.account.username) {} else {}
```

**Comment by gr2m** [comment]
I think it's rather something to put on hood.ie, maybe as a `Account Events` section? @espy

**Comment by espy** [comment]
Done!

**Comment by gr2m** [comment]
Sorry to comment on a closed issue, but I've a related question:

Shall we rename: "authenticated" to "reauthentictaed", and make it fire only if the user is signed locally, und successfully reauthenticates? I think that would make things more clear, what you think?

Right now, the "authenticated" request gets trigger pretty much every time you run `hoodie.account.authenticate().then( doSomethingButOnlyIfSignedInWithValidSession )`

**Comment by gr2m** [comment]
Oh, also, the other event is called `error:unauthenticated`, not `unauthenticated`. What makes more sense to you? There might be other errors at some point, but not sure yet
