### ISSUE TITLE
rename "bearer" to "session" in Authorization header

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#485]
rename bearer in our Authorization header to session, because that’s what it is, and we don’t use bearer tokens anywhere else in our code. It’s unnecessary confusing. So instead of Authorization: bearer sessionid123 header, we would have Authorization: session sessionid123

**Comment by jameswestnz** [comment]
@gr2m wish I had noticed this a bit sooner as I have a question on this..

This issue makes sense in the current context, but would we not be better longer term to look at JWT? I'm not trying to block this issue so late in the game, as I think this question will be a longer running discussion, but curious to others' thoughts.

**Comment by gr2m** [comment]
You mean [JSON Web Token](https://jwt.io/)? I don’t know anything about it, I’ll have to look into it. But the plan is that besides `Session` there will be other ways to authenticate, like `Token` that can be used once to reset a password, and probably plugins will find other ways to use the Authorization header?

**Comment by jameswestnz** [comment]
I sure do :)

I bring it up as it does provide a bit more flexibility with what information is passed in this token, and it's signed with a private key which allows for distributed authorization (i.e. by any of your servers knowing the private key, you can let a user in knowing the provided JWT hasn't been tampered with.). A use case I considered at one point was checking auth on our reverse proxy server (running hapi/h2o2 etc) to reduce load to the app servers - not the best example as loading proxy servers isn't always smart haha.

In saying that, I can now see the other uses you're thinking of - so it feels like the hoodie default should be `Session`, and a plugin later down the track _could_ wrap the account plugins providing jwt etc, while still providing your mentioned use cases, such as `Token`.

**Comment by gr2m** [comment]
done via done via e63a0dd, 65c6a3f, f3dd07e
