### ISSUE TITLE
Hoodie Windows Installer 

### ISSUE THREAD

**Issue by LadyNaggaga** [hoodiehq/hoodie#505]
Hi ! What version of node and npm do I need to install ?

**Comment by gr2m** [comment]
install the `LTS` version: https://nodejs.org/en/. Once installed, update to latest `npm` with `npm install -g npm`

We want to improve setup instructions for Windows, @jsturtevant is working on some helpful tips to get a terminal, git and node / npm installed, looking forward to his blog post on this :)

**Comment by jsturtevant** [comment]
I put up a post at http://www.jamessturtevant.com/posts/5-Ways-to-install-git-on-Windows/.

Let me know what you think.  I can also take one of the scenarios and do a more focused post.
