### ISSUE TITLE
Wrong hoodie url when using from another host

### ISSUE THREAD

**Issue by rogeriochaves** [hoodiehq/hoodie#519]
The client.js bundle initialize hoodie without url options, like this:

``` javascript
hoodie = new Hoodie();
```

This causes hoodie to use the url from `location.origin`, the problem is that in my use case, I need to use hoodie as an external resource, like this:

``` html
<script type="text/javascript" src="http://localhost:4000/hoodie/client.js"></script>
```

But my application is running on another port (e.g. localhost:8000), so hoodie does not work. And if I instantiate it like this on my app side:

``` javascript
hoodie = new Hoodie({url: 'http://localhost:4000'});
```

It's too late because `client.js` already initialized hoodie on the wrong url, so some automatic calls, like `api/user%2Fmyuser/`, keep getting called on my own app url (localhost:8000/hoodie instead of localhost:4000/hoodie like it should be), throwing 404s, and poor clueless PouchDB says they are normal

**Comment by gr2m** [comment]
we will fix it via the `client` option instead, see https://github.com/hoodiehq/hoodie/pull/520#issuecomment-230166837
