### ISSUE TITLE
ie.hood.local-tld-firewall.plist conflicts with pow

### ISSUE THREAD

**Issue by jontore** [hoodiehq/hoodie#52]
I had a problem with that the hoodie deamons are rerouting all request to dev even though the hoodie app is not started. This is causing some major headache when working with other applications such pow that also does this trick. Would it be possible to turn these off when the hoodie app is not running, and the enable it when it is. Or provide a tool to change the domain for for hoodie.

**Comment by gr2m** [comment]
Yes, we are working on this at the moment, the local-tld magic will become optional, also because of multi platform support. Find the current state at https://github.com/caolan/hoodie-app, but I don't know the current state here.

@caolan @janl can you tell where we are with making local-tld optional?

**Comment by janl** [comment]
On Apr 22, 2013, at 15:52 , Gregor Martynus notifications@github.com wrote:

> Yes, we are working on this at the moment, the local-tld magic will become optional, also because of multi platform support. Find the current state at https://github.com/caolan/hoodie-app, but I don't know the current state here.
> 
> @caolan @janl can you tell where we are with making local-tld optional?

We aren’t yet :) — but definitely planning to, once I get a minute in between travels.

**Comment by jontore** [comment]
Great :) Thank you for good work. BTW is there any workaround except for unloading them at the moment?

**Comment by janl** [comment]
unloading is easiest :)

**Comment by gr2m** [comment]
This can be closed, right?
