### ISSUE TITLE
No CORS headers for replications

### ISSUE THREAD

**Issue by sdvg** [hoodiehq/hoodie#526]
My webpack dev server runs at `http://127.0.0.1:8080`, the hoodie webserver at `http://127.0.0.1:2048`.
The `signUp` and `signIn` methods work with this setup.

After signing in I always experience #503 (401s for replications requests).

Then I reload the page and every request to `http://127.0.0.1:2048/hoodie/store/api/user%2F319ztpw/` results in the following error:

> XMLHttpRequest cannot load http://127.0.0.1:2048/hoodie/store/api/user%2F319ztpw/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:8080' is therefore not allowed access. The response had HTTP status code 404.

The requests look like this:

```
curl 'http://127.0.0.1:2048/hoodie/store/api/user%2F319ztpw/' -H 'authorization: Session bUBzZC52Zzo1NzkzNzk3NzoGRWg0ob-k5dRpejYH2-MohuIjSA' -H 'Origin: http://127.0.0.1:8080' -H 'Accept-Encoding: gzip, deflate, sdch' -H 'Accept-Language: en-US,en;q=0.8,de;q=0.6,ru;q=0.4' -H 'User-Agent: Mozilla/5.0 (Linux; Android 5.1.1; Nexus 6 Build/LYZ28E) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.23 Mobile Safari/537.36' -H 'Accept: application/json' -H 'Referer: http://127.0.0.1:8080/overview' -H 'Cookie: beaker.session.id=b18fc57541128c9bf6d67ef37f161771' -H 'Connection: keep-alive' --compressed
```

I use the up to date Hoodie 23.1.0.

Please tell me if you need any more information :)

**Comment by gr2m** [comment]
Thanks @sdvg I’ll have a look at it and see if I can reproduce the issue. We are adding CORS support globally here: https://github.com/hoodiehq/hoodie/blob/master/server/index.js#L29 but maybe it’s not getting added when only proxying the requests to a CouchDB?

Do you use CouchDB as a backend for your Hoodie app (meaning do you set the `dbUrl` option)?

**Comment by gr2m** [comment]
Okay I could reproduce the issue with https://github.com/hoodiehq/hoodie-app-tracker. Make sure you have `hoodie@23.1.0` installed, then start the tracker app with

```
npm start -- --url="http://localhost:8080"
```

Now open http://127.0.0.1:8080 in the browser. All hoodie requests will go to cross-origin to http://localhost:8080. The account requests work fine, the store requests fail because no CORS headers are being set.

I’m looking into it. Good catch, thanks @sdvg

**Comment by gr2m** [comment]
after you sign in, try to reload the page. Do you still get the error?

**Comment by gr2m** [comment]
Not sure if this is the root cause for this, but it’s definitely a bug that was bothering us for a long time, finally found out what’s causing it: https://github.com/hoodiehq/hoodie-store-client/issues/106. I’ll look into this one first

**Comment by gr2m** [comment]
I fixed hoodiehq/hoodie-store-client#106 but it does not yet resolve the CORS issue with `/hoodie/store/api/...` routes

**Comment by gr2m** [comment]
if you use CouchDB as a backend, the problem does not occur, only when using PouchDB as a backend (which Hoodie does by default). I think the problem is that we are passing the raw request / response pair to express-pouchdb here: https://github.com/hoodiehq/hoodie-store-server/blob/master/index.js#L72

**Comment by gr2m** [comment]
I think I got it, using https://github.com/jakepruitt/hapi-to-express in hoodie-store-server resolves the issue. I’ll start a PR

**Comment by gr2m** [comment]
Travis is currently not picking up builds so we can’t release a new version, but you can check if this fixes the problem that you see: https://github.com/hoodiehq/hoodie-store-server/pull/48. Would be great if you could review the PR, just to check if the changes all make sense to you and if you tested it locally
