### ISSUE TITLE
Turn hoodie into hapi plugin

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#528]
at the moment, `require('hoodie')` returns a method that creates a Hapi instance and passes it to the callback: https://github.com/hoodiehq/hoodie/blob/master/server/index.js

The way we start the Hoodie server at the moment can be seen in [bin/start.js](https://github.com/hoodiehq/hoodie/blob/master/bin/start.js#L129-L145)

I think it had historical reasons why we ended up with that architecture, and I don’t think it makes much sense any more. Instead, I’d suggest that `require('hoodie')` will return a hapi plugin and that we instantiate a Hapi instance in `bin/start.js` instead. 

That will also make it simple to use Hoodie in existing architectures. And for some people who don’t want to wait for plugins, they can build their own hapi server with custom routes and add hoodie to the mix.

Any thoughts?

**Comment by gr2m** [comment]
I’ll look into this as I think it’s pretty straight forward and it will let people extend Hoodie Server more easily without limitations

**Comment by sebbel** [comment]
Looking forward to this!!

**Comment by jameswestnz** [comment]
This is ideal - I've done the dirty and used `proxyquire` to replace some basic functions in the short term. This is going to remove the need for plugins for me in the short term, and will get rid of some of my hacks!
