### ISSUE TITLE
use _changes?feed=continuous instead of feed=longpoll

### ISSUE THREAD

**Issue by janl** [hoodiehq/hoodie#54]

**Comment by svnlto** [comment]
+1

**Comment by gr2m** [comment]
as suggested by @acconut, let's look into EventSource as well #74 

> I have no opinion on that matter. We currently use long poll requests, @janl already suggested to use the continuous feed instead.
> 
> I don't know about the pros & cons here. Can you guys help to make a comparison between the long poll, continuous feed and EventSource Implementation?

**Comment by gr2m** [comment]
@daleharvey mentioned at IRC the other day that he had big problems with the continuous feed, right?

I'd suggest we leave it as is until we migrate to PouchDB. Feel free to reopen if you don't agree :)

**Comment by janl** [comment]
Sounds good
