### ISSUE TITLE
CORS stopped working

### ISSUE THREAD

**Issue by sdvg** [hoodiehq/hoodie#544]
CORS headers for Hoodie APIs no longer get set, so cross origin requests fail.

Steps to reproduce:
1. `git clone https://github.com/hoodiehq/hoodie-app-tracker.git`
2. `cd hoodie-app-tracker/`
3. `npm start -- --url="http://localhost:8080"`
4. Open http://127.0.0.1:8080/account.html in an incognito / private tab.
5. Try to log in.

A message like this should appear in the console:

> XMLHttpRequest cannot load http://localhost:8080/hoodie/account/api/session. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:8080' is therefore not allowed access. The response had HTTP status code 404.

**Comment by gr2m** [comment]
only the `/hoodie/account/api/*` routes are affected, not the `/hoodie/store/api/*` routes

**Comment by gr2m** [comment]
Hey @sdvg any update on the issue? @brunopedroso just run into the same thing

For the record: a temporary workaround is to remove `sandbox: 'plugin'` from https://github.com/hoodiehq/hoodie/blob/master/server/index.js#L55

**Comment by mmolhoek** [comment]
got the same problem when integrating hoodie in angular 2 app https://github.com/simpulton/ngrx-rest-app. removing the sandbox did the job for me aswell :+1:

**Comment by sdvg** [comment]
@gr2m Not really, I spent some time on this but didn't find out much new.
The Hoodie implementation looks got to me (but I didn't find much documentation on the sandbox feature).

Next steps could be to look for a solution in the hapi code or to build a reduced test case.
I can't tell when I'll find the time to do so :/

**Comment by sdvg** [comment]
I looked into this again and the problem seems to be solved in either Hoodie or hapi :)

FYI: I had to test with two different servers (on different ports). When I start Hoodie with `npm start -- --url="http://localhost:8080"` and open `http://127.0.0.1:8080` in the browser, all request go to `127.0.0.1` instead of `localhost` now.

**Comment by gr2m** [comment]
I think `127.0.0.1`, `localhost` and `0.0.0.0` are aliases, they all point to your own computer. The only difference is that if you bind an app running on your computer to `127.0.0.1` it cannot be accessed from outside, while if you bind it to `0.0.0.0` it can

**Comment by gr2m** [comment]
Also thanks fro checking :)
