### ISSUE TITLE
registerPlugins(): Handler name already exists

### ISSUE THREAD

**Issue by jameswestnz** [hoodiehq/hoodie#545]
This occurs when hoodie is being run as a hapi plugin (as opposed to being run from CLI).

This error is thrown when another plugin (or the user's script) registers plugins that are also registered in `hoodie`.

I'm using a plugin that is built very similar to hoodie (registers more hapi plugins when the plugin is bootstrapped) which registers `h2o2` and `inert`, and noticed hoodie wasn't starting. This error is also not thrown here: https://github.com/hoodiehq/hoodie/blob/master/server/plugins/index.js#L40 - it required a try/catch wrapped around the register function, which rendered the following message: `[Error: Handler name already exists: proxy]`.

I've tried modifying both hoodie and the other plugin to use different hapi registration settings (such as `once`, or even their dependency function), but unfortunately don't yet have a work-around.

Maybe someone has had similar experiences with conflicting plugin registrations and could shed some light?

**Comment by jameswestnz** [comment]
We may need to consider using the dependency method: http://hapijs.com/api#serverdependencydependencies-after

This would mean that in `cli/index.js` we would need to register these dependencies, then anyone use hoodie as a plugin would need to do the same in their own code.

**Comment by hayload** [comment]
So I think there's a work-around for this, and I also think it's acceptable considering you'd only see this issue in an advanced hapi setup...

Basically, the error arises when registering certain plugins more than once within the same hapi instance. So the workaround is to run seperate hapi instances where this conflict happens. The reality is that hoodie relies on a single connection hapi instances anyway (we have references to `server.info` everywhere, which doesn't work with multiple hapi connections).

This only works if you were planning on running on different ports or host, as you wouldn't be able to bind two instances to one port without having different hosts keeping the two separated. Just an FYI, as I don't think issue will come up often, and feel it's quite specific to the use-case.

**Comment by jameswestnz** [comment]
So I think there's a work-around for this, and I also think it's acceptable considering you'd only see this issue in an advanced hapi setup...

Basically, the error arises when registering certain plugins more than once within the same hapi instance. So the workaround is to run seperate hapi instances where this conflict happens. The reality is that hoodie relies on a single connection hapi instances anyway (we have references to `server.info` everywhere, which doesn't work with multiple hapi connections).

This only works if you were planning on running on different ports or host, as you wouldn't be able to bind two instances to one port without having different hosts keeping the two separated. Just an FYI, as I don't think issue will come up often, and feel it's quite specific to the use-case.

**Comment by gr2m** [comment]
I don’t 100% understand the problem here :) but if you think it’s an edge case, shall we close the issue and get back to it in case someone else has the same issue, too?

For Hoodie itself, we will definitely stay with only one connection for everything
