### ISSUE TITLE
ask for password at `hoodie.account.destroy()`

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#55]
similar to `hoodie.account.changeUsername(password, newUsername)`.

**Comment by caolan** [comment]
@gr2m do we check the password in the backend during a username change? I see there is a sign-in call from the frontend, but the subsequent task handled by the users plugin doesn't seem to check you sent a correct password. This would need handling in the same way for this ticket.

**Comment by gr2m** [comment]
> do we check the password in the backend during a username change

I think that we don't. And I also don't yet know how we could achieve that. Sending a sign in is all nice, but in theory, you could work around this, which I'd consider a security flaw.

So my Idea was to setup update handlers on the `_users` database, and for the `changeUsername` / `changePassword` / `destroy` requests, we'd require to send the password and check it server-side. Would that be possible?

**Comment by gr2m** [comment]
closing in favor of https://github.com/hoodiehq/hoodie-account/issues/13
