### ISSUE TITLE
objects reappear after deleting them

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#57]
This is a known issue. The problem lies on how hoodie.js generates `_rev` number locally before sending local changes to CouchDB. At the moment, they are random uuids, but I've learned that they are actually a hash of the last state of the object (is that right @janl)

So the pushed changes create conflicts in CouchDB, which decides who's the "winner". And that usually is not the version that got deleted. So the old revision gets pushed back to the client, and the objects reappears.

I want to look into [pouchdb](https://github.com/daleharvey/pouchdb)'s implementation to fix that. I hope to have time for it the coming week. But if anyone want to jump in, feel free :-)

**Comment by janl** [comment]
@gr2m spot on.

**Comment by espy** [comment]
I think this is also the source of the "isDirty === true" problems we talked about, @gr2m. There are versions of deleted objects lying around in localstorage that never get synced.

**Comment by espy** [comment]
Just for reference: https://github.com/hoodiehq/hoodie-app/issues/65

**Comment by gr2m** [comment]
I fixd a few things, but didn't get to the reappearing bug yet. I tried hard to reproduce the issue, but just couldn't. Can you tell me one? Might also be at http://hoodie-mapchat.jit.su/
