### ISSUE TITLE
Refactor logger.js for better testability

### ISSUE THREAD

**Issue by davelosert** [hoodiehq/hoodie#593]
Taken from #590 - @gr2m asked me to open another issue. 

What it is about:

> I realized quickly that the logger-module itself is not very easy testable. It would be easier if the actual logging-method was exposed from the module or extracted into a submodule.
> 
> As I see it, the logger.js has 3 responsibilities:
> 1. Register the plugin as such with the server
> 2. Create the “GoodCase”-Class as a stream-logger
> 3. Create the actual log-function for the different events
>    It would be way nicer (and better testable) to split those 3 responsibilities into three different files. If you agree we could open an issue for that and I would try to create a PR.

This should be done AFTER [hoodiehq/camp#35](https://github.com/hoodiehq/camp/issues/35) - as it directly handles another refactoring of the logger.

**Comment by davelosert** [comment]
I see within [hoodiehq/camp#35](https://github.com/hoodiehq/camp/issues/35) the server-register was separated from the rest. So I'd say it looks better testable now and this refactoring here is not needed anymore.

@gr2m You agree? If so maybe just close it.

**Comment by gr2m** [comment]
yes I agree, it’s much simpler now 👍 thanks to hoodiehq/camp#35
