### ISSUE TITLE
Refactor client/index.js for better testability

### ISSUE THREAD

**Issue by davelosert** [hoodiehq/hoodie#594]
Taken from #590 - @gr2m asked me to open another issue for it. 

Regarding [client/index.js](https://github.com/hoodiehq/hoodie/blob/master/server/plugins/client/index.js)

> Something similar to logger (see #593): It would be way easier to test if the actual handler-function was exposed or refactored into a different file. Right now I wasn’t able test if fs actually writes to the correct path (or only with lots of code duplication). If the Handler-Function could be created with all those paths as options-object, it would be easier. What do you think?

With this I meant: You have to jump through a little hoop to get to test the function passed to the `handler`-property given to the `server.router()`-function - as you have to mock the `server` object and then get the handler from the argument passed to it - simplified it looks like this:

```
var simple = require('simple-mock')
var client = require('server/plugins/client');
var mockServer = {
      route: simple.stub()
}
var next = simple.stub()
client.register(mockServer, {config: {}}, next)
// All this just to get to the handler-function I want to test
var handler = mockServer.route.lastCall.arg[0].handler
```

If the actual function passed to `handler` would be extracted into an own file, it would be better testable.
As it depends on some paths (`hoodieClientModulePath`, `hoodieClientPath` and `bundleTargetPath`) I think a factory would be nice, so it could look something like:

```
var createHandler = require('./handler-factory.js)
var hoodieClientModulePath = path.dirname(require.resolve('@hoodie/client/package.json'))
var hoodieClientPath = path.join(hoodieClientModulePath, 'index.js')
var bundleTargetPath = path.join(options.config.data || '.hoodie', 'client.js')

server.route([{
    method: 'GET',
    path: '/hoodie/client.js',
    handler: createHandler(hoodieClientModulePath, hoodieClientPath, bundleTargetPath)
  }])
```

The upside: It would also be testable if the `fs.writeFile()` call actually writes to the `bundleTargetPath` as with the factory one would have directly control over that from the outside (right now thats not possible to be passed in).

**Comment by davelosert** [comment]
I'm going to work on this one...

**Comment by gr2m** [comment]
done via https://github.com/hoodiehq/hoodie/issues/606 👍
