### ISSUE TITLE
Create 404.html page for accept: text/html requests

### ISSUE THREAD

**Issue by davelosert** [hoodiehq/hoodie#595]
Taken from #590 - @gr2m  asked me to open another issue for it.

> When sending a request with accept: text/html to the url /hoodie/unkown, the server responds with JSON. Maybe there should be a 404.html page?

I guess thats rather clear :smile:

**Comment by jamietanna** [comment]
Mind if I claim this?

**Comment by gr2m** [comment]
@jamietanna not at all, good luck :)

**Comment by davelosert** [comment]
@jamietanna : Are you still on this? If not then maybe I would grab it! :D

**Comment by jamietanna** [comment]
Apologies @davelosert, been a busy couple of days. I'm looking into it this afternoon, with a fix expected by end of tomorrow!

**Comment by davelosert** [comment]
@jamietanna Alright, no pressure! :+1: Good luck with the task! :)
