### ISSUE TITLE
Don't throw error when browserify.bundle fails

### ISSUE THREAD

**Issue by davelosert** [hoodiehq/hoodie#596]
Taken from #590  - @gr2m asked me to open another issue for it.

Regarding [server/plugins/client/bundle.js](https://github.com/hoodiehq/hoodie/blob/master/server/plugins/client/bundle.js)

> When browserify.bundle runs into an error, the error is thrown instead of passed to the callback – effectively killing the server. Shouldn’t this be handled more gracefully by invoking an error-callback instead?

Rather low hanging fruit I guess - maybe something for first-timers? :smile:

**Comment by redice44** [comment]
New comer here 🖐 I'll take a crack at it 😊
