### ISSUE TITLE
create a worker for pagemunch

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#60]
just a reminder issue for myself, @caolan brought up the idae, and I thinkt it's a great one:
http://www.pagemunch.com/

**Comment by caolan** [comment]
Also going to mention @tommoor on this issue since he created the service ;)

**Comment by tommoor** [comment]
Good day,

Hope all is well in Hoodie land! It would be great to know what you plan on using the worker for - anything in particular? Also, I'm sure you've spotted there is a (very simple) npm module for pagemunch that might shave 5 mins off your development time :)

Let me know if there are any problems or questions - cheers!

**Comment by janl** [comment]
@gr2m when you close these, can you mention what resolved them?

**Comment by gr2m** [comment]
yeah sorry, I've put it in the backlog, we'll review these regularly
https://github.com/hoodiehq/hoodie.js/issues?milestone=2&state=closed

I just closed them to cleanup the issues, for better focus

**Comment by janl** [comment]
Excellent, thanks! This helps to follow this remotely :)
