### ISSUE TITLE
Initial start application

### ISSUE THREAD

**Issue by guiferpa** [hoodiehq/hoodie#611]
I'm create a `hello world`application but when start it show me this message:

`Please enter your CouchDB _admin credentials:`

I'm write my username and password but this command-line show me again the same message.

**Comment by gr2m** [comment]
it looks like you use the old Hoodie version. Can you try this please?

First, uninstall the hoodie CLI, it’s deprecated 

```
npm uninstall --global hoodie
```

After that create a new folder, create a package.json and install hoodie

```
mkdir hoodie-test-app
cd hoodie-test-app
npm install --save hoodie
```

then create `public/index.html` with any content you  want. And then 

```
npm start
```

Does that work for you?

**Comment by guiferpa** [comment]
I don't need require `hoodie` package ? Just create a file `index.html` ?

**Comment by guiferpa** [comment]
Great, I understand. tks 😃

**Comment by gr2m** [comment]
> Just create a file index.html ?

In the `public/index.html` file you can load the Hoodie client using

``` html
<script src="/hoodie/client.js"></script>
```
