### ISSUE TITLE
Invalid credentials when trying to do hoodie.account.signIn. Following the getting started guide

### ISSUE THREAD

**Issue by GreenGeorge** [hoodiehq/hoodie#614]
Hi I was trying to follow along the official [getting started guide ](http://docs.hood.ie/camp/start/getting-started/getting-started-1.html)
I got to the `hoodie.account.signUp` and `hoodie.account.signIn` example. 
Copy pasted the example code and this is what I got:

``` javascript
hoodie.account.signUp({username: 'Robin', password: 'secret'})
```

returns 

``` javascript
{outcome: { id:"0k4dgh7", username:"Robin"}, ...}
```

and

``` javascript
hoodie.account.signIn({username: 'Robin', password: 'secret'})
```

returns 

``` javascript
{ outcome: "Invalid credentials" , ...}
```

and status `401` unauthorized

`$ npm ls | grep hoodie` returns :

``` bash
├─┬ hoodie@24.2.5
│ ├─┬ @hoodie/account@2.0.1
│ │ ├── @hoodie/account-client@4.4.0
│ │ └─┬ @hoodie/account-server@4.0.5
│ ├─┬ @hoodie/admin@1.2.2
│ ├─┬ @hoodie/client@5.0.7
│ │ ├── @hoodie/account-client@2.8.0
│ │ ├─┬ @hoodie/connection-status@3.0.0
│ │ ├── @hoodie/log@2.1.0
│ │ ├─┬ @hoodie/store-client@1.0.0
│ │ │ ├── hoodie-zuul-config@2.0.0
│ │ │ ├─┬ pouchdb-hoodie-api@1.6.4
│ │ │ └── pouchdb-hoodie-sync@1.4.1
│ ├─┬ @hoodie/server@21.1.1
│ │ ├─┬ @hoodie/store-server@2.1.5
npm ERR! extraneous: node-pre-gyp@0.6.30 /Applications/MAMP/htdocs/hoodie/node_modules/node-pre-gyp
│ ├─┬ @hoodie/store@1.0.4
│ │ └─┬ @hoodie/store-client@5.0.12
```

**Comment by gr2m** [comment]
I think you hit this bug:
https://github.com/hoodiehq/hoodie-account-client/issues/115

Try to sign up / sign in with a lowercase username, does that work?
If you like you can try to send a PR to fix the issue to https://github.com/hoodiehq/hoodie-account-client, happy to give you guidance

**Comment by GreenGeorge** [comment]
Yes it works if i do

``` javascript
hoodie.account.signUp({username: 'robin', password: 'secret'});
hoodie.account.signIn({username: 'robin', password: 'secret'});
// { outcome: { id: "f94iali", ... }, ... }
```

I'll have a look at it. In the meantime how about updating the getting started guide to use a lowercase example so people trying out hoodie won't get thrown off too much by this bug ?

**Comment by gr2m** [comment]
Great idea 👍 Can you change it here?
https://github.com/hoodiehq/documentation/blob/gh-pages/camp/start/getting-started/getting-started-1.md
