### ISSUE TITLE
post install error

### ISSUE THREAD

**Issue by brunopedroso** [hoodiehq/hoodie#615]
I'm trying:

```
> mkdir test
> cd test
> npm init -y
> npm install --save hoodie
```

and getting:

```
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130

> hoodie@24.3.0 postinstall /Users/bruno/workspace/test_hoodie_cli_2/node_modules/hoodie
> node ./bin/setup.js

fs.js:540
  binding.open(pathModule._makeLong(path),
          ^

TypeError: path must be a string
    at TypeError (native)
    at Object.fs.open (fs.js:540:11)
    at Object.fs.writeFile (fs.js:1132:6)
    at /Users/bruno/workspace/test_hoodie_cli_2/node_modules/hoodie/bin/setup.js:50:10
    at FSReqWrap.oncomplete (fs.js:82:15)
npm WARN test_hoodie_cli_2@1.0.0 No description
npm WARN test_hoodie_cli_2@1.0.0 No repository field.
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "hoodie"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! hoodie@24.3.0 postinstall: `node ./bin/setup.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hoodie@24.3.0 postinstall script 'node ./bin/setup.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hoodie package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/setup.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hoodie
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hoodie
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/bruno/workspace/test_hoodie_cli_2/npm-debug.log
```

If I try

```
 npm install --save hoodie@24.2.5
```

It works...

**Comment by brunopedroso** [comment]
also: 

```
$ node -v
v4.4.7
$ npm -v
3.10.9
```

**Comment by gr2m** [comment]
Thanks, looking into it!

**Comment by gr2m** [comment]
I tried to reproduce the problem with the same node & npm versions, but had no luck unfortunately. 

Could you please help debug this issue? Can you debug what’s happening in `/Users/bruno/workspace/test_hoodie_cli_2/node_modules/hoodie/bin/setup.js:50`?

**Comment by brunopedroso** [comment]
Oh, I see... in my node version the method `fs.writeFile` could only [receive a string](https://nodejs.org/dist/latest-v4.x/docs/api/fs.html#fs_fs_writefile_file_data_options_callback), not [an integer file descriptor](https://nodejs.org/api/fs.html#fs_fs_writefile_file_data_options_callback) yet...

**Comment by brunopedroso** [comment]
yup. Upgraded node and it ran.

Should we close this or is there any prerequisites doc that should be updated?

**Comment by gr2m** [comment]
But I run it with the same node version and could not reproduce the error ... odd. We try supporting node v4, so if there is a way to work around this potential error, that’d be great

**Comment by klazich** [comment]
I think changing `fd` to `path.join(pathToAppRoot, 'README.md')` should keep this from occurring.

[setup.js  at line 50 ](https://github.com/hoodiehq/hoodie/blob/45baeaf4023516154ea6b63e83774a77af1c5fc4/bin/setup.js#L50)

``` js
      fs.writeFile(fd, readMeContents,
        function (error) {
          if (error) {
            log.error('setup', 'Could not create README.md at ' + pathToAppRoot)
            log.error(error)
            return
          }
          log.info('setup', 'README.md created')
        })
```

**Comment by gr2m** [comment]
@klazich did you test it with node v4? It sounds good to me, if someone could test this in node@4 and submit a PR, that’d be ace 👍

**Comment by brunopedroso** [comment]
I've tested it with (node: 4.4.7, npm: 2.15.8 ) and with (node: 7.0.0, npm: 3.10.8) and it worked.

In the first setup I see these warnings, btw:

```
npm WARN engine hapi@15.2.0: wanted: {"node":">=4.5.0"} (current: {"node":"4.4.7","npm":"2.15.8"})
npm WARN engine shot@3.3.2: wanted: {"node":">=4.5.0"} (current: {"node":"4.4.7","npm":"2.15.8"})
```

[Here's](https://github.com/hoodiehq/hoodie/pull/634) the PR.

**Comment by gr2m** [comment]
Thanks! the warning is legit I think, latest node@stable is 4.5.0 I think, so that’s what hapi requires in its package.json
