### ISSUE TITLE
logging in not saving data properly

### ISSUE THREAD

**Issue by bbn** [hoodiehq/hoodie#62]
1. create a new hoodie app.  (test)
2. start it up. see hoodie playground.
3. add a todo.("groceries")
4. sign up an account. ("aaaaa"/"aaaaa")
5. go to local couch database (couch.test.dev/_utils). note that user database has not been created!
6. sign out. data disappears as expected.
7. sign in. data does not reappear because it was not saved.
8. go to local couch database. note that user database is now present.

what should happen: as soon as a user record is created, user database should be created and all data synced.

**Comment by gr2m** [comment]
thanks for reporting this, I'll look into it

**Comment by gr2m** [comment]
Both @espy and me were not able to reproduce the problem. What system are you on again? Did you start the app right after the install, and went through the steps? Or did you go through the steps after some time? Maybe you hade your computer in sleep mode in between, I think there is a problem related to that. I've no other ideas at the moment.

**Comment by bbn** [comment]
Latest OS X (not at my machine right now). Nothing extra between steps - I reproduced it a few times just to be sure. 

I can do some debugging. Biggest clue is that user db is not created after initial sign up.

**Comment by espy** [comment]
I definitely had this exact problem once yesterday, but couldn't reproduce it later. I'm also looking it to it.

**Comment by gr2m** [comment]
So if the logs don't show any error, my guess is that the users-worker doesn't pick up _changes from _users database. What Node.js & CouchDB Version are you on?

**Comment by espy** [comment]
Node: v0.8.2
Couchdb - Apache CouchDB 1.2.1

I suspect that should be 1.3, no?

**Comment by janl** [comment]
1.2.x or 1.3.x shouldn’t make a difference.

**Comment by bbn** [comment]
I added a log statement to the _users changes callback and did some more testing.

created a user, see this in the logs: http://cl.ly/image/09362x1t2v2O
so it created the user database, but didn't put anything inside it.

also, maybe irrelevant, but the modal signup window did not close: http://cl.ly/image/1Q3X2f1k141i
this is despite other parts of the interface recognizing that I am logged in: http://cl.ly/image/1j1c0A1m2D0d

adding more data to the store at this point does not save anything to the DB.

if i sign out and sign back in, the items I created aren't there. no surprise, they weren't saved to the DB.
however if I now add a new item, I see for the first time a POST to /_api/.../_bulk_docs: http://cl.ly/image/0A1W0c0m2e0E

That didn't show up the first time. I'll try and track down where that gets short-circuited.

**Comment by bbn** [comment]
hoodie.remote.connected is false after I create a new account.

**Comment by bbn** [comment]
hi - just to be clear, this checkin does _not_ fix the issue of saving data properly. here's what i just did:
1. created a new hoodie 
2. started it up
3. verified the new code was in place (extra defer argument)
4. went to the URL
5. created a couple of todo items
6. signed up a new account
7. waited a few seconds
8. logged out. TODOs disappear.
9. logged back in with the same account. _TODOs do not reappear._
10. check the database. the data is not saved in the user's db.

**Comment by gr2m** [comment]
that I just fixed in #64.

**Comment by gr2m** [comment]
could you give it another try?

**Comment by bbn** [comment]
sorry, same steps, same result :( 
i'll just verify now that https://github.com/hoodiehq/hoodie.js/commit/2b8a938e64e5042a9b83a239678ad4b1b3b4bf37 is in the hoodie i just built... yes it is.

**Comment by bbn** [comment]
note that my steps are different than your steps to reproduce in #64.

**Comment by gr2m** [comment]
checking it ...

**Comment by gr2m** [comment]
can you update with latest [hoodie.js](https://raw.github.com/hoodiehq/hoodie.js/master/hoodie.js) and try again?

**Comment by bbn** [comment]
you bet. trying now...

**Comment by bbn** [comment]
hallelujah! fixed!
nice work @gr2m.
newest hoodie.js needs to make its way into the build. :)

**Comment by gr2m** [comment]
all pushed, cheers!
