### ISSUE TITLE
hapi usage: replace options.db with options.PouchDB

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#625]
refactor options for the hapi plugin usage to be coherent with @hoodie/server, @hoodie/store, @hoodie/account

eg. compare https://github.com/hoodiehq/hoodie#hapi-plugin with https://github.com/hoodiehq/hoodie-server#usage

**Comment by Taekyoon** [comment]
@gr2m I'll take this one!

**Comment by gr2m** [comment]
oh hey @Taekyoon I actually made a camp issue for it: https://github.com/hoodiehq/camp/issues/51 Can you ask Jean there if she still wants to work on it? If yes I am happy to help find something else for you to work on, if not it’s all yorus :)

I’ll close this issue in favor of https://github.com/hoodiehq/camp/issues/51
