### ISSUE TITLE
A new store object's attachment isn't available when the corresponding 'add'-event arrives

### ISSUE THREAD

**Issue by espy** [hoodiehq/hoodie#63]
To test: 

Listen for the add event of a store object with an image attachment and then attempt to display that attachment (this assumes that the attachment filename is saved as `image.name`, otherwise you'll have to get it with `Object.keys(image._attachments)[0];` or something like that):

```
hoodie.store.on('add:image', function(image){
  var imgSrc = hoodie.baseUrl + "/user%2F" + image.createdBy + "/image%2F" + image.id + "/" + image.name
  var img = new Image();
  img.src = imgSrc;
  $('body').append(img);
});
```

The request for the image will 404 unless you add a small timeout. Expected behaviour would be for the DB to send the 'add' event only after the complete object, including attachments, is actually available. 

Not sure who should get this, possibly @janl

**Comment by gr2m** [comment]
Okay, just for reference, this is what happens:
- You create a new `image` object and use the CouchDB schema to add an attachment to it
- You listen to the `add:image` event, which gets fired right after it was stored locally
- You try to access image from remote, although it was not even synced yet.

Maybe we should step away a little bit and ask ourselves what you try to accomplish and what a nice API for it would be?

One idea we had was to add an event that gets triggered when an object got synced, like `hoodie.store.on('synced:image:id123', callback)`.

The other idea would be to provide an own api for uploads, as a hoodie extension. That'd also abstract away the schma that CouchDB uses, what we try to do with all the other API as well.

So what you think? Maybe let's start by creating a dreamcode for your use case, [noBackend Style](http://nobackend.org/dreamcode)? ;-)

**Comment by espy** [comment]
Makes sense. I think the problem is that the sync issue isn't really transparent or even obvious, I'd suspect (dangerous) that most people would just expect objects with attachments to behave like objects without attachments (because, on all clients except the one the attachment was uploaded from, they already do anyway). 

But I like your idea for an upload API, as it would hide the mimeType bits and magic number awkwardness like

```
content_type: mimeType,
data: event.target.result.substr(13 + mimeType.length)
```

But that might not really help with the events, since we ideally want to use the same listener on all clients, not a special upload listener on the uploading client and a normal add/change listener on the others, when the result is essentially the same.

What use cases can you think of where you'd explicitly want the result you currently get (event fires when data is stored, independent of attachments)? I think I'm a bit stuck in my perspective atm.

**Comment by gr2m** [comment]
I can't think of any other use case where I'd need this event, really. All I need to know is: are there any local changes, that have not been synced yet or not, that I can check with `hoodie.store.isDirty()`.

Why no add an upload module? Something like

``` js
// open dialog, let user select a file
hoodie.upload().then( showImage ) 

// set the filename that gets used when uploaded. Also sets filter for dialog
hoodie.upload("image.png").then( showImage )

// more complex settings
hoodie.upload({
  filter: "*.png,*.jpg,*.gif",
  filename: "image",
  multiple: true
}).then( showImage )

// upload a file via url
hoodie.upload( "http://exam.ple/path/to/image.png" ).then ( showImage )
```

Thoughts?

**Comment by svnlto** [comment]
Closing for now, please reopen if still needed.
