### ISSUE TITLE
npm install --save hoodie: do not overide "start" script in package.json

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#636]
when installing `hoodie`, it runs a setup in `postinstall`. Among other things, it sets the "start" script (via https://github.com/hoodiehq/hoodie/pull/592)

But if the "start" script is already set, it currently gets overwritten, which it shouldn’t do

**Comment by Taekyoon** [comment]
Hey Greg, can I grab this? but I have little knowledge dealing with it.

**Comment by gr2m** [comment]
Sure, give it a try! The relevant line is this one: https://github.com/hoodiehq/hoodie/blob/8fa80e1b1ac192c18766b2d8e189529f8c003029/bin/setup.js#L18: Instead of simply setting `packageJson.scripts[ 'start' ]` we should check if `packageJson.scripts[ 'start' ]` is already set. If it is
1. do not set it to `'hoodie'` and and add a `log.info('setup', 'start script already set to "' + packageJson.scripts[ 'start' ] + ', you can start hoodie with "npm run start-hoodie" instead`
2. set `packageJson.scripts[ 'start-hoodie']` to `hoodie` instead.

Makes sense?

**Comment by Taekyoon** [comment]
@gr2m Greg, I've finished adding statements as you said following your comment. And I want to verify and test this codes to check if it works well. How to implement this test codes on the project? I think there's no test code for `setup.js`.

**Comment by gr2m** [comment]
@Taekyoon wanna add a test as part of the PR?

**Comment by Taekyoon** [comment]
@gr2m If I can show my PR, that would be better, but more important thing is that I'm not sure whether my codes will work well. So, I just wanna check is the codes run properly.

**Comment by gr2m** [comment]
that’s totally normal, start a pull request and we can discuss there :)

**Comment by gr2m** [comment]
done via https://github.com/hoodiehq/hoodie/pull/642
