### ISSUE TITLE
Hoodie Client: replace PouchDB dependency with options.PouchDB

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#643]
We want the Hoodie Client to not only run in browsers, but also on servers (server-side rendering) and in Service Workers. We are currently [removing `@hoodie/client-store`'s dependency on `PouchDB`](https://github.com/hoodiehq/hoodie-store-client/issues/134) by replacing it with `options.PouchDB`

This will also give developers more control about the used PouchDB version and [custom build](https://pouchdb.com/custom.html). Only `hoodie` should have a dependency on PouchDB, all lower-level dependencies should work with options.

- [ ] depends on https://github.com/hoodiehq/hoodie-client/pull/107

**Comment by Taekyoon** [comment]
@gr2m Can I take this issue, instead of PR? 
And, I'll ask you about what PR is.

**Comment by gr2m** [comment]
@Taekyoon I’m already working on this one, here is the work-in-progress pull request: https://github.com/hoodiehq/hoodie/pull/644

**Comment by Taekyoon** [comment]
I got it!
