### ISSUE TITLE
Hoodie Account: Can't Sign Out

### ISSUE THREAD

**Issue by lauralindal** [hoodiehq/hoodie#647]
I'm using Hoodie on Linux Mint in Firefox and tried the account API by signing up, signing in and trying to sign out via my dev console in the browser. 

SignUp and SignIn work fine, but SignOut doesn't work. All I get is a Promise but it never comes through.
![screenshot from 2016-12-01 16 12 42](https://cloud.githubusercontent.com/assets/5703164/20829298/cd364ebe-b87b-11e6-9b0f-835b0fdbf094.png)

I would expect that eventually, I'll get a ```false``` when checking if signed in.

Further data: Using Hoodie (24.3.0), node (6.9.1), npm 3.10.8., Firefox (50.0), Linux Mint (17.3).

**Comment by gr2m** [comment]
Thanks a lot Laure for filing the bug with all the details! I’ve installed the [tracker app](https://github.com/hoodiehq/hoodie-app-tracker) and tried it with the latest hoodie version as well as `24.3.0` and Firefox (50.0.2), but could not reproduce the `Authorization header missing` error. Did you maybe test it in a private window? Hoodie does not work in Firefox private windows right now, but you should see another error in that case ...

Can you please try to `rm -rf node_modules && npm install` to do a fresh install? The latest Hoodie version is `24.3.5`, maybe that will help already? 

I unfortunately don’t have Linux myself, I hope we can figure this out anyway :)

**Comment by lauralindal** [comment]
So apparently, it works on Windows in Chrome with node 6.9.1 and npm 3.10.8, with Hoodie 25.3.0 - but after updating Hoodie, it now also works on my firefox & setup :)

**Comment by gr2m** [comment]
okay, glad it works now 👍 Thanks a lot for following up & testing, much appreciated!

**Comment by lauralindal** [comment]
I finally could reproduce the error.

We are using webpack to build and nodemon to hot-reload the sources. The error occurs on every re-build. I guess, because the session is not valid any more? The account is gone and this is why I get a 401 and can't logout again. The user id is still stored in the localStorage. (No idea, if this is important or related). 

After recreating the account, it works again and login as well as logout work. Until the next change in the code and the next reload.

**Comment by gr2m** [comment]
That should still be no problem, unless you also restart the server and you run it with `--inMemory`
