### ISSUE TITLE
Shares with remote hoodie instances

### ISSUE THREAD

**Issue by caolan** [hoodiehq/hoodie#65]
I would love to be able to:

``` js
hoodie.share(share_id, 'http://remote.hoodie.instance').subscribe()
```

Then, we could each run a local instance of our little app and still have social features like sharing photos without having to rely on a centralised service.

This idea also implies something like:

``` js
share.grantReadAccess('joe@example.com', 'http://remote.hoodie.instance');
```

So you can share with users on remote instances... There are likely to be many more implications that I've not thought through yet, I just wanted to record this idea somewhere!

**Comment by gr2m** [comment]
Thirst thought: love it.
Second thought: I'd simplify the API

``` js
hoodie.share('http://remote.hoodie.instance/share_id').subscribe()
```

Third thought: technical question:
Can I secure my share, so that it's not public read but only accessible by certain users? And can I pass user auth, so that I get a continuous replication to a remote share, that also authenticates with passed credentials? e.g.

``` js
hoodie.share('http://remote.hoodie.instance/share_id', { user: "gregor", pass: "secret" }).subscribe()
```

**Comment by caolan** [comment]
Ideally you wouldn't need an account on the remote instance. So perhaps we generate a token for each user you want to share with? Then they enter the token when they subscribe to the share? ...kind of like BitTorrent Sync or Bitcoin

**Comment by caolan** [comment]
Perhaps something like this?

``` js
hoodie.share('http://remote.hoodie.instance/share_id').subscribe(my_token)
```

**Comment by gr2m** [comment]
btw, there already is `hoodie.open( pathOrUrl )`. This provides you a Store API, e.g.

``` js
caolansStuff = hoodie.open('http://caol.en/stuff' )
caolansStuff.findAll( showCaolansStuff )
caolansStuff.on('change', handleNewStuffByCaolan )
caolansStuff.connect()
```

`hoodie.store` is just a shortcut for `hoodie.open`. So auth & tokens should rather be passed when the store gets "opened", so it can be passed to all its requests. Thoughts?

**Comment by gr2m** [comment]
moved to backlog
