### ISSUE TITLE
Missing authorization header with `@hoodie/client` dependency

### ISSUE THREAD

**Issue by sdvg** [hoodiehq/hoodie#652]
I found this mysterious issue: When I have both `hoodie` and `@hoodie/client` in my package.json, all PouchDB API requests lack the `authorization` header and fail with a 401 Unauthorized response.

I built a simple test case for that. Steps to reproduce:

```
git clone https://github.com/sdvg/hoodie-authhe-bug.git
cd hoodie-authhe-bug/
npm install
npm start -- --in-memory
```

Then open a browser tab with http://localhost:8080/ and open the console. You should see something like:

> Signed up!
> Signed in!
> GET http://localhost:8080/hoodie/store/api/user%2F1aaxotp/ 401 (Unauthorized)
> GET http://localhost:8080/hoodie/store/api/user%2F1aaxotp/ 401 (Unauthorized)
> GET http://localhost:8080/hoodie/store/api/user%2F1aaxotp/ 401 (Unauthorized)
> [...]

When you inspect one of the failing requests you should see that there is no "authorization" request header.

**Comment by gr2m** [comment]
I was able to reproduce the error, looking into it

**Comment by gr2m** [comment]
Notes to self:

- looks like the new `ajax.headers` getter is not executed, which was recently introduced here: 
https://github.com/hoodiehq/hoodie-client/commit/6c7b9316803f1156494607dec50db2cfb8db14ec#diff-e4208702c8e33245e2fe39ecc5e37004R32
- latest `hoodie` depends on `@hoodie/client@^7.0.0`, not `@^8.0.0`: https://github.com/hoodiehq/hoodie/blob/83c4dc316c3ab0558c52602f6c041260b63013e7/package.json#L16. When changing the version to `^7.0.0` in the `package.json` then things work as expected

**Comment by gr2m** [comment]
Unrelated to this issue, I found another bug: https://github.com/hoodiehq/hoodie-server/issues/524 :)

**Comment by gr2m** [comment]
okay seems like this is the problem: https://github.com/pouchdb/pouchdb/issues/6053. I’ll fix it in `@hoodie/store-client`

**Comment by gr2m** [comment]
@sdvg should be fixed via https://github.com/hoodiehq/hoodie-client/releases/tag/v8.0.1 and https://github.com/hoodiehq/hoodie-store-client/releases/tag/v6.0.2. `rm -rf node_modules && npm install` should fix it for your case

**Comment by sdvg** [comment]
Yes, that fixed it 🎉 
Thank you!
