### ISSUE TITLE
404 on link

### ISSUE THREAD

**Issue by gautamkrishnar** [hoodiehq/hoodie#656]
The link  http://go.hood.ie/hoodie-starter-issues displayed on hoodie [github org](https://github.com/hoodiehq) is showing a 404. 

Please make changes to the link

**Comment by gr2m** [comment]
fixed, thanks! We now have a dedicated repository with prepared issues for new and existing contributors: https://github.com/hoodiehq/camp/issues?q=is%3Aopen+is%3Aissue+label%3A%22up+for+grabs%22

**Comment by gautamkrishnar** [comment]
:smile: :+1:
