### ISSUE TITLE
Add documentation for docs contributors / maintainers

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#660]
follow up for https://github.com/hoodiehq/discussion/issues/109#issuecomment-270891487

Every page on http://hoodie.readthedocs.io/ has an "Edit on GitHub" button on the top right corner, so making small changes should be no problem. But for bigger changes, we should document on how to setup / build the documentation locally. 

Read The Docs is using [Sphinx](http://sphinx-doc.org/) which is a Python project. This Question might be relevant, too http://docs.readthedocs.io/en/latest/faq.html#i-want-to-use-the-read-the-docs-theme-locally

**Comment by gr2m** [comment]
How about we add a `docs/README.md` file that will be shown on GitHub when opening the [docs folder](https://github.com/hoodiehq/hoodie/tree/master/docs), with information on what this folder is, how things work, how to contribute and how to setup it up locally?

**Comment by ThomasWaldmann** [comment]
Not sure if this helps, but see yourself:

See there about how we build local / on rtfd: https://github.com/borgbackup/borg/tree/master/docs

- we have slightly customized the readthedocs theme (logo, colours)
- see also our docs, development section about how to build the docs

**Comment by fozy81** [comment]
+ for to add documentation for docs contributors / maintainers

We could get a little more testing functionality out of Sphinx beyond flagging dead url links. For example by adding a [spell checking module](https://doughellmann.com/blog/2011/05/26/creating-a-spelling-checker-for-restructuredtext-documents/) too? - I know my spelling is bad! Perhaps travis CI can run the checks on the pull request? 

Beyond that, there's some interesting technical document testing ideas mentioned in this blog post https://www.mapbox.com/blog/retext-mapbox-standard/

**Comment by gr2m** [comment]
great idea! And yes, I’m sure we can add more checks to our travis builds :)

**Comment by fozy81** [comment]
I like the idea to treat 'docs-as-code'. There's a interesting plain [text linter](https://github.com/textlint/textlint) which can test for all types of typos and errors. It also works with [rst](https://github.com/jimo1001/textlint-plugin-rst). 

Open Stack docs has a nice [style guide](http://docs.openstack.org/contributor-guide/writing-style/general-writing-guidelines.html) for technical docs. Maybe of interest, to people new to writing docs (like me!).
