### ISSUE TITLE
Quick Start error

### ISSUE THREAD

**Issue by quangv** [hoodiehq/hoodie#663]
Hi, I was trying to follow the [quick-start guide](http://docs.hood.ie/en/latest/guides/quickstart.html#create-a-new-hoodie-backend).

I got the following error:

```
> npm start

> decide@0.0.1 start /home/quang/dev/decide
> hoodie


/home/quang/dev/decide/node_modules/hoodie/bin/start.js:9
    throw error
    ^
OpenError: IO error: .hoodie/data/hoodie-config/LOCK: No such file or directory
    at /home/quang/dev/decide/node_modules/hoodie/node_modules/pouchdb-adapter-leveldb/node_modules/levelup/lib/levelup.js:119:34
    at /home/quang/dev/decide/node_modules/hoodie/node_modules/pouchdb-adapter-leveldb/node_modules/leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:39:16

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE
npm ERR! decide@0.0.1 start: `hoodie`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the decide@0.0.1 start script 'hoodie'.
npm ERR! This is most likely a problem with the decide package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     hoodie
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs decide
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls decide
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/quang/dev/decide/npm-debug.log
```

I'm using node version v4.4.7

my package.json is https://github.com/quangv/decide/blob/master/package.json

**Comment by gr2m** [comment]
Thanks for reporting the issue, I could just confirm it locally. I’m very sorry that this slipped trough our QA!

Can you try to create the folder `.hoodie/data/hoodie-config` (you can use `mkdir -p .hoodie/data/hoodie-config`) and see if that resolves the problem for you?

**Comment by quangv** [comment]
@gr2m Thanks! yes that fixed it.

**Comment by gr2m** [comment]
Great, thanks for letting us know! 

For reference, here is a description of the bug causing the problem you run into: https://github.com/hoodiehq/hoodie-server/issues/529. If you like, I’d be happy to help you land a fix for it? No worries if not, I’m sure we get this resolved soon.

Thanks again for reporting it!

**Comment by quangv** [comment]
> I’d be happy to help you land a fix for it? 

@gr2m it's okay, I'm sure you can fix it 100x faster than I could. :blush:

**Comment by gr2m** [comment]
> it's okay, I'm sure you can fix it 100x faster than I could. 😊

surely, but gotta grow the community :)

**Comment by kevinkhuat** [comment]
@gr2m Is this still an issue? I ran through the quick start and got an error, but I got a different message. I wouldn't mind working on a fix for it as well. Let me know.


`$ npm start

> testapp@1.0.0 start ..//testapp
> hoodie

..//testapp/node_modules/hoodie/bin/start.js:9
    throw error
    ^

Error: listen EADDRINUSE 127.0.0.1:8080
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1257:14)
    at listen (net.js:1293:10)
    at net.js:1403:9
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

`

**Comment by kevinkhuat** [comment]
@gr2m 

I think I figured out why I'm having the issue. I'm already using port 8080. So this should work if I keep it open.

**Comment by gr2m** [comment]
thanks for letting us knwo @kevinkhuat 👍 

I think this issue has been resolved meanwhile, thanks!
