### ISSUE TITLE
Config hoodie/dbUrl not accepted when password contains some special chars

### ISSUE THREAD

**Issue by gicelte** [hoodiehq/hoodie#668]
Let's say dbUrl is set to https://USERNAME:PASSWORD@ACCOUNTNAME.cloudant.com/

If PASSWORD contains is too complicated (contains slashes, semicolon - chars have to be discovered as I did not test them specifically!) the app cannot start and the following error is thrown:

Error: Authentication details missing from database URL

**Comment by Manosmer** [comment]
When you are trying to make a basic http auth (via url), username's and password's special characters are being encoded into url encoding (e.g. symbol `@` becomes `%40`). Maybe that's the case?

**Comment by Manosmer** [comment]
For example if you are trying to login with an email-type username, like "john@doe.com" then you have to write `https://john%40doe.com:PASSWORD@ACCOUNTNAME.cloudant.com/`

**Comment by mbad0la** [comment]
@gr2m , I feel the solution proposed by @Litarhis is a good one. What do you think?

**Comment by gr2m** [comment]
yes that is correct. I would like to implement a better error if you use a special non-encoded character in the username or password. We could give an explanation about encoding in there or link to this issue. Anyone want to work on this?

**Comment by Manosmer** [comment]
@gr2m, I would like to give it a try if that is possible. This would be my first PR ever so I may need a little bit more time to finish the project. Also there are two versions that can solve that issue; we can log a relevant error back to the console or we can automatically encode the given URL string before using it without forcing the user to care about encoding. I think the second solution fits more to the ideology of hoodie, as it provides a solution closer to the out-of-the-box model.

**Comment by gr2m** [comment]
Hey @Litarhis the issue is all yours :) And welcome to Hoodie and Open Source, we are delighted that you consider to send your first PR to our humble community! I’ve invited you as a contributor, once you accept the invitation you can assign the issue to yourself.

I would love to see if you can manage to to automatically encode the given URL, it’s worth to give it a try :)

**Comment by Manosmer** [comment]
@gr2m Thanks! I'll try my best on this one! hehe. My idea consists of modifing the dbUrl option and breaking it to 3 pieces: username, password, database address. That is the only way to achieve auto-encoding, because password or username can include the symbol `:` and if that's the case, we can't separate the username from the password, because we wouldn't know which one of the `:` symbols is the separator.

**Comment by Manosmer** [comment]
hello, @gr2m. I think I finished the code needed for fixing this issue, but I have some difficulties. At first sorry for the inconvenience of "playing" with the milestones in this issue post. I am new here 😛 . Secondly, I am new at testing and I don't know exactly how to do it the right way. I use `npm test` but then command line gives the following message: `Reading TAP data from stdin (use "-" argument to suppress)` and it just repeats what I write. Also, have you read my previous message on this issue? The idea is to break the `--dbUrl` into three arguments; `--username`, `--dbAddress`, `--pass`. This will break backwards compatibility for developers that were using --dbUrl. But dbUrl should be deprecated as it can't be controlled and fixed by code, as I mentioned in my previous message.

**Comment by gr2m** [comment]
I would like to keep a single option `--dbUrl` as it works for most common cases. But we could add two extra options `--dbUrlUsername` & `--dbUrlPassword` for people who have weird characters in their URL? We can also mention these two in the error message that we throw if we can’t read a valid URL out of `--dbUrl`. Both `--dbUrlUsername` and `--dbUrlPassword` could be optional. You could for example have the username in `--dbUrl` but then set the password separately `--dbUrlPassword`

Would that work?

> "playing" with the milestones

Don’t worry :) But please discuss with us first before working managing labels or milestones. I would recommend not to mess around with these things in other projects, people might react badly :) Like you come to their house and then decide to change the furniture in their living room while they are out shortly :D No worries, but if you could remove the milestones again, that’d be great. Happy to chat about your ideas though

> I use npm test but then command line gives the following message: Reading TAP data from stdin (use "-" argument to suppress) and it just repeats what I write. Also, have you read my previous message on this issue?

Hmmmmm ... can you tell me the node & npm version you are using? `node -v && npm -v`. If your node  version is older than 6,  consider to update to the latest LTS version: https://nodejs.org/en/

**Comment by Manosmer** [comment]
@gr2m yeah... sorry if I created any trouble with the labels. It's that I see that everyone uses them very rarely and they are so helpful.

> But we could add two extra options --dbUrlUsername & --dbUrlPassword for people who have weird characters in their URL?
> You could for example have the username in --dbUrl but then set the password separately --dbUrlPassword

Yes and no haha. We can find a solution in the middle of these two. We can leave `--dbUrl` as there are a lot of people using it right now (but please, mark it as deprecated as it's uncontrollable) and support the other 2 new arguments `--dbUrlUsername` & `--dbUrlPassword`. But I am afraid we can't do the second one which is the ability to provide username in the url and password afterwards. Although, I already created the option to provide username, username & password, or none of them in the URL so it is not so hard to make them optional (password requires username to be provided, thus I do not refer to it separately from username).

> Hmmmmm ... can you tell me the node & npm version you are using? node -v && npm -v. If your node version is older than 6, consider to update to the latest LTS version: https://nodejs.org/en/

`npm: 3.10.9`
`node: 6.9.2`

**Comment by gr2m** [comment]
I think we can do it without deprecating `dbUrl`.

Here is a test script to demonstrate how I think we could introduce `dbUrlUsername` and `dbUrlPassword` as additional options without breaking current behavior

```js
// npm install yargs
var argv = require('yargs').argv
var url = require('url')

console.log('\nARGV ===========================================================')
;[
  'dbUrl',
  'dbUrlUsername',
  'dbUrlPassword'
].forEach(key => console.log(`${key}: ${argv[key] || ''}`))

const {
  hostname,
  port = 80,
  auth = ''
} = url.parse(argv.dbUrl, null, 2)

console.log('\nparsed dbUrl ===================================================')
console.log(`hostname: ${hostname}`)
console.log(`port: ${port}`)
console.log(`auth: ${auth || ''}`)

let [
  username = '',
  password = ''
] = (auth || '').split(':')

if (username.length + password.length + 1 < auth.length) {
  console.log('\nERROR =========================================================')
  console.log('Could not parse username & password from dbUrl. Please try setting dbUrlUsername and dbUrlPassword instead')
  process.exit(1)
}

username = username || argv.dbUrlUsername
password = password || argv.dbUrlPassword

if (!username) {
  console.log('\nERROR =========================================================')
  console.log('Could not find username in dbUrl or dbUrlUsername')
  process.exit(1)
}

if (!password) {
  console.log('\nERROR =========================================================')
  console.log('Could not find password in dbUrl or dbUrlUsername')
  process.exit(1)
}

console.log('\nUSERNAME / PASSWORD from auth & dbUrlUsername, dbUrlPassword ===')
console.log(`username: ${username}`)
console.log(`password: ${password}`)
```

Here a few example runs (reduced output for readability)

```
$ node test.js --dbUrl="http://example.com"
Could not find username in dbUrl or dbUrlUsername

$ node test.js --dbUrl="http://foo@example.com"
Could not find password in dbUrl or dbUrlUsername

$ node test.js --dbUrl="http://foo:secret@example.com"
username: foo
password: secret

$ node test.js --dbUrl="http://foo:sec:ret@example.com"
Could not find username & password in dbUrl. Please try setting
dbUrlUsername and dbUrlPassword if either contains special characters like : or @

$ node test.js --dbUrl="http://foo@example.com" --dbUrlPassword=sec:ret
username: foo
password: sec:ret

$ node test.js --dbUrl="http://example.com" --dbUrlUsername=f@?/oo --dbUrlPassword=sec:ret
username: f@?/oo
password: sec:ret
```

**Comment by Manosmer** [comment]
@gr2m, hmmm... I see.. I was wrong. I was mistakenly believing that you can omit password in http auth. But, in reality the url has to follow the format: `https://<username>:<password>@url/somethingElseMaybe`

I will implement 2 possible ways of connecting to an externat db. The first one would be the one everyone was using. The second will be to provide the database url with --dbUrl (e.g. `https://mydatabase.com/testDB` and provide the credits seperately via --dbUrlUsername and --dbUrlPassword. I already succeded at doing the second way, so I just have to retype the original code.  

`$ node test.js --dbUrl="http://foo@example.com" --dbUrlPassword=sec:ret
username: foo
password: sec:ret`

For that bit, is it really useful? I mean are there any users that will provide the username in the url and later the password via --dbUrlPassword?

Also, have you figured out why `npm test` does not work? I updated nodejs to the latest LTS version and I reinstalled the dependencies... Nothing worked for me

**Comment by gr2m** [comment]
> For that bit, is it really useful? I mean are there any users that will provide the username in the url and later the password via --dbUrlPassword?

yes, because most ofthen the password is the one that has the special characters

> Also, have you figured out why npm test does not work? I updated nodejs to the latest LTS version and I reinstalled the dependencies... Nothing worked for me

no, unfortunately not, this is super odd. Can you please make a separate issue for that? I’ve to log off for today, I’ll be back tomorrow

**Comment by Manosmer** [comment]
Hello @gr2m . Thank you for your help so far. I am having trouble with testing and this made me have some thoughts. The algorithm I created takes as a `--dbUrl` only URLs starting with 'https'. According to this document: https://www.httpwatch.com/httpgallery/authentication/ , we can have 2 different possibilities; either **basic http auth** with 'https' URL, in which password is being provided in plain text base64 format, or **digest http auth** with 'http' URL, in which the user has to provide the password already hashed (I am not talking about NTLM as it may produce lots of errors and thus it's not common). Should I implement code for these 2 occasions or shall I stay with the basic http auth?

NOTE: if we choose to implement only "https" URLs (in other words **basic http auth**) test cases should change and URLs starting with "http" should throw an error

NOTE 2: actually, we can use **basic http auth** with "http" URLs, but it's unsafe, so we can log a warning every time a user uses "http"

**Comment by gr2m** [comment]
We must support http for local development and deployments where the CouchDB lives on the same machine / same network as the hoodie process.

As far as I know, basic auth means using the `Authorization` header and sending username & password as a base64 encoded string. We pass it directly into the URL. It should be no problem for us.

I suggest we should take both http:// & https:// URLs and assume the user knows what they are doing

**Comment by Manosmer** [comment]
@gr2m, thought so, did so 😛
