### ISSUE TITLE
removed objects remain in localStorage._dirty

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#67]
when removing an object, it should get remove from the _dirty key of localStorage after it got pushed. It isn't at the moment.

See also: https://github.com/hoodiehq/hoodie.js/issues/57

**Comment by janl** [comment]
Just to understand this, do you mean to say you don’t want to have the fact that an object was deleted replicated back to the server?

**Comment by gr2m** [comment]
no, it's about that deleted objects do not get properly cleaned up locally
