### ISSUE TITLE
Exception when trying to add document with ID that existed before

### ISSUE THREAD

**Issue by sdvg** [hoodiehq/hoodie#672]
When you add a document, remove it and try to insert an object with the same ID again, the following exception gets thrown:

> Object with id "test" already exists

Code to reproduce:

```javascript
const add = () => {
    return hoodie.store.add({ id: 'test' });
};
const remove = () => {
    return hoodie.store .removeAll();
};
hoodie.ready.then(() => {
    add()
    .then(remove)
    .then(add);
});
```

**Comment by gr2m** [comment]
can you try this?

```javascript
const add = () => {
    return hoodie.store.add({ id: 'test' });
};
const remove = () => {
    return hoodie.store .removeAll();
};
hoodie.ready.then(() => {
    remove()
    .then(add)
    .then(remove)
    .then(add);
});
```

I think the 2nd `add()` is not the problem. A document with id `test` already exists when you run the first `add()`, and it won’t let you add document with an existing id

**Comment by sdvg** [comment]
Yes, this works. Looks like I didn't test properly, I can't reproduce the issue anymore.
Thanks for looking at it.
