### ISSUE TITLE
Update docs: deployment to now

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#684]
Add information based on our most recent blog entry: 
http://hood.ie/blog/single-line-deployment.html

I would suggest a separate section for Cloudant, as it is not now-specific, and we could for example add a Heroku section, too.

**Comment by fozy81** [comment]
Created this pull request based on one line deploy blog post https://github.com/hoodiehq/hoodie/pull/685 @gr2m

**Comment by gr2m** [comment]
done via https://github.com/hoodiehq/hoodie/pull/685
