### ISSUE TITLE
[Docs] Problem in "Options" table rendering

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#686]
there seems to be a syntax issue in [hoodie/docs/guides/configuration.rst ](https://github.com/hoodiehq/hoodie/blob/f6dcd1da7b8467ee349935da6c98eaa249b72ca6/docs/guides/configuration.rst), see the table on http://docs.hood.ie/en/latest/guides/configuration.html (it’s also not rendered correctly on GitHub itself)

<img width="845" alt="screen shot 2017-02-09 at 20 51 53" src="https://cloud.githubusercontent.com/assets/39992/22810905/9f1ec500-ef09-11e6-9937-d4076828b863.png">

**Comment by fozy81** [comment]
Fixed https://github.com/hoodiehq/hoodie/pull/688 - slowly getting the hang of .rst syntax! :-)

**Comment by gr2m** [comment]
@fozy81 instead of closing the issue manually, you can add `closes #686` to the pull request and when we merge it, this issue gets closed automatically. See https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by fozy81** [comment]
@gr2m sure, no problem. Will do next time.
