### ISSUE TITLE
options.db.url is not specified

### ISSUE THREAD

**Issue by Manosmer** [hoodiehq/hoodie#699]
Where does options.db.url is being initialized and set, in order to be used at https://github.com/hoodiehq/hoodie/blob/master/cli/parse-options.js#L51 ?

Is that some sort of left-over code from previous fixes? Have I found a bug?

**Comment by gr2m** [comment]
ohhh yes, we used to pass `options.db` into `@hoodie/server`, but now we pass in a `options.PouchDB` instead. You totally found a bug, we must have missed that :)

**Comment by Manosmer** [comment]
Worry no more. My code for  #668 fixes this error too.

**Comment by gr2m** [comment]
it would be great if you could send a separate PR for this bug. Smaller PRs are much easier for others to review and merge. But don’t worry this time, I think we’ll be fine :) just in general, small PRs always work better

**Comment by Manosmer** [comment]
Then I will do so! 😄
