### ISSUE TITLE
Implement frontend API for CouchDB views

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#70]
This is what we got, it just needs to get wired. Shouldn't be too hard
- https://github.com/hoodiehq/hoodie.js/blob/master/src/core/remote.coffee#L20
- https://github.com/hoodiehq/hoodie.js/blob/master/src/core/remote.coffee#L102

**Comment by mstefaniuk** [comment]
Worth to consider simplified key value support:
- JSON.stringify for array / object values of keys
- building proper startkey / endkey values from single key when non-couch-hoodie-option `range` is set to `true` (sensitive do `descending` option as well)

**Comment by gr2m** [comment]
could you make up some dreamcode, to express how you'd like to work with CouchDB views? The most simplest I could think of is 

``` js
hoodie.open('dbname').get('view_name').then( handleResult )
```

**Comment by mstefaniuk** [comment]
When a custom database skeleton is used then design doc should be pointed (or one desing document with fixed name allowed).

Getting reference to a view:

```
var v = hoodie.open('dbname').view('ddoc','view');
```

Getting full contents of a view:

```
v.get().then( handleResult );
```

Getting of filtered view with automatic range generation:

```
v.get({
  key: [1,"04011408"],    // it would become startkey=[1,"04011408"]&endkey=[1,"04011408",{}]
  range: true
}).then( handleResult );
```

Getting first page of results with 10 elements:

```
v.get({
  key: "que",    // it would become startkey="que"&endkey="que\ufff0"
  range: true,
  rows_per_page: 10,  // actual size would be 11 (one for paging)
}).then( handleResult );
```

Getting next page of results with 10 elements:

```
v.get({
  rows_per_page: 10,  // actual size would be 11 (one for paging)
  page: paging_row     // last complete row returned from previous call
}).then( handleResult );
```

To make paging clear `handleResult` function should accept two parameters - `rows` and `paging`. The latter would be provided if `rows_per_page` is defined and would be simply popped from rows array. Actually `paging` may not be a full row but simple `startkey` and `startkey_docid`. Idea is that paging object would simply passed to next get().

**Comment by gr2m** [comment]
I'd like not to use `view` in the API, as it's very CouchDB specific, the rest of the Hoodie API is not. Maybe we could do something like

``` js
hoodie.open('dbname').get('ddoc/view', params).then( function( results, meta) {} )
```

And params could be all kind of options, they'll get simply passed as url query parameters. The callback would get the `results` array in results, and meta would get `{total_rows, offset}`.

What you think?

**Comment by mstefaniuk** [comment]
It's not so convenient but simple and powerful. For me it is enough.

**Comment by gr2m** [comment]
All right, let's do it then

**Comment by janl** [comment]
maybe we can hide it one layer down, something like `hoodie.internal.db.open().view()...` just to make clear that if you know what you are doing all is well, but that this isn’t yet an official part of the main API.

**Comment by mstefaniuk** [comment]
My idea was to provide simple-as-hoodie interface for CouchDB features (views, roles). Payments, accounts, emails, document notifications and why not DB queries? Do you plan to support other NoSQL?
I think `store` is good place for that but maybe not `get()` - rather `query()` would be better (if not `view()`).

**Comment by janl** [comment]
@mstefaniuk this is an excellent suggestion!

The reason I’d suggest keeping lower level things like querying a database to a lower level in the API is that Hoodie’s target audience are not capable programmers, but more frontendy/designery/UXy types who don’t want to and shouldn’t have to worry about databases and queries and all the mundane things that more seasoned programmers enjoy so much.

As a result, my suggestion is to keep the high-level Hoodie API clean from tech-isms that aren’t relevant to frontend application developers, while giving the experts an API to do whatever they want, it’s just not in the high-level API.

So yeah, tl;dr: we are trying to avoid confusion here, while still enabling advanced features.

**Comment by gr2m** [comment]
We just discussed the topic. Our thoughts are:
1. We don't see use cases for update handlers at the moment, so we'll leave them out for now
2. We'll add a method `query`, that can be used to query named views

So we could do something like `hoodie.remote.query('stats/by_type')`. `stats` would be the name of the `_design` object, `by_type` would be the name of the view.

Cool?

**Comment by gr2m** [comment]
We had another thought, to make things even more simple. 

Hoodie will expect a design doc with `"_id": "_design/views"`, so what gets passed to `hoodie.remote.query` is the name of the view only. So to query all objects by their type, the code could look like: `hoodie.remote.query('by_type')`, where `by_type` is the name of the view.

**Comment by mstefaniuk** [comment]
I like the last one.

**Comment by gr2m** [comment]
closing and moving this to [Backlog](https://github.com/hoodiehq/hoodie.js/issues?milestone=2&state=closed)
