### ISSUE TITLE
npm test does not work

### ISSUE THREAD

**Issue by Manosmer** [hoodiehq/hoodie#700]
When I give the command `npm test` to the command line after a while the batch freezes as it is seen in the attached photo:
<img width="674" alt="clitap" src="https://cloud.githubusercontent.com/assets/15073846/23344066/87652738-fc7e-11e6-9fa7-8d6fe342efbc.PNG">

When I write something and hit enter the console logs it back.

System: Windows 10 64-bit
NodeJS: 6.10.0 LTS
npm: 3.10.10

**Comment by gr2m** [comment]
Can you please try run tap directly?

```
./node_modules/.bin/tap './test/{unit,integration}/**/*-test.js'
```

It might be that for Windows you need to use backslashes instead?

```
.\node_modules\.bin\tap './test/{unit,integration}/**/*-test.js'
```

If that is not working, can you try to run a single test file directly with node?

```
node .\test\integration\smoke-test.js
```

If that works try

```
.\node_modules\.bin\tap .\test\integration\smoke-test.js
```

**Comment by Manosmer** [comment]
On the first command I terminated the batch with Ctrl+C

<img width="674" alt="tapproblem" src="https://cloud.githubusercontent.com/assets/15073846/23345101/2a5dacc8-fc91-11e6-941b-d42a042a9c48.PNG">

**Comment by Manosmer** [comment]
I tried to isolate the issue and I think that the problem is that `./test/{unit,integration}/**/*-test.js` path at package.json's scripts is pointing to one or more files that do not exist. Because, if I customly give the command `node_modules\.bin\tap ./test/unit/**/*-test.js` the tests run as they should.

**Comment by Manosmer** [comment]
Ok I just found the issue!!! Pfff.... haha! The problem is that in package.json, in the test script, the path parameter for nyc tap `./test/{unit,integration}/**/*-test.js` must not be included in single quotes! I don't how to implement that and also I don't know if single quotes are required from Linux systems.

**Comment by gr2m** [comment]
the problem I have seen before is that without the single quotes, on unix-based system the passed argument is parsed before passing to the process, and it ended up run tests multiple times. But I cannot reproduce the problem myself anymore, so I’m okay with removing the quotes again. Maybe it was fixed meanwhile. Can you send a PR for that? If you could check the [other repositories](http://docs.hood.ie/en/latest/about/architecture.html), too, that’d be great

**Comment by gr2m** [comment]
fyi the `help wanted` label is one that Open Source projects assign to issues if they want to say that this is a good issue for others to work on. But here it feels more like you have been blocked, in that case it’s better to ping one of us directly here on GitHub

**Comment by Manosmer** [comment]
@gr2m, sorry for that again. I am new here and I am already making enough trouble. Also, another problem I have faced is in client tests (./test/unit/client/client-test.js):


<img width="960" alt="clienttests" src="https://cloud.githubusercontent.com/assets/15073846/23376993/e89e9850-fd36-11e6-83ae-4337dc008d9d.PNG">

Paths have backslashes

**Comment by gr2m** [comment]
you make no problem at all. You are tremendously helpful, because none of us has Windows, and you run into problems that we did not ourselves! It’s great that we have the tests going now. Could you paste a full log of the output of your tests somewhere, maybe create a Gist? https://gist.github.com/

**Comment by gr2m** [comment]
the problem here is that we pass a path string directly:
https://github.com/hoodiehq/hoodie/blob/62fe6276fa0434eae45c0e1023a82f6e390cf5e6/test/unit/client/client-test.js#L50

We should use [path.join](https://nodejs.org/api/path.html#path_path_join_paths) instead. We should _always_ use path.join, but looks like we missed that at several places.

Can you see if that helps fix the errors you are seeing?

**Comment by Manosmer** [comment]
@gr2m, I mean that I create a mess with labels 😛. Testlog for my system can be found here: https://gist.github.com/Litarhis/3339644005760e8651ddee2f27ddb933 . I see what you mean with path. We should implement that technique. 

NOTE: the test is being executed against the code I've made for the issue #668, thus coverage for parse-options is at 75%

**Comment by gr2m** [comment]
> coverage for parse-options is at 75%

that’s okay, we are not at 100% right now. We can address that separately. 
If you are interested in more detail, you can run `.\node_modules\.bin\nyc report --reporter=lcov` and then open `coverage\lcov-report\index.html` in your browser. It should show you a report similar to https://coveralls.io/builds/10341786/source?filename=server%2Findex.js, you can browser all files and see exactly which lines are not covered

**Comment by gr2m** [comment]
also start a PR so we can discuss there, makes things easier
