### ISSUE TITLE
docs: Then icon in the documentation side panel had been disappeared 

### ISSUE THREAD

**Issue by NimmiW** [hoodiehq/hoodie#702]
![image](https://cloud.githubusercontent.com/assets/26009680/23369386/342cb5cc-fd37-11e6-9f26-1bdae5b45e4e.png)

**Comment by NimmiW** [comment]
![image](https://cloud.githubusercontent.com/assets/26009680/23369718/4d16851c-fd38-11e6-9439-cefcef4519aa.png)

Where Can I find this 'low-profile-dog-1.png' ? @fozy81

**Comment by gr2m** [comment]
you can use that image attached:

![low-profile-dog](https://cloud.githubusercontent.com/assets/39992/23375869/c9c169f6-fcde-11e6-9c6f-6373d36ecb3c.png)

**Comment by gr2m** [comment]
Or maybe it would be more appropriate to use [Docs Chicken](http://hood.ie/animals/#docs-chicken)? 
![docs-chicken](https://cloud.githubusercontent.com/assets/39992/23375908/ed47eddc-fcde-11e6-9b9d-e9af7f0d7d47.png)

**Comment by fozy81** [comment]
Oops, I meant to reference this [file](https://github.com/hoodiehq/hoodie/blob/master/public/low-profile-dog-1.png).

I like the idea of using the Docs Chickens :+1:

**Comment by NimmiW** [comment]
@gr2m  and @fozy81 Then Let us use the Doc Chicken 👍
