### ISSUE TITLE
Code highlighting: line breaks are being ignored 

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#708]
<img width="852" alt="image" src="https://cloud.githubusercontent.com/assets/39992/23415411/f8f9d252-fd93-11e6-8ca1-fcd17328b5ae.png">

**Comment by NimmiW** [comment]
@gr2m I will fix this issue :) since I am currently doing some pages in the API documentation

**Comment by gr2m** [comment]
great :) If you could send a separate pull request for it, that’d be great

**Comment by NimmiW** [comment]
@gr2m I created a PR at https://github.com/hoodiehq/hoodie/pull/715 :) you can review it and let me know any changes.
