### ISSUE TITLE
docs: running `make` throws errors

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#717]
I get this error

```
writing output... [  4%] about/architecture                                                                                                                                
Exception occurred:
  File "/Library/Python/2.7/site-packages/docutils/writers/html4css1/__init__.py", line 381, in depart_enumerated_list
    self.compact_simple, self.compact_p = self.context.pop()
ValueError: too many values to unpack
```

Full log: https://gist.github.com/6913faffb390239e6b2ed19fa8ae26bc

When I reduce the content of `architecture.rst` to just 

```
Architecture
============
```

it works. Can I do anything about this? It works on readthedocs.org

**Comment by fozy81** [comment]
@gr2m It builds locally for me, I've installed sphinx and sphinx_rtd_theme. I'm on linux / ubuntu.

I do get a lot of warnings e.g.

hoodie/docs/about/architecture.rst:0: WARNING: nonlocal image URI found: https://david-dm.org/hoodiehq/hoodie-log.svg

Maybe these non-local images are affecting things?

**Comment by fozy81** [comment]
Maybe try updating sphinx install?

**Comment by NimmiW** [comment]
@fozy81 this works now :) by the way it gave me some warnings. but other stuff worked smooth.

**Comment by fozy81** [comment]
@NimmiW glad it works! Yes, lots of warnings, I've not quite sure why :-/ .  But at least it builds locally and so useful for testing. Thanks for all the changes you've made, i think it's close to all documentation being 'complete' :-)

**Comment by NimmiW** [comment]
@fozy81 yes it's close to the end of documentation. And its a pleasure to have your company and help all the time :)

**Comment by fozy81** [comment]
@gr2m Still having problems building the docs? I can look at the architecture file and see if I can debug.

**Comment by gr2m** [comment]
@fozy81 yes, here is the error message I get: https://gist.github.com/b3abd5a68b7a5183d652289766ef6f90

Is there any more info I can get you that would help with debugging?

**Comment by fozy81** [comment]
@gr2m I've opened the above pull request to update some of the link formatting in the affected file. This may help with the make/building of the docs locally. Excuse the delay...busy few weeks, this slipped through the net.

**Comment by gr2m** [comment]
no worries, thanks for looking again into it. I still get the `ValueError: too many values to unpack` with your latest changes, but additionally I know also see this:

```
/Users/gregor/Projects/hoodie/hoodie/docs/guides/deployment.rst:107: ERROR: Unknown target name: "admin".
```

here is the full log: https://gist.github.com/8dd38397a584ece6abcfa18fd00a1d7d

Let me know if there is anything I can do to help debug this
