### ISSUE TITLE
Data not syncing immediately after signing out

### ISSUE THREAD

**Issue by jorgepedret** [hoodiehq/hoodie#72]
I hit a "bug" when adding an item to the TODO list, then signing out. Then when I signed back in, the item wasn't there anymore.

**Steps to reproduce:**

1) Login as any user

```
hoodie.account.signIn('user', 'secret');
```

2) Refresh the page
3) Store a new item

```
hoodie.store.add('todo', { title: 'buy unsweetened almond milk' });
```

4) Immediately logout

```
hoodie.store.signOut();
```

5) Log back in

```
hoodie.account.signIn('user', 'secret');
```

**Expected results:**
The item that I added should be in the list when I get the todo data `hoodie.store.findAll('todo')`

**Current result:**
The item is not in the list

**Note:** Adding the item works fine if you wait a couple of seconds before Signing Out. Make sure you Sign Out immediately after adding the item.

**Comment by janl** [comment]
verified at JSConf by looking over @jorgepedret’s shoulder :)

**Comment by gr2m** [comment]
I thought about this issue a few times, but didn't find a nice solution yet. 

In general, check with `hoodie.store.isDirtry()` if you have local changes. If you do, let the user know that he'll loose data if she/he signs out now. 

But I agree that hoodie.account.signOut() should at least try to push local code once if store is dirty. Thanks for opening the issue.

As a side note, if you want local changes to be pushed directly, call `hoodie.remote.push()`
