### ISSUE TITLE
Adding comments in the code

### ISSUE THREAD

**Issue by NimmiW** [hoodiehq/hoodie#721]
When I was going through the code, sometimes I felt uneasy. I would be glad if anyone can put comments in the code. So that it will be helpful to all of us :)

I was going through this process:
http://docs.hood.ie/en/latest/guides/quickstart.html

When I executed the following CLI command, I got an client.js file 
`npm install hoodie --save`
Since there are no comments, I think adding comments will be helpful.

The hoodie-app-tracker also needed to be enriched with comments. :) Ex: https://github.com/hoodiehq/hoodie-app-tracker/blob/master/public/assets/js/index.js

**Comment by gr2m** [comment]
That is a great idea :) What would be great is to

1. Point us to places where you don’t understand what is happening in the code and we can explain it to you
2. Add comments explaining code as you figure it out. 

Ideally we try to keep the comments to a minimum and make the code itself as clear and readable as possible. But we figure it out case-by-case :)

**Comment by Manosmer** [comment]
@gr2m, if you remember we had a related discussion previously about commenting and we thought about including some javadoc-like commenting if we could find a decent tool for generating docs out of comments. I found it useful to mention it on that issue. Hope I did the good thing

**Comment by gr2m** [comment]
@Litarhis yeah it would still be great, but I think it’s out of scope of this issue. Usually the javadoc-like comments are outside of functions to describe their APIs and functionality, I think this issue is about some of the code being hard to understand.

**Comment by Manosmer** [comment]
If I may propose a suggestion, my thoughts were that we could provide javadoc-like comments at every file that includes a module, like cli/options.js, in order to have a solid description of our modules. That's why I thought that my mention suited in this issue. Of course, I don't want to create conflicts with the moderators' and creators' ideology for the project at all.

**Comment by gr2m** [comment]
no worries, all good :)

**Comment by gr2m** [comment]
@NimmiW we are still open to add more comments around the code, feel free to send separate pull requests or keep asking questions here. But I’ll close the issue due to inactivity
