### ISSUE TITLE
Proposal: better organization of issues, PRs and merges 

### ISSUE THREAD

**Issue by Manosmer** [hoodiehq/hoodie#728]
Recently, I created a guide for better maintainance of a repository, with simple rules that help me a lot, under the repo https://github.com/Litarhis/GuidesforRepos . If it is easy, I would like you to take a look and give me some feedback including your thoughts. I want to note that I don't want to advertise myself or be selfish or a show-off. I really think this would help. Sorry if this creates any mess.

**Comment by gr2m** [comment]
Hm I’m not sure about the emoji in the titles. Isn’t that what labels are for?

**Comment by Manosmer** [comment]
You can omit any part that's not following your way of thinking of course as long as the backbone of the ruleset stays solid :-)

**Comment by gr2m** [comment]
Hey @Litarhis would you mind me closing this issue? I’m going trough issues right now and closing the ones without recent activity
