### ISSUE TITLE
app-tracker on now is down

### ISSUE THREAD

**Issue by Sebring** [hoodiehq/hoodie#731]
Example app running on now-servers, https://hoodie-app-tracker.now.sh/, as [referenced in the docs](http://docs.hood.ie/en/latest/guides/deployment.html) gives 

> 502 | An error occured with your deployment.

Sorry if this is out of scope as it is not directly part of this repo.

**Comment by gr2m** [comment]
Thanks @Sebring! Sorry that nobody got back to you. I deployed the app myself and will have a look at it after May 10th when I’ll be back to Hoodie work :)

**Comment by gr2m** [comment]
fixed now, sorry for the delay!
