### ISSUE TITLE
Use EventSource

### ISSUE THREAD

**Issue by Acconut** [hoodiehq/hoodie#74]
Since EventSources are [quite qood supported](http://caniuse.com/#feat=eventsource) and [CouchDB supports them since 1.3](https://couchdb.readthedocs.org/en/1536-feature_add-docs/changes.html#event-source) we should consider using them.
If the browser supports EventSource and CORS use the ES else fall back to polling.

> Reportedly, CORS in EventSource is currently supported in Firefox 10+, Opera 12+, Chrome 26, other WebKit-based browsers will support soon.

**Comment by gr2m** [comment]
I have no opinion on that matter. We currently use long poll requests, @janl already [suggested to use the continuous feed](https://github.com/hoodiehq/hoodie.js/issues/54) instead.

I don't know about the pros & cons here. Can you guys help to make a comparison between the long poll, continuous feed and EventSource Implementation?

**Comment by gr2m** [comment]
closing this in favor of #54
