### ISSUE TITLE
@bbn asks via IRC: any thought to having hoodie.js served as part of the hoodie-app module

### ISSUE THREAD

**Issue by janl** [hoodiehq/hoodie#75]
@bbn on IRC:

```
[10:40:20] <bbn>     [20:41] heyo.
[10:40:20] <bbn>     [20:41] any thought to having hoodie.js served as part of the hoodie-app module?
[10:40:20] <bbn>     [20:42] I feel like they are part of the same unit. If I upgrade one shouldn't I upgrade the other?
```

Eventually hoodie.js should be dynamically complied from the modules that are enabled in the hoodie admin. That means that it would be shipped out of hoodie-app in a way that you ask for.

So yeah, eventually :)

**Comment by gr2m** [comment]
I have the same thought, good that we have a ticket for it now.

My fought is that hoodie-app brings the hoodie.js core, while the modules (share, public store, etc) bring hoodie.js extensions. These will be compiled / minified in pocket and served alltogether from hoodie-app. So if I add the share module, `hoodie.share` becomes available in the frontend as well.

I'm thinking about doing both: providing hoodie.js as standalone lib but also making it part of hoodie-app

**Comment by gr2m** [comment]
Moving to our [backlog](https://github.com/hoodiehq/hoodie.js/issues?milestone=2&state=closed)
