### ISSUE TITLE
401 Unauthorized when registering new user in Node.js 8

### ISSUE THREAD

**Issue by markwatsonatx** [hoodiehq/hoodie#754]
When registering a new user an unhandled exception occurs in Hoodie resulting in a 401 Unauthorized to be sent to the browser. This bug has been fixed in pouchdb-users (https://github.com/hoodiehq/pouchdb-users), but a new module has not been released in npm.

Here is the merge that fixes the bug:
https://github.com/hoodiehq/pouchdb-users/pull/10

In Node.js 6 and 7 a deprecation warning is printed. In Node.js 8 it seems like the function has been removed and is resulting in an unhandled exception. I believe the fix is to simply release a new version of pouchdb-users to npm.

**Comment by gr2m** [comment]
@markwatsonatx a new version is on its way, the PR was merged without fixing the commit message so no new release happened, but I pushed another commit to fix it, the build is running right now: https://travis-ci.org/hoodiehq/pouchdb-users

**Comment by markwatsonatx** [comment]
@gr2m I tested on Node 8, 7, and 6 and it works. I believe it is no longer working on Node 5 and below because the function signature is different. I have created a pull request in pouchdb-users. I am checking the version of Node.js and passing in the digest if the version >= 6. Not sure if there is a better way.

Pull request: https://github.com/hoodiehq/pouchdb-users/pull/12

**Comment by Terreii** [comment]
I'm sorry, for not following your guidelines.
I know I did miss something ...
😅 [Commit Message Conventions](https://github.com/hoodiehq/hoodie/blob/master/CONTRIBUTING.md#commit-message-conventions)

**Comment by markwatsonatx** [comment]
My previous statement was incorrect. It does work on Node 4 and 5. Something else was causing the issues I was experiencing.
