### ISSUE TITLE
docs: allow "Connection timed" errors

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#767]
Just had a false positive because david-dm.org didn’t work: https://travis-ci.org/hoodiehq/hoodie/builds/239553214#L1194

>  1. [L169]  https://david-dm.org/hoodiehq/hoodie-connection-status.svg Connection timed out - connect(2) for "david-dm.org" port 443 

@fozy81 is there a way to allow for connection time out errors? david-dm.org is tending to have that

**Comment by fozy81** [comment]
Just realised there's a special timeout flag on the link checker - so I've added that. Although if the link is known to be slow/flaky - maybe best not to include?

**Comment by gr2m** [comment]
Yes good point, I think we can ignore all the david-dm.org links, they are only coming from the badges in README.md files and people will realise very quickly if there is a problem with them. I’ll make a follow up issue
