### ISSUE TITLE
hoodie.ready property is still in the docs

### ISSUE THREAD

**Issue by khalillechelt** [hoodiehq/hoodie#768]
`hoodie.ready` is still in the docs right here: https://github.com/hoodiehq/hoodie/blob/master/docs/api/client/hoodie.rst#hoodieready

**Comment by gr2m** [comment]
Can you send a PR to remove it?

![image](https://cloud.githubusercontent.com/assets/39992/26821269/2c8bfc08-4aa6-11e7-85e5-8fb02e0ea86c.png)

**Comment by khalillechelt** [comment]
sure :D
