### ISSUE TITLE
Deploy to Heroku Button?

### ISSUE THREAD

**Issue by spencerthayer** [hoodiehq/hoodie#777]
It would be super useful if we could get a `Deploy to Heroku` button which would enable users to easily deploy your software to a Heroku instance without ever leaving the web browser. And with just a little configuration on the users end they'll have something running almost instantly. I propose the button because it is ideal for communities who need to make decisions quickly with the flexibility of something like Heroku.

It's very simple to do, just make sure that an app.json file is located in the repo root directory. More about Heroku deploy buttons [here](https://devcenter.heroku.com/articles/heroku-button).

[![Deploy](https://www.herokucdn.com/deploy/button.png)](https://heroku.com/deploy?template=https://github.com/hoodiehq/hoodie)

**Comment by gr2m** [comment]
hey @spencerthayer, I’ve seen you posting this across multiple repositories. We all like Heroku :) but could you explain your relation to Heroku and what your incentive is? Copy & pasting the same issue about adding an integration with a for-profit company could be taken as SPAM by some, I just want to clarify that it’s not. 

If you want to add information on how to deploy Hoodie to Heroku, then http://docs.hood.ie/en/latest/guides/deployment.html would be the right place, we’d welcome your pull request

**Comment by spencerthayer** [comment]
I'm working on a suite of security applications for activists. This suite relies on easy to use - and free tier - setup processes. Heroku's deploy to button is perfect for these activists to control their services and data without really knowing how to host anything. But most importantly, it's free for low use applications. I'm posting on a bunch of Hoodie like repositories hoping maybe one of them will bite and I can then start using that service. I plan on closing the other issues whenever someone bites. It sounds like maybe, that'll be you guys.

**Comment by gr2m** [comment]
thanks for the clarification :) 

We are big fans of https://zeit.co/now, deploying to it is fairly simple:
http://hood.ie/blog/single-line-deployment.html

Adding a deploy-to-heroku button to your app built with Hoodie should be fairly simple. Adding it to hoodie itself wouldn’t make much sense though, would it? It’s not an app itself, it’s a dependency for your app

**Comment by sudheesh001** [comment]
I agree with @gr2m I vote to close this issue.
