### ISSUE TITLE
node_modules/hoodie folder is 23,8mb

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#779]
![image](https://user-images.githubusercontent.com/39992/27712781-6e55b61c-5cdd-11e7-8b40-3477f165a8a1.png)

nearly all of it are unneeded things like the pandoc binary and docs. We should remove it by adding the ["files" setting](https://docs.npmjs.com/files/package.json#files) to `hoodie`’s package.json file and only list what’s needed to be published

**Comment by sohini-roy** [comment]
Thanks for the description, I would like to work on this issue :)

**Comment by sohini-roy** [comment]
#780

**Comment by sohini-roy** [comment]
#780 
please have a look and review

**Comment by gr2m** [comment]
The folder is now only **79 KB**! Thanks a ton @sohini-roy, this makes a huge difference :)

**Comment by espy** [comment]
Wow, thanks so much @sohini-roy ! 👍
