### ISSUE TITLE
Are there any First PR issues?

### ISSUE THREAD

**Issue by lucask42** [hoodiehq/hoodie#782]
Hello all, I was recommended to hoodie as a good place to start with contributing to open source projects.  Can someone direct me towards an issue that I can tackle?

**Comment by gr2m** [comment]
Welcome @lucask42 👋 

We don’t currently have any open I’m afraid. You can watch the https://github.com/hoodiehq/camp repository to get notified about new issues ready for taking. I plan to prepare a few myself this weekend. I’d be happy to ping you in this issue, too, if you prefer.

Is there anything specific you would like to contribute? We have code, design, documentation and editorial contributors, and also a [fundraiser on Open Collective](https://opencollective.com/hoodie)

**Comment by lucask42** [comment]
Thanks for the welcome 👋 I'm most interested in code and design.  I'll gladly help with docs, as well.

I've watched the /camp repository and I'll check in early next week.  Cheers

**Comment by lucask42** [comment]
Also, is there a better way for me to ask questions than creating a new issue?  Please pardon my ignorance

**Comment by gr2m** [comment]
don’t worry, creating an issue is perfectly fine :) Maybe the best way is to ping us in our [chat](http://hood.ie/chat/).

I think I can close this issue now? Feel free to keep commenting if you still have questions

**Comment by gr2m** [comment]
I created a small docs issue here if you are interested: https://github.com/hoodiehq/camp/issues/122
