### ISSUE TITLE
Intro page

### ISSUE THREAD

**Issue by Ret3z** [hoodiehq/hoodie#806]
Why before loading to intro page have this picture but other page not have
![hoodie](https://user-images.githubusercontent.com/26427864/30867319-d4c39b4e-a305-11e7-9b30-75099170da57.jpg)

**Comment by gr2m** [comment]
That is odd in indeed. Does http://hood.ie/intro/ work for you?

**Comment by pingping-n** [comment]
I think "https" is mistake.

**Comment by gr2m** [comment]
https://hood.ie/intro/ does not work, we don’t have an SSL certificate set up at this point
