### ISSUE TITLE
distribute a version of hoodie that does not require browserify as a dependency

### ISSUE THREAD

**Issue by dominicbarnes** [hoodiehq/hoodie#825]
I'm working on creating a hoodie app built on [apex/up](https://up.docs.apex.sh/) which deploys applications via AWS Lambda. My app is a pretty simple hoodie app, which is a SPA that uses hoodie as the backend.

I only have 2 dependencies for the backend, which are `hoodie` and `pouchdb`, but even still the weight of my deployment is >35MB. I've been able to trim down to ~27MB using [node-prune](https://www.npmjs.com/package/node-prune), but that's still pretty heavy. (which makes my cold start times much higher than I want them to be)

I'm already bundling `/hoodie/client.js` in the build process for my front-end, so I have no need for `browserify` and all of it's dependencies. I see why it's there, as it's nice to have when just getting started. However, it would be great if there was a distribution of hoodie that didn't include those batteries.

**Comment by gr2m** [comment]
you can depend on [`@hoodie/server`](https://github.com/hoodiehq/hoodie-server) and [`@hoodie/client`](https://github.com/hoodiehq/hoodie-client) directly, does that help?

**Comment by dominicbarnes** [comment]
I was really hoping I could do just that! In that case, I'll close this issue and I'll re-open if that turns out to not work as well as I'd like.
