### ISSUE TITLE
more flexible logging

### ISSUE THREAD

**Issue by dominicbarnes** [hoodiehq/hoodie#826]
I'm working on creating a hoodie app built on [apex/up](https://up.docs.apex.sh/) which deploys applications via AWS Lambda. The way logging works on that platform is to emit them in a structured (JSON) format.

When using hoodie, the logs appear to go to `stderr` in an unstructured format, which ends up being interpreted as level=error with the entire line as the message (losing context like the time, level, etc).

It would be great if the logging in hoodie was more customizable, as I would like to hook into the logs and output them in a JSON format that up would be able to digest. At the least, it would be nice if hoodie output only errors to `stderr` and most everything else to `stdout`.

**Comment by gr2m** [comment]
that sounds like a bug, I agree that it should only log errors to `stderr`

**Comment by dominicbarnes** [comment]
That's just how npmlog works, it prints everything to stderr unless you override `log.stream` and do some more advanced stuff. (since in many cases, you may want stdout clean for piping between commands, while still wanting to print warnings/errors)

**Comment by dominicbarnes** [comment]
Since I'm going to be using `@hoodie/server` directly as per your recommendation on #825, I will probably just do some custom/advanced stuff with npmlog myself. I'll close this ticket since the more I think about it, it's out of scope for this package.
