### ISSUE TITLE
hoodie does not install with pnpm package manager

### ISSUE THREAD

**Issue by ghost** [hoodiehq/hoodie#858]
Hi there hoodie people,

Just wanting to let you know that I tried to take hoodie for a spin for the first time using your [quickstart instructions](http://docs.hood.ie/en/latest/guides/quickstart.html) but using [pnpm](https://github.com/pnpm/pnpm) instead of installing with `npm` and I was out of luck.

I have raised an issue on **pnpm** over [here](https://github.com/pnpm/pnpm/issues/1249). @zkochan, the developer of pnpm has offered a [solution for the problem](https://github.com/pnpm/pnpm/issues/1249#issuecomment-401628793) which can easily be fixed at your end apparently.

Regards, Justin Johansson

**Comment by kragil** [comment]
Hoodie is mostly dead. Sorry.

**Comment by ghost** [comment]
No worries. Thanks for reply.
