### ISSUE TITLE
windows 10 - npm start fails: syntax error in @hoodie/account-server package

### ISSUE THREAD

**Issue by salus-sage** [hoodiehq/hoodie#861]
i followed the quickstart guide http://docs.hood.ie/en/latest/guides/quickstart.html
OS = windows 10
node version = 4.4.4
npm version = 2.15.1

- during npm install hoodie, there are a bunch of warnings related to the node versions
![screenshot 67](https://user-images.githubusercontent.com/6399323/45168408-d22e2980-b218-11e8-9e6d-cd228f254baa.png)

- and when i did npm start, got a syntax error in @hoodie/account-server package, below is the screenshot
![screenshot 68](https://user-images.githubusercontent.com/6399323/45168443-e96d1700-b218-11e8-9448-9955dd2674a6.png)

this is a very interesting project, looking forward to contribute

**Comment by gr2m** [comment]
can you update to latest node / npm? Node 4 and npm 2 are no longer maintained / supported.

**Comment by salus-sage** [comment]
Thanks, that worked,
