### ISSUE TITLE
share data between users and groups

### ISSUE THREAD

**Issue by cphubs** [hoodiehq/hoodie#870]
Hi 
Can I write a big offline project like CMS or CRM or ERP with Hoodie? 
If possible. How can share users database or documents between other users or groups?

Thanks

**Comment by gr2m** [comment]
I don’t think Hoodie would be a good fit for that. Sharing is not implemented yet, it might become easier with the upcoming CouchDB 3, but there is no ETA and a lot of work would need to be put to adapt Hoodie for the new CouchDB
