### ISSUE TITLE
npm start command fails

### ISSUE THREAD

**Issue by jtdorseyiii** [hoodiehq/hoodie#872]
Hello!

I've come across the hoodie project this morning and wanted to try it out; however, I'm running in to a little problem. Using the commands in the readme, I cloned the repo and installed hoodie. When I attempt the start command... I am faced with this:
![hoodie start issue](https://user-images.githubusercontent.com/1382852/60593177-330e8b80-9d70-11e9-9a6e-37e653855ff7.PNG)

I haven't started to dig in to the problem myself yet, so I hope someone may have an answer... else, I guess I'll figure it out on my own!

Thanks in advance for any advice/help that can be given. :)

**Comment by md37** [comment]
Windows accepts backslashes, not slashes. One should change this in package.json file, depending which one OS is user on.

**Comment by gr2m** [comment]
I’m fairly sure that npm normalizes that based on the OS. But worth testing out if that’s the case, I’d love to know! I don’t have a Windows machine myself though

**Comment by md37** [comment]
Same problem on my Windows machine.
I'm going to fix it.
