### ISSUE TITLE
Make LocalStore listen to remote:remove events

### ISSUE THREAD

**Issue by hqm42** [hoodiehq/hoodie#88]
Just cleaning up silently [1] and not triggering store:remove feels asymmetrical to the other crud events coming from remote.

[1] https://github.com/hoodiehq/hoodie.js/blob/master/src/core/local_store.js#L345

**Comment by gr2m** [comment]
LocalStore listens to `remote:remove`. The comment is a bit misleading. When an object has been removed from remote, it gets removed locally and triggers the `remove` events, with `options.remote = true`.

Or does it not work for you?

**Comment by hqm42** [comment]
Lets say i have a todo app. I want to persist my todos using hoodie. Whenever a todo is removed from the local store (either via hoodie.store.remove or via remote) i want to receive an event (e.g. store:remove:todo). Right now I have to listen to 'store:remove:todo' and 'remote:remove:todo'. It's the same with add, update and change.

**Comment by gr2m** [comment]
no, just listen to `store:remove:todo`. It gets triggered when removed from remote as well. This is a bit confusing, which is why we decided to merge `hoodie.remote` into `hoodie.store` in #91
