### ISSUE TITLE
uuid collides frequently in V8

### ISSUE THREAD

**Issue by ericelliott** [hoodiehq/hoodie#89]
```
var test = function (iterations) {
  var collision = false;
    var ids = {},
      i,
      id;
    for (i = 0; i < iterations; i++) {
      id = uuid();
      if (!ids[id]) {
        ids[id] = id;        
      } else {
        collision = true;
        break;
      }
    }
  return collision ? 'fail' : 'pass';
};
```

```
> test(500);
"fail"
```

This test fails easily in V8 (probably other engines as well). In fact, this type of pure pseudo-random ID will always have probable collisions. See [cuid](http://usecuid.org/)

**Comment by gr2m** [comment]
Hey Eric, thanks so much for looking into Hoodie!

Thanks for pointing out this issue. We just went with a simple solution without putting lots of thoughts into it, but we agree that if collisions would happen as frequently as you pointed it out, that'd be a big problem.

To give you some background, I like the short UUIDs that used all all digits and a-z, for two reasons
1. when sharing data, URLs would be rather short, like myapp.com/abc4567
2. short ids use less space in the local storage, which is usually limited

But for one I think we can work around my two points and the collision problem outweighs the benefits of short IDs.

So we're happy to move on with your cuid lib, it's better than what we have atm. Wanna send a pull request?

**Comment by ericelliott** [comment]
I have considered a shorter version of cuid for short url purposes. The
random property would take a big hit, so it would be easier to guess other
existing IDs, but maybe that's not a huge problem. I could build up the id
as a numerical string and then base convert it to your character set. I'll
play with the math and try to land it in seven digits (a really big number).
- Eric

**Comment by gr2m** [comment]
Thanks Eric, let me know if there is anything I can help with

**Comment by ericelliott** [comment]
Sorry, I've been sick and I haven't had time to look at the short version of cuid(). You can shave bytes off off cuid() by requiring fewer random digits at the end, and possibly by removing the most significant bits from the timestamp. You can use BASE64 (it's currently BASE36, if I remember right), which should come out more compact. Anyway, those are the thoughts that occurred to me when I was thinking about the shorturl problem.

**Comment by gr2m** [comment]
I'd also leave out the "c" in the beginning to save a few bytes. Wanna send a pull request? 

btw I started to rewrite hoodie.js based on your suggestions: https://github.com/hoodiehq/hoodie.js/pull/107

**Comment by ericelliott** [comment]
I added a `.slug()` method to cuid for things like this: https://github.com/dilvie/cuid
