### ISSUE TITLE
any plan for php port of the backend ?

### ISSUE THREAD

**Issue by beppe9000** [hoodiehq/hoodie#899]
is there a documentation of the protocol somewhere ?

**Comment by gr2m** [comment]
no, sorry

**Comment by beppe9000** [comment]
Is the server-side api communication protocol documented?

**Comment by gr2m** [comment]
The Hoodie server part hast mostly two aspects

1. A Store API which is compatible with CouchDB's database-level APIs
2. An Account API which is documented here: https://accountjsonapi.docs.apiary.io/

**Comment by beppe9000** [comment]
Thanks I'll look into those
