### ISSUE TITLE
remove dependency on jQuery

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#9]
hoodie.js currently depends on jQuery for pragmatic reasons. It mainly uses jQuery's ajax and promise implementations.

**Comment by gr2m** [comment]
closed by accident

**Comment by gr2m** [comment]
moved to backlog

**Comment by gr2m** [comment]
for reference:
https://github.com/cesarvarela/jQuery.deferred-stand-alone
https://github.com/warpdesign/deferred-js

I'm sure I've seen a project a while a go that used only the jQuery modules needed for Promises. I think it was a requirejs example app or something. I remember that my first though was: we can do that, too. That's the piece we need to get rid of jQuery dependencie, while remaining compatible with it.

**Comment by svnlto** [comment]
another reference https://github.com/tildeio/rsvp.js

**Comment by gr2m** [comment]
on JavaScript's native `Promise` object: www.html5rocks.com/en/tutorials/es6/promises/

what I could find on jQuery's discussion:
Now that http://bugs.jquery.com/ticket/14510

I'm watching this closely. I think compatibility with jQuery is important for our target group, but if the core team decides to become Promise/A compatible in the future, that's what would convince me to do the same. And I think they will, as having a native JavaScript Promise object and having more and more of the native JavaScript APIs using it will outweigh the downside of harder debugging / development. 

rsvp.js came up with the error event for thrown errors, that might help a bit already, I like that

``` js
RSVP.on('error', function(reason) {
  console.assert(false, reason);
});
```

**Comment by svnlto** [comment]
A very sane decision, we really should aim to be Promise/A compliant at some point.

**Comment by louisremi** [comment]
The ajax module could be replaced by [superagent](https://github.com/visionmedia/superagent).
But many projects rely on jQuery. It could be good to give the option of using jQuery OR standalone  replacement modules.

**Comment by JosefJezek** [comment]
Please No jQuery!

http://youmightnotneedjquery.com

**Comment by wajerrr** [comment]
+1

**Comment by svnlto** [comment]
getting there, slowly.

**Comment by gr2m** [comment]
I think the only remaining thing we use is the AJAX, shouldn't be hard to get rid of that, too

**Comment by svnlto** [comment]
dont think so, we could just reuse pouchdbs ajax implementation https://github.com/pouchdb/pouchdb/blob/master/lib/deps/ajax.js

**Comment by gr2m** [comment]
yes, that's the plan

**Comment by andru** [comment]
I'm working on a React app with no jQuery and just got bitten by this.

`Uncaught TypeError: Cannot read property 'ajax' of undefined`

I've always felt a bit intimidated to get stuck in on Hoodie but it seems like this might be a good starting contribution for me if nobody's already on it. Anyone?

**Comment by gr2m** [comment]
Nope, all yours :)
