### ISSUE TITLE
Make sure store.add only accepts objects as data

### ISSUE THREAD

**Issue by xMartin** [hoodiehq/hoodie#90]
So looks as if `store.add` and `store.save` expect a JavaScript object as data. I skimmed the code and found checks for typeof 'object' and it is passed to jQuery.extend with a new object as first argument which always returns an object (even if you pass an array).

I would propose to really make sure it is an object that is passed (not an array or what not). Things are getting funny otherwise. For example if I pass `[1,2,3]` the JSON would end up being `{"0":1,"1":2,"2":3}`.

I didn't test. This is just what I assume from skimming a part of the code that looked relevant.

**Comment by gr2m** [comment]
good catch. I thought about using jQuery's [isPlainObject](http://api.jquery.com/jQuery.isPlainObject/) method for the check, but that would exclude instances like `car = new Car( atts ); hoodie.store.add('car', car)`.

So I'll check if the passed object is an Array and reject if it is. We might allow to pass an array of objects at some point, but nobody asked for that yet.
