### ISSUE TITLE
taskStore = hoodie.store('task'); taskStore.add(task); taskStore.findAll()

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#97]
This is our current store API:

``` js
hoodie.store.find('song', 'id123')
hoodie.store.findAll('song' )
hoodie.store.add('song', object)
hoodie.store.update('song', 'id123', new_properties )
hoodie.store.updateAll( 'song', new_properties)
hoodie.store.remove('song', 'id123')
hoodie.store.removeAll('song')
hoodie.store.on(event, callback)
```

I was thinking to add an alternative notation, that would go like this:

``` js
hoodie.store('song').find('id123')
hoodie.store('song').findAll()
hoodie.store('song').add(object)
hoodie.store('song').update(new_properties )
hoodie.store('song').updateAll( new_properties)
hoodie.store('song').remove('id123')
hoodie.store('song').removeAll()
```

I see myself needing this kind of namespaced store pretty often, for example for the share extension, where I need to implement all the store methods, but without passing the type, as it's always `$share` [src/extensions/share.js](https://github.com/hoodiehq/hoodie.js/blob/master/src/extensions/share.js#L23). I can see many future plugins having a need for that.

This is nothing urgent, but wanted to get it out of my head finally

**Comment by svnlto** [comment]
:+1: on the alternative syntax.

**Comment by gr2m** [comment]
I want to hack this out before leaving for holidays on Thursday. This should be rather simple in v0.3

what do you think about not only to allow to scope on a type, but also on one object?

``` js
var song = { type: 'song', id: '123', name: 'Urlaub in Polen'}

hoodie.store(song).find()
hoodie.store(song).update(new_properties )
hoodie.store(song).remove()

hoodie.store(song).on('update', cb)
hoodie.store(song).on('remove', cb)
hoodie.store(song).on('change', cb)
```

**Comment by gr2m** [comment]
@espy what do you think about it?
