### ISSUE TITLE
problem saving data with "my first hoodie" app

### ISSUE THREAD

**Issue by jmarca** [hoodiehq/hoodie#98]
I dropped the latest hoodie.js into the stock "my first hoodie" app, and hit a bug saving data.

using hoodie.js commit id 22c1d55bb5db4c3bae242bbd318badd31fece493

none of the "to do list" entries get saved to couchdb.

Not sure about the internals of hoodie, so I hesitate to make a pull request, but I traced it to https://github.com/hoodiehq/hoodie.js/blob/master/dist/hoodie.js#L2999

In the line

``` javascript
var promise = AccountRemote.__super__.push.apply(this, objects);
```

objects is an array of objects to save to couchdb, but when invoking push.apply(this,objects), push only ends up seeing a single object, given its  method signature is `Remote.prototype.push = function(objects)`

That is, fun.apply(thisArg[, argsArray]) is sending the array of objects as the arguments, but only the first is hitting `objects`.  What you really want is 

``` javascript
var promise = AccountRemote.__super__.push.apply(this, [objects]);
```

So that the `argsArray` is an array, and the first element of that array is also the array, and so the full array of objects gets stashed in `objects`.

I _think_ the change should be made here:

https://github.com/hoodiehq/hoodie.js/blob/master/src/core/account_remote.js#L127

**Comment by gr2m** [comment]
Thanks @jmarca, should be good now.
