### ISSUE TITLE
headless testing: find alternative to testem

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie#99]
one that is fast, so it's good to make tests on file changes

**Comment by svnlto** [comment]
considering porting the [phantomjs runner](https://github.com/hoodiehq/hoodie.js/blob/8df75058e65f809b80067b0b3c23d2c17aa3aa6f/test/lib/phantomjs_test_runner.coffee) from the CoffeeScript version of the project

**Comment by svnlto** [comment]
So, I've had a conversation with @remy and a few others about testing / test runners and [karma](http://karma-runner.github.io/) was mentioned as an alternative to testem. Having had a quick read of the docs and watching the introduction video I have to say that I really like it.

**Comment by gr2m** [comment]
I like that you like it. Let's optimize for fun™

I'm focussing on the Plugin API at the moment, can you get on this one? It would really be nice to have tests running nicely again

**Comment by svnlto** [comment]
@gr2m going to close this as we're using `karma` now.

**Comment by g-patel** [comment]
Just found this thread from google. I have used testem to more extent than karma.

@gr2m @svnlto any comparison insights between karma and testem from your experience?

**Comment by gr2m** [comment]
this thread is over 3 years old :) I haven’t use either since then

**Comment by g-patel** [comment]
okay. thanks for reply.
